DAEDrupalInterface: modules/algorithms/algorithms_copy.inc File Reference
modules/algorithms/algorithms_copy.inc File Reference
Functions
algorithms_copy_run ()
Copies the output of a run from a user's uploads directory to their uploads directory.
algorithms_run_done ($run)
Confirms a run is finished.
algorithms_copy ($run)
Actually copies the files between runs and uploads.
algorithms_get_output_files ($output)
algorithms_copy_make_dest_dir ($run)
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file algorithms_copy.inc.
Function Documentation
algorithms_copy ($ run)
Actually copies the files between runs and uploads.
Creates a directory to place the output files named algorithm_run-id
Parameters:
$run the run id.
Definition at line 81 of file algorithms_copy.inc.
References $uploads, algorithms_check_files_moved_to_runs(), algorithms_copy_make_dest_dir(), algorithms_get_output_files(), and home_directory_change_usage().
Referenced by algorithms_copy_run().
algorithms_copy_make_dest_dir ($ run)
Definition at line 123 of file algorithms_copy.inc.
References $db, $uploads, getDAEDatabase(), and home_directory_make_directory().
Referenced by algorithms_copy().
algorithms_copy_run ()
Copies the output of a run from a user's uploads directory to their uploads directory.
Confirms that the run exists and is finished. Creates a directory with the name of the run underscore run id in My Uploads
Definition at line 36 of file algorithms_copy.inc.
References algorithms_copy(), algorithms_run_done(), and algorithms_valid_run().
algorithms_get_output_files ($ output)
Definition at line 104 of file algorithms_copy.inc.
Referenced by algorithms_copy().
algorithms_run_done ($ run)
Confirms a run is finished.
Requires run status vars and the database class
Parameters:
$run the run id.
Definition at line 57 of file algorithms_copy.inc.
References $db, $user, and getDAEDatabase().
Referenced by algorithms_copy_run().