DAEDrupalInterface: modules/algorithms/algorithms_modify.inc File Reference
modules/algorithms/algorithms_modify.inc File Reference
Functions
modify_algorithm_ui ()
modify_form ()
formContent ($sn, $val)
getExists ($aname, $aversion)
getAlgName ($aid)
IOpart ($val, $sn)
basicInfo ($aid)
cleanStepsAfter ($sn)
getAllAlgIdName ()
choose_type ()
ct_content ($sn, $val)
ct_create_content ()
ct_select_content ($val)
ct_select_sub1_content ($val)
ct_select_sub2_content ($val)
save_type ()
check_version_page ($aname, $aversion)
submit_page ()
algorithms_mail ($key, &$message, $params)
Function Documentation
algorithms_mail ($ key, &$ message, $ params)
Definition at line 604 of file algorithms_modify.inc.
References $user.
basicInfo ($ aid)
Definition at line 201 of file algorithms_modify.inc.
References $db, $result, and getDAEDatabase().
Referenced by formContent().
check_version_page ($ aname, $ aversion)
Definition at line 377 of file algorithms_modify.inc.
References $db, $result, and getDAEDatabase().
Referenced by submit_page().
choose_type ()
Definition at line 247 of file algorithms_modify.inc.
References ct_content().
cleanStepsAfter ($ sn)
Definition at line 231 of file algorithms_modify.inc.
ct_content ($ sn, $ val)
Definition at line 254 of file algorithms_modify.inc.
References ct_create_content(), ct_select_content(), ct_select_sub1_content(), and ct_select_sub2_content().
Referenced by choose_type().
ct_create_content ()
Definition at line 293 of file algorithms_modify.inc.
Referenced by ct_content().
ct_select_content ($ val)
Definition at line 310 of file algorithms_modify.inc.
References $db, $result, and getDAEDatabase().
Referenced by ct_content().
ct_select_sub1_content ($ val)
Definition at line 340 of file algorithms_modify.inc.
References $db, and getDAEDatabase().
Referenced by ct_content().
ct_select_sub2_content ($ val)
Definition at line 351 of file algorithms_modify.inc.
References $db, and getDAEDatabase().
Referenced by ct_content().
formContent ($ sn, $ val)
Definition at line 24 of file algorithms_modify.inc.
References basicInfo(), getAlgName(), getAllAlgIdName(), getExists(), and IOpart().
Referenced by modify_form().
getAlgName ($ aid)
Definition at line 85 of file algorithms_modify.inc.
References $db, and getDAEDatabase().
Referenced by formContent().
getAllAlgIdName ()
Definition at line 234 of file algorithms_modify.inc.
References $db, $result, and getDAEDatabase().
Referenced by formContent().
getExists ($ aname, $ aversion)
Definition at line 78 of file algorithms_modify.inc.
References $db, and getDAEDatabase().
Referenced by formContent().
IOpart ($ val, $ sn)
Definition at line 92 of file algorithms_modify.inc.
References $db, $result, and getDAEDatabase().
Referenced by formContent().
modify_algorithm_ui ()
Definition at line 5 of file algorithms_modify.inc.
modify_form ()
Definition at line 15 of file algorithms_modify.inc.
References formContent().
save_type ()
Definition at line 362 of file algorithms_modify.inc.
References $db, and getDAEDatabase().
submit_page ()
Definition at line 398 of file algorithms_modify.inc.
References $user, check_version_page(), and getPID().