DAEDrupalInterface: modules/algorithms/algorithms_my_runs.inc File Reference
modules/algorithms/algorithms_my_runs.inc File Reference
Build a list of runs initiated by the authenticated user.
Functions
algorithms_my_runs ()
algorithms_run_deleted ($run)
Checks to see if the user has "deleted" the run.
algorithms_get_run_input_filename ($run)
Looks first in the spool directory then in the run directory for an input file.
algorithms_get_run_info ()
Responds to AJAX calls from My Runs page for information on a given Run.
algorithms_run_get_status ($run)
Retreives a run's status from the DAE db.
algorithms_get_run_info_failed ($failure)
Returns information on a run failure.
algorithms_get_run_info_working ($run)
Returns information on a run in progress.
algorithms_get_run_info_done ($run)
Gathers information on a finished run and moves files to runs from spool if necessary.
run_on_database ($run)
algorithms_get_database_run_info_done ($run)
algorithms_get_home_folder_run_info_done ($run)
algorithms_check_files_moved_to_runs ($run)
algorithms_save_output_to_db ($run)
Detailed Description
Build a list of runs initiated by the authenticated user.
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file algorithms_my_runs.inc.
Function Documentation
algorithms_check_files_moved_to_runs ($ run)
Definition at line 397 of file algorithms_my_runs.inc.
Referenced by algorithms_copy(), algorithms_get_database_run_info_done(), and algorithms_get_home_folder_run_info_done().
algorithms_get_database_run_info_done ($ run)
Definition at line 264 of file algorithms_my_runs.inc.
References $db, $input, algorithms_check_files_moved_to_runs(), and getDAEDatabase().
Referenced by algorithms_get_run_info_done().
algorithms_get_home_folder_run_info_done ($ run)
Definition at line 328 of file algorithms_my_runs.inc.
References $db, $user, algorithms_check_files_moved_to_runs(), getDAEDatabase(), and hd_scandir().
Referenced by algorithms_get_run_info_done().
algorithms_get_run_info ()
Responds to AJAX calls from My Runs page for information on a given Run.
This function requires the global variable $spool to be set to the appropriate directory and takes the assumption that all negative statuses are failures.
If the run is complete and the files have not already been moved, the function moves files from spool to the user's runs directory when it calls algorithm_run_info_done()
Definition at line 141 of file algorithms_my_runs.inc.
References $user, algorithms_get_run_info_done(), algorithms_get_run_info_failed(), algorithms_get_run_info_working(), algorithms_run_get_status(), and algorithms_valid_run().
algorithms_get_run_info_done ($ run)
Gathers information on a finished run and moves files to runs from spool if necessary.
This function requires the UI and DB classes
Parameters:
$run the run id.
Definition at line 248 of file algorithms_my_runs.inc.
References algorithms_get_database_run_info_done(), algorithms_get_home_folder_run_info_done(), and run_on_database().
Referenced by algorithms_get_run_info().
algorithms_get_run_info_failed ($ failure)
Returns information on a run failure.
The function assumes the unix error numbers are positive
Parameters:
$failure the (positive) status integer from the DAE database
Definition at line 195 of file algorithms_my_runs.inc.
Referenced by algorithms_get_run_info().
algorithms_get_run_info_working ($ run)
Returns information on a run in progress.
This function requires the UI class and db class
Information on runtime is gathered and returned
Parameters:
$run the run id.
Definition at line 216 of file algorithms_my_runs.inc.
References $db, and getDAEDatabase().
Referenced by algorithms_get_run_info().
algorithms_get_run_input_filename ($ run)
Looks first in the spool directory then in the run directory for an input file.
This function requires the global variables $runs and $spool to be set to the appropriate directories
If no input file is found, an empty string is returned
Parameters:
$run the run id.
Todo:
Almost definitely not stable.
Definition at line 96 of file algorithms_my_runs.inc.
References $db, $input, getDAEDatabase(), and hd_scandir().
Referenced by algorithms_my_runs().
algorithms_my_runs ()
Definition at line 33 of file algorithms_my_runs.inc.
References $db, $ui, $user, algorithms_get_run_input_filename(), algorithms_run_deleted(), getDAEDatabase(), and getPID().
algorithms_run_deleted ($ run)
Checks to see if the user has "deleted" the run.
This function requires the drupal MySQL database
Returns 1 (true) if the run has been deleted
Parameters:
$run the run id.
Definition at line 81 of file algorithms_my_runs.inc.
Referenced by algorithms_my_runs().
algorithms_run_get_status ($ run)
Retreives a run's status from the DAE db.
This function will only allow users to check on their own runs
Parameters:
$run the run id.
Definition at line 175 of file algorithms_my_runs.inc.
References $db, $user, getDAEDatabase(), and getPID().
Referenced by algorithms_get_run_info().
algorithms_save_output_to_db ($ run)
Definition at line 421 of file algorithms_my_runs.inc.
run_on_database ($ run)
Definition at line 257 of file algorithms_my_runs.inc.
References $db, and getDAEDatabase().
Referenced by algorithms_get_run_info_done().