DAEDrupalInterface: modules/dae_wsdl/algowsdl.php File Reference
modules/dae_wsdl/algowsdl.php File Reference
Functions
procedure ($name)
invokeWSDL ($id)
Detailed Description
Author:
Yingjie Li <yil308@lehigh.edu>
Version:
1.0
Todo:
This file and all subsequent functions should be moved out of the dae_data module eventually. It is here for pure convenience.
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see <http://www.gnu.org/licenses/>.
Definition in file algowsdl.php.
Function Documentation
invokeWSDL ($ id)
This PHP page genereates WSDL files for different algorithms with different inputs and outputs. Invokes the WSDL server for the algorithm given by $id. If $id is in the form of '<id>?wsdl' it's WSDL interface description is returned. If not, it is supposed to be combined with an HTTP_POST upload of the required input data.
Parameters:
[in] $id contains at least the algorithm id to invoke, possibly followed by '?wsdl'
Todo:
manage publication of remote services (i.e. not on 'localhost/dae')
Todo:
Is this needed if the service is remote ? If yes, what should we replace 'procedure' with ?
Definition at line 69 of file algowsdl.php.
References $db, $HTTP_RAW_POST_DATA, $i, $inputT, $inputType, $outputT, $outputType, $row, $server, getDAEDatabase(), and soap_server().
Referenced by dae_wsdl_get_wsdl().
procedure ($ name)
This function is currently only an empty stub. Eventually this will launch the effective execution of the corresponding algorithm (as set in the $name URIs array parameter)
Parameters:
$name the array of URIs to execute
Definition at line 38 of file algowsdl.php.