DAEDrupalInterface: modules/algorithms/algorithms_execute.inc File Reference
modules/algorithms/algorithms_execute.inc File Reference
For the purposes of keeping hardcoded algorithm execution separate, all hardcoded run functions are in this file.
Functions
algorithm_execute ($input, $onDatabase)
Executes an algorithm identified by its database id and its input parameter string.
create_database_flag ($runFolder, $input)
Creates a file in the $runFolder containing all dataitems contained in $input.
algorithms_create_spool_directories ($input)
algorithms_get_file_name ($path, $ext=true)
algorithms_get_extension_name ($path)
run_2 ($input)
run_102 ($input)
convert
run_143 ($input)
Ocrad OCR.
run_125 ($input)
Tesseract OCR.
run_124 ($input)
Kanungo Degradation Program (from QGar Library)
run_82 ($input)
run_XX ($path, $input)
Variables
global $db = getDAEDatabase()
Detailed Description
For the purposes of keeping hardcoded algorithm execution separate, all hardcoded run functions are in this file.
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Bart Lamiroy lamir.nosp@m.oy@c.nosp@m.se.le.nosp@m.high.nosp@m..edu
Version:
1.0
Date:
Last Updated 9/18/10
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
YOUR METHOD
To add a procedure for a given algorithm, simply declare a function with the name "run_\<algorithm id\>($input)" in a similiar fashion to the ones below such that <algorithm id> is the id of the algorithm in the oracle database.
  $input is an array of the format $input["file_\<input_number\>"] = '\<filepath\>'
where the file path is relative to the users uploads directory. Begin your function by declaring global $uploads; and then you can refer to files by concatenating $uploads and a filepath. $spool and $uploads have no trailing slashes, and filepaths begin with /, so there is no need to concatenate a slash when creating a full path (ex: $uploads . $filepath will produce a correct path)
$input also contains the run id of the algorithm run: $input['run_id']
As of 5/8/10 querying the database for an algorithm's required filetypes is not implemented, so for now there will be only one input ($input["file_0"])
Note: if you use a variable in place of the 0 because you have more than one file input (input["file_$i"]) you must put the array key in double quotes or the string $i will be passed instead of the value of $i.
Printing or echoing any text will cancel the construction of the web page, so simply take care of whatever system calls are necessary. No return value is necessary.
User id can be accessed by adding global $user; and referring to $user->uid
Look at run_XX for some example code.
REQUIREMENTS
In order for the webserver to retreive the results correctly, please follow these guidelines:
Run the method algorithms_create_spool_directories($input) and pass the $input. This call accomplishes the following:
Creates a subdirectory of $spool (/dae/spool/<user_id>/<algorithm_run_id>/) named after the algorithm run id ($input['run_id']) resulting a directory structure like /dae/spool/12/450 where 12 is a user id and 450 is the algorithm run id. Note: $spool = /dae/spool/<user_id>
Creates an output directory (/dae/spool/<user_id>/<algorithm_run_id>/output)
Returns path to /dae/spool/<user_id>/<algorithm_run_id> where input belongs and output directory is
Copy all input files to $spool . "/" . $input'run_id'
Declare the output directory as $spool . "/" . $input['run_id']. "/output"
Make sure your system calls/helper script will result in an end time being placed in the database when the run completes
For debugging purposes, the website does not forward to the runs page so that you can echo variables for testing purposes. Finished implementations should not have any echos or prints.
Definition in file algorithms_execute.inc.
Function Documentation
algorithm_execute ($ input, $ onDatabase)
Executes an algorithm identified by its database id and its input parameter string.
Parameters:
$input algorithm input array
$onDatabase database instance
Returns:
true if execution successfully launched, false otherwise
Definition at line 94 of file algorithms_execute.inc.
References $db, $input, databaseDebugMessage(), and getDAEDatabase().
Referenced by algorithms_run_form_submit(), and algorithms_run_go().
algorithms_create_spool_directories ($ input)
This function requires the global variable $spool to be set. It will create a subdirectory under the $spool directory identified by the current run identifier. It also creates a subdirectory 'output' under the previously mentioned one,
Parameters:
$input
Returns:
the name (string) of the created directory under $spool.
Definition at line 143 of file algorithms_execute.inc.
References $input.
Referenced by run_102(), run_124(), run_125(), run_143(), run_82(), and run_XX().
algorithms_get_extension_name ($ path)
Definition at line 170 of file algorithms_execute.inc.
algorithms_get_file_name ($ path, $ ext = true)
Definition at line 158 of file algorithms_execute.inc.
Referenced by run_102(), run_124(), run_125(), run_143(), and run_82().
create_database_flag ($ runFolder, $ input)
Creates a file in the $runFolder containing all dataitems contained in $input.
Parameters:
[in] $runFolder
[in] $input
Definition at line 123 of file algorithms_execute.inc.
References $input.
run_102 ($ input)
convert
Parameters:
$input
Todo:
These values should be global variables
Todo:
Solve a major security hole !
Bug:
This is a major security hole. People can set any value in 'algorithms_app_server' and just pipe comments to ssh !!
This is just a minor problem currently, since this code is not distributed and only people having admin access rights can modify the algorithms_app_server value.
Definition at line 195 of file algorithms_execute.inc.
References $db, $input, $uploads, $user, algorithms_create_spool_directories(), algorithms_get_file_name(), and databaseDebugMessage().
run_124 ($ input)
Kanungo Degradation Program (from QGar Library)
Parameters:
$input
This is where the hacking starts. We're assuming (since we know it) that there's only one file input parameter
Todo:
These values should be global variables
Todo:
Solve a major security hole !
Bug:
This is a major security hole. People can set any value in 'algorithms_app_server' and just pipe comments to ssh !!
This is just a minor problem currently, since this code is not distributed and only people having admin access rights can modify the algorithms_app_server value.
Definition at line 417 of file algorithms_execute.inc.
References $db, $input, $uploads, $user, algorithms_create_spool_directories(), algorithms_get_file_name(), and databaseDebugMessage().
run_125 ($ input)
Tesseract OCR.
Parameters:
$input
This is where the hacking starts. We're assuming (since we know it) that there's only one file input parameter
Todo:
These values should be global variables
Todo:
Solve a major security hole !
Bug:
This is a major security hole. People can set any value in 'algorithms_app_server' and just pipe comments to ssh !!
This is just a minor problem currently, since this code is not distributed and only people having admin access rights can modify the algorithms_app_server value.
Definition at line 341 of file algorithms_execute.inc.
References $db, $input, $uploads, $user, algorithms_create_spool_directories(), algorithms_get_file_name(), and databaseDebugMessage().
run_143 ($ input)
Ocrad OCR.
Parameters:
$input
This is where the hacking starts. We're assuming (since we know it) that there's only one file input parameter (argument 2) and a file extension (argument 1)
Todo:
These values should be global variables
Todo:
Solve a major security hole !
Bug:
This is a major security hole. People can set any value in 'algorithms_app_server' and just pipe comments to ssh !!
This is just a minor problem currently, since this code is not distributed and only people having admin access rights can modify the algorithms_app_server value.
Definition at line 268 of file algorithms_execute.inc.
References $db, $input, $uploads, $user, algorithms_create_spool_directories(), algorithms_get_file_name(), and databaseDebugMessage().
run_2 ($ input)
Definition at line 185 of file algorithms_execute.inc.
References $input, and run_82().
run_82 ($ input)
This is where the hacking starts. We're assuming (since we know it) that there's only one file input parameter
Todo:
These values should be global variables
Todo:
Solve a major security hole !
Bug:
This is a major security hole. People can set any value in 'algorithms_app_server' and just pipe comments to ssh !!
This is just a minor problem currently, since this code is not distributed and only people having admin access rights can modify the algorithms_app_server value.
Definition at line 489 of file algorithms_execute.inc.
References $db, $input, $uploads, $user, algorithms_create_spool_directories(), algorithms_get_file_name(), and databaseDebugMessage().
Referenced by run_2().
run_XX ($ path, $ input)
Todo:
These values should be global variables
Todo:
Solve a major security hole !
Bug:
This is a major security hole. People can set any value in 'algorithms_app_server' and just pipe comments to ssh !!
This is just a minor problem currently, since this code is not distributed and only people having admin access rights can modify the algorithms_app_server value.
Definition at line 570 of file algorithms_execute.inc.
References $input, $uploads, $user, algorithms_create_spool_directories(), and databaseDebugMessage().
Variable Documentation
global $db = getDAEDatabase()
Definition at line 84 of file algorithms_execute.inc.
Referenced by Person\__construct(), algorithm_execute(), algorithms_copy_make_dest_dir(), algorithms_delete_access(), algorithms_delete_run_files(), algorithms_get_database_run_info_done(), algorithms_get_home_folder_run_info_done(), algorithms_get_run_info_working(), algorithms_get_run_input_filename(), algorithms_list(), algorithms_my_runs(), algorithms_run(), algorithms_run_choose(), algorithms_run_done(), algorithms_run_form(), algorithms_run_form_submit(), algorithms_run_get_status(), algorithms_run_go(), algorithms_run_title(), basicInfo(), check_comment_id(), check_version_page(), ct_select_content(), ct_select_sub1_content(), ct_select_sub2_content(), dae_data_browse(), dae_data_browse_dataitem(), dae_data_browse_dataitem_rate(), dae_data_browse_dataset_comment_rate(), dae_data_browse_get_results(), dae_data_browse_runoptions(), dae_data_browse_subset(), dae_data_build_page_image_list(), dae_data_comment_rating_exists(), dae_data_copy(), dae_data_copyright(), dae_data_display_datasets(), dae_data_download(), dae_data_download_before(), dae_data_get_activity(), dae_data_get_array_of_paths(), dae_data_get_dataset_hierarchy(), dae_data_get_dataset_info_array(), dae_data_get_dataset_leaves(), dae_data_get_download_size(), dae_data_get_file_info_array(), dae_data_get_file_path(), dae_data_get_page_element_info_array(), dae_data_get_page_image_path(), dae_data_get_pageimage_info_array(), dae_data_get_paths_from_result(), dae_data_get_rating(), dae_data_get_tags(), dae_data_page_element_form(), dae_data_page_element_form_submit(), dae_data_page_element_type_search(), dae_data_rating_exists(), dae_data_search_page_select(), dae_data_search_page_submit(), dae_data_search_results_page(), dae_data_tag_add_assoc(), dae_data_tag_form_submit(), dae_data_upload_submit(), dae_data_upload_validate(), dae_dataset_page(), dae_dataset_preview(), dae_file_page(), dae_page_element_add_interpretation(), dae_page_element_add_interpretation_submit(), dae_page_element_page(), dae_pageimage_page(), dae_query_pageimage(), dae_service_algorithms_service(), data_repository_display(), data_repository_queryurl(), dataitem_service_descript(), declareDAEType(), generate_isolated_pixelmask(), generate_pixelmask(), generic_hook_convert(), generic_hook_ocrad(), get_comment_information(), get_dataitem_comments(), get_dataitem_submitter(), get_page_element_boxes(), get_pageelement_properties(), getAlgName(), getAllAlgIdName(), getDescById(), getExists(), getNameById(), getNextPID(), getPIDByEmail(), home_directory_user(), insertPersonInfo(), IOpart(), parse_tree(), retrieveAlgorithmSOAPInputTypes(), retrieveAlgorithmSOAPOutputTypes(), retrieveAlgortithmInfo(), run_102(), run_124(), run_125(), run_143(), run_82(), run_on_database(), save_type(), sel1(), sel2(), show_stat_block(), sql_service(), updatePersonInfo(), and validatePreSelected().