DAEDrupalInterface: modules/algorithms/algorithms.module File Reference
modules/algorithms/algorithms.module File Reference
The algorithms module allows users to view and run algorithms.
Functions
algorithms_menu ()
algorithms_perm ()
algorithms_list ()
Builds a list of algorithms in the DAE database.
algorithms_valid_run ($run)
Confirms that the run ID in the URL is only a number.
Detailed Description
The algorithms module allows users to view and run algorithms.
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
This module is soon to be completely rewritten. It is currently based on the fact that algorithms are hosted and executed on a specific server. This assumption does not hold anymore since the projects architecture has evolved to a web-service oriented paradigm.
Although still operational, this module is to be considered as obsolete.
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file algorithms.module.
Function Documentation
algorithms_list ()
Builds a list of algorithms in the DAE database.
This function requires the DAE db
Unauthenticated users are allowed to view the list
Definition at line 168 of file algorithms.module.
References $db, and getDAEDatabase().
algorithms_menu ()
Implements hook_menu().
Definition at line 45 of file algorithms.module.
algorithms_perm ()
Implements hook_perm().
Definition at line 155 of file algorithms.module.
algorithms_valid_run ($ run)
Confirms that the run ID in the URL is only a number.
Sets a security message in case the run ID was an attempt at SQL injection
Parameters:
$run the run id.
Definition at line 287 of file algorithms.module.
Referenced by algorithms_copy_run(), algorithms_delete_run(), and algorithms_get_run_info().