DAEDrupalInterface: DAEDatabase Class Reference
DAEDatabase Class Reference
Generic class, providing all database interaction functions.
Public Member Functions
__construct ()
Constructor.
getConn ()
Current connection identifier $this->conn.
getSafeConn ()
Current safe connection identifier $this->conn.
i ($query, $variables=-1)
Transparent call to subclass function q() using the same parameters. Return value is discarded.
r ($query, $variables=-1)
Transparent call to subclass function q() using the same parameters. Return single row from result.
num_fields ($query)
Transparent call to a DMBS specific version returning the number of fields returned by a query.
field_name ($query, $i)
Transparent call to a DMBS specific version returning the name of a field returned by a query.
fetch_row ($query)
Transparent call to a DMBS specific version returning the current row of a query result.
convertDateFormat ($format)
Converts a date formatting string from the standard Oracle syntax to the effecively used DBMS syntax.
dateFormat ($fields, $format)
Generic function that builds upon overloading by inheriting classes to generate a date conversion query that is complatible by the underlying DMBS.
getDataItemType ($id)
SQL query returning type of a given dataitem id.
getAlgName ($id)
SQL query returning the name of an algorithm with a given id.
checkAlgExists ($id)
SQL query checking whether a given algorithm id exists.
checkConcurrentRuns ()
Checks whether the current Drupal user is under his/her quota of allowed concerrent algorithm runs.
checkDataSetHasChildren ($id)
runElapsedTime ($run)
runLength ($run)
Static Public Member Functions
static getDAEDatabase ()
Retrieves the current active Database or creates one if it doesn't exist (Singleton Design Pattern)
Public Attributes
$dbmsType
Database Management System used.
$defaultSysdateString = 'SYSDATE'
String representing the database system date variable or function.
$sysdateString = 'SYSDATE'
String representing the database system date variable or function.
$dateConversionString = 'to_char'
Database function providing conversion from a 'Date' format to a 'String' format (DBMS dependant)
$timestampFormat = 'd-M-Y h:i:s A'
Conversion parameters for 'Date' to 'String' (DBMS dependant)
Protected Attributes
$conn
Connection identifier.
$user
Database connection user name.
$pass
Database connection user password.
$safe_conn
Connection identifier for safe connexions.
$ro_user
Database read-only connection user name.
$ro_pass
Database read-only connection user password.
$host
Database hostname.
Static Protected Attributes
static $database = null
Singleton Pattern.
Detailed Description
Generic class, providing all database interaction functions.
This class is intended to be a single-point access to any kind of DBMS. It is currently extendended by inheritance to function with Oracle and MySQL.
The class is implemented as a Singleton Design Pattern. It is therefore guaranteed to have only a single instance at one time.
Author:
Bart Lamiroy lamir.nosp@m.oy@c.nosp@m.se.le.nosp@m.high.nosp@m..edu
Definition at line 69 of file daedatabase_db.inc.
Constructor & Destructor Documentation
DAEDatabase::__construct ()
Constructor.
Retrieves the Drupal the following global variables:
dae_db_user: affected to $this->user
dae-db_pass: affected to $this->pass
dae-db_server: affected to $this->host
$this->dbmsType is set to blank.
Reimplemented in DAEOracleDatabase, and DAEMySQLDatabase.
Definition at line 105 of file daedatabase_db.inc.
Member Function Documentation
DAEDatabase::checkAlgExists ($ id)
SQL query checking whether a given algorithm id exists.
Parameters:
[in] $id Database id number supposedly from algorithm table.
Returns:
true if an algorithm with the given $id exists, false otherwise.
Todo:
This function is DAE Data Model dependant and should be moved to a more specific file.
Definition at line 347 of file daedatabase_db.inc.
DAEDatabase::checkConcurrentRuns ()
Checks whether the current Drupal user is under his/her quota of allowed concerrent algorithm runs.
Returns:
true if the current Drupal user can launch at least one more algorithm run, false otherwise.
Todo:
This function is DAE Data Model dependant and should be moved to a more specific file.
Definition at line 364 of file daedatabase_db.inc.
References $user, and getPID().
DAEDatabase::checkDataSetHasChildren ($ id)
Checks whether a Dataset contains sub-datasets (children).
Parameters:
[in] $id Dataset database id
Returns:
true if the dataset with given id is associated to another dataset through the ASSOCIATE_DATASET table, false otherwise
Bug:
This function ignores the TYPE field of the ASSOCIATE_DATASET table, making the assumption that all associations are one-way inclusions.
Definition at line 387 of file daedatabase_db.inc.
DAEDatabase::convertDateFormat ($ format)
Converts a date formatting string from the standard Oracle syntax to the effecively used DBMS syntax.
This function is supposed to be overloaded by inheriting classes.
Parameters:
[in] $format the Oracle syntax format string
Returns:
a format string in the appropriate syntax. This string contains embedded beginning and end quotes.
Reimplemented in DAEMySQLDatabase.
Definition at line 269 of file daedatabase_db.inc.
Referenced by dateFormat().
DAEDatabase::dateFormat ($ fields, $ format)
Generic function that builds upon overloading by inheriting classes to generate a date conversion query that is complatible by the underlying DMBS.
The query is supposed to be in the form of F($fields, $format) like to_char(SYSDATE,"MON DD"). This function will replace:
the standard conversion function name by the overridden function name
convert SYSDATE references
replace Oracle syntax with the correct format string syntax
Parameters:
[in] $fields
[in] $format
Returns:
the DMBS compliant SQL query for date conversion
Definition at line 287 of file daedatabase_db.inc.
References convertDateFormat().
Referenced by runElapsedTime(), and runLength().
DAEDatabase::fetch_row ($ query)
Transparent call to a DMBS specific version returning the current row of a query result.
This function should be overloaded by deriving classes Each call is supposed to position the current row to the next row.
Parameters:
[in] $query the query that was issued (not the SQL string, but the DBMS-specific structure. e.g. 'ressource')
Returns:
the current row of the query result
Reimplemented in DAEOracleDatabase, and DAEMySQLDatabase.
Definition at line 254 of file daedatabase_db.inc.
References databaseDebugMessage().
DAEDatabase::field_name ($ query, $ i)
Transparent call to a DMBS specific version returning the name of a field returned by a query.
This function should be overloaded by deriving classes Fields are supposed to be numbered starting from 0.
Parameters:
[in] $query the query that was issued (not the SQL string, but the DBMS-specific structure. e.g. 'ressource')
[in] $i index of the column the field name is to be returned
Returns:
the name of field number $i in query $query.
Reimplemented in DAEOracleDatabase, and DAEMySQLDatabase.
Definition at line 239 of file daedatabase_db.inc.
References databaseDebugMessage().
DAEDatabase::getAlgName ($ id)
SQL query returning the name of an algorithm with a given id.
Parameters:
[in] $id Database id number from algorithm table.
Returns:
name of $id in algorithm table or false if query did not succeed.
Todo:
This function is DAE Data Model dependant and should be moved to a more specific file.
Definition at line 327 of file daedatabase_db.inc.
DAEDatabase::getConn ()
Current connection identifier $this->conn.
Returns:
the current connection identifier $this->conn if the calling Drupal User has the required access rights to do so. Returns call to getSafeConn() otherwise.
Definition at line 155 of file daedatabase_db.inc.
References $conn, and getSafeConn().
static DAEDatabase::getDAEDatabase () [static]
Retrieves the current active Database or creates one if it doesn't exist (Singleton Design Pattern)
This function violates classical inheritance encapsulation, in the sense that it creates derived class instances in function of the Drupal dae_db_application global variable.
Somewhere, somehow, when the Drupal daedatabase configuration is changed, this database gets reinitialized. That's the way it should, but it's not quite clear how and where this is done.
Definition at line 124 of file daedatabase_db.inc.
References $database, and databaseDebugMessage().
Referenced by getDAEDatabase().
DAEDatabase::getDataItemType ($ id)
SQL query returning type of a given dataitem id.
Parameters:
[in] $id Database id number from dataitem table.
Returns:
DATA_ITEM_PAGE_IMAGE if $id is a PAGE_IMAGE, DATA_ITEM_DATASET if it is a DATASET. Returns DATA_ITEM_UNKNOWN otherwise
Todo:
This function is DAE Data Model dependant and should be moved to a more specific file.
Definition at line 303 of file daedatabase_db.inc.
References r().
DAEDatabase::getSafeConn ()
Current safe connection identifier $this->conn.
Returns:
the current safe connection identifier $this->safe_conn otherwise.
Definition at line 169 of file daedatabase_db.inc.
References $safe_conn.
Referenced by getConn().
DAEDatabase::i ($ query, $ variables = -1)
Transparent call to subclass function q() using the same parameters. Return value is discarded.
Please note that q() is not defined in current class and is supposed to be implemented within the inherited class
Parameters:
[in] $query a valid SQL query string
Returns:
nothing
Definition at line 187 of file daedatabase_db.inc.
References databaseDebugMessage().
DAEDatabase::num_fields ($ query)
Transparent call to a DMBS specific version returning the number of fields returned by a query.
This function should be overloaded by deriving classes
Parameters:
[in] $query the query that was issued (not the SQL string, but the DBMS-specific structure. e.g. 'ressource')
Returns:
the number of fields returned by the query
Reimplemented in DAEOracleDatabase, and DAEMySQLDatabase.
Definition at line 223 of file daedatabase_db.inc.
References databaseDebugMessage().
DAEDatabase::r ($ query, $ variables = -1)
Transparent call to subclass function q() using the same parameters. Return single row from result.
Please note that q() is not defined in current class and is supposed to be implemented within the inherited class.
Parameters:
[in] $query a valid SQL query string
[in] $variables array of substitution values to inject into $query
Returns:
first row of the query result, discarding the rest
Definition at line 205 of file daedatabase_db.inc.
References $result, and databaseDebugMessage().
Referenced by getDataItemType(), and DAEOracleDatabase\searchTable().
DAEDatabase::runElapsedTime ($ run)
Bug:
The following code does not give correct results with MySQL
Definition at line 398 of file daedatabase_db.inc.
References $result, $user, and dateFormat().
DAEDatabase::runLength ($ run)
Definition at line 424 of file daedatabase_db.inc.
References $result, $user, and dateFormat().
Member Data Documentation
DAEDatabase::$conn [protected]
Connection identifier.
Definition at line 71 of file daedatabase_db.inc.
Referenced by getConn().
DAEDatabase::$database = null [static, protected]
Singleton Pattern.
Definition at line 84 of file daedatabase_db.inc.
Referenced by getDAEDatabase().
DAEDatabase::$dateConversionString = 'to_char'
Database function providing conversion from a 'Date' format to a 'String' format (DBMS dependant)
Definition at line 91 of file daedatabase_db.inc.
DAEDatabase::$dbmsType
Database Management System used.
Definition at line 81 of file daedatabase_db.inc.
DAEDatabase::$defaultSysdateString = 'SYSDATE'
String representing the database system date variable or function.
Definition at line 87 of file daedatabase_db.inc.
DAEDatabase::$host [protected]
Database hostname.
Definition at line 79 of file daedatabase_db.inc.
DAEDatabase::$pass [protected]
Database connection user password.
Definition at line 73 of file daedatabase_db.inc.
DAEDatabase::$ro_pass [protected]
Database read-only connection user password.
Definition at line 77 of file daedatabase_db.inc.
DAEDatabase::$ro_user [protected]
Database read-only connection user name.
Definition at line 76 of file daedatabase_db.inc.
DAEDatabase::$safe_conn [protected]
Connection identifier for safe connexions.
Definition at line 75 of file daedatabase_db.inc.
Referenced by getSafeConn().
DAEDatabase::$sysdateString = 'SYSDATE'
String representing the database system date variable or function.
Definition at line 89 of file daedatabase_db.inc.
DAEDatabase::$timestampFormat = 'd-M-Y h:i:s A'
Conversion parameters for 'Date' to 'String' (DBMS dependant)
Definition at line 93 of file daedatabase_db.inc.
DAEDatabase::$user [protected]
Database connection user name.
Definition at line 72 of file daedatabase_db.inc.
Referenced by checkConcurrentRuns(), runElapsedTime(), and runLength().
The documentation for this class was generated from the following file:
modules/daedatabase/daedatabase_db.inc