DAEDrupalInterface: DAEOracleDatabase Class Reference
DAEOracleDatabase Class Reference
Public Member Functions
__construct ()
Constructor.
fetch_array ($r, $mode=DATABASE_BOTH)
q ($query, $variables=-1)
u ($q, $variables=-1)
searchTable ($return, $search, $field, $select_fields, $from_table, $page_start=0, $page_end=10, $wildcard=array('start'=> false, 'end'=> true), $case_sensitive=false)
createUniqueEntry ($table, $field)
__destruct ()
num_fields ($query)
Overloaded call to a OCI8 specific version returning the number of fields returned by a query.
field_name ($query, $i)
Overloaded call to a OCI8 specific version returning the name of a field returned by a query.
fetch_row ($query)
Overloaded call to a OCI8 specific version returning the current row of a query result.
Detailed Description
Definition at line 641 of file daedatabase_db.inc.
Constructor & Destructor Documentation
DAEOracleDatabase::__construct ()
Constructor.
Retrieves the Drupal the following global variables:
dae_db_user: affected to $this->user
dae-db_pass: affected to $this->pass
dae-db_server: affected to $this->host
$this->dbmsType is set to blank.
databaseDebugMessage("Oracle Database created " . print_r($this,true));
Reimplemented from DAEDatabase.
Definition at line 643 of file daedatabase_db.inc.
References databaseDebugMessage().
DAEOracleDatabase::__destruct ()
Definition at line 812 of file daedatabase_db.inc.
Member Function Documentation
DAEOracleDatabase::createUniqueEntry ($ table, $ field)
Todo:
Check if this has security impact
Definition at line 792 of file daedatabase_db.inc.
DAEOracleDatabase::fetch_array ($ r, $ mode = DATABASE_BOTH)
Definition at line 680 of file daedatabase_db.inc.
DAEOracleDatabase::fetch_row ($ query)
Overloaded call to a OCI8 specific version returning the current row of a query result.
Each call positions the current row to the next row.
Parameters:
[in] $query the query that was issued (not the SQL string, but the OCI8-specific 'statement')
Returns:
the current row of the query result
Reimplemented from DAEDatabase.
Definition at line 850 of file daedatabase_db.inc.
DAEOracleDatabase::field_name ($ query, $ i)
Overloaded call to a OCI8 specific version returning the name of a field returned by a query.
Fields are numbered starting from 0.
Parameters:
[in] $query the query that was issued (not the SQL string, but the OCI8-specific 'statement')
[in] $i index of the column the field name is to be returned
Returns:
the name of field number $i in query $query.
Reimplemented from DAEDatabase.
Definition at line 837 of file daedatabase_db.inc.
DAEOracleDatabase::num_fields ($ query)
Overloaded call to a OCI8 specific version returning the number of fields returned by a query.
Parameters:
[in] $query the query that was issued (not the SQL string, but the OCI8-specific 'statement')
Returns:
the number of fields returned by the query
Reimplemented from DAEDatabase.
Definition at line 823 of file daedatabase_db.inc.
DAEOracleDatabase::q ($ query, $ variables = -1)
Definition at line 685 of file daedatabase_db.inc.
References databaseDebugMessage().
Referenced by searchTable().
DAEOracleDatabase::searchTable ($ return, $ search, $ field, $ select_fields, $ from_table, $ page_start = 0, $ page_end = 10, $ wildcard = array('start' => false, 'end' => true), $ case_sensitive = false)
Definition at line 739 of file daedatabase_db.inc.
References q(), and DAEDatabase\r().
DAEOracleDatabase::u ($ q, $ variables = -1)
Definition at line 716 of file daedatabase_db.inc.
References databaseDebugMessage().
The documentation for this class was generated from the following file:
modules/daedatabase/daedatabase_db.inc