DAEDrupalInterface: DAEMySQLDatabase Class Reference
DAEMySQLDatabase Class Reference
Public Member Functions
__construct ()
Constructor.
q ($query, $variables=-1)
fetch_array ($r, $mode=DATABASE_BOTH)
createUniqueEntry ($table, $field)
__destruct ()
convertDateFormat ($formatstring)
num_fields ($query)
Overloaded call to a MYSQL specific version returning the number of fields returned by a query.
field_name ($query, $i)
Overloaded call to a MYSQL specific version returning the name of a field returned by a query.
fetch_row ($query)
Overloaded call to a MYSQL specific version returning the current row of a query result.
Detailed Description
Definition at line 455 of file daedatabase_db.inc.
Constructor & Destructor Documentation
DAEMySQLDatabase::__construct ()
Constructor.
Retrieves the Drupal the following global variables:
dae_db_user: affected to $this->user
dae-db_pass: affected to $this->pass
dae-db_server: affected to $this->host
$this->dbmsType is set to blank.
Reimplemented from DAEDatabase.
Definition at line 457 of file daedatabase_db.inc.
References databaseDebugMessage().
DAEMySQLDatabase::__destruct ()
Todo:
Log this error more appropriately
Definition at line 523 of file daedatabase_db.inc.
Member Function Documentation
DAEMySQLDatabase::convertDateFormat ($ formatstring)
Conversion from Oracle type date formatting strings to MySQL date formatting strings
Parameters:
[in] $formatstring the Oracle format string
Returns:
the equivalent (or as close as possible) MySQL format string
Reimplemented from DAEDatabase.
Definition at line 542 of file daedatabase_db.inc.
DAEMySQLDatabase::createUniqueEntry ($ table, $ field)
Definition at line 517 of file daedatabase_db.inc.
DAEMySQLDatabase::fetch_array ($ r, $ mode = DATABASE_BOTH)
Definition at line 509 of file daedatabase_db.inc.
References databaseDebugMessage().
DAEMySQLDatabase::fetch_row ($ query)
Overloaded call to a MYSQL specific version returning the current row of a query result.
Each call positions the current row to the next row.
Parameters:
[in] $query the query that was issued (not the SQL string, but the MySQL-specific 'ressource')
Returns:
the current row of the query result
Reimplemented from DAEDatabase.
Definition at line 634 of file daedatabase_db.inc.
DAEMySQLDatabase::field_name ($ query, $ i)
Overloaded call to a MYSQL specific version returning the name of a field returned by a query.
Fields are numbered starting from 0.
Parameters:
[in] $query the query that was issued (not the SQL string, but the MySQL-specific 'ressource')
[in] $i index of the column the field name is to be returned
Returns:
the name of field number $i in query $query.
Reimplemented from DAEDatabase.
Definition at line 621 of file daedatabase_db.inc.
DAEMySQLDatabase::num_fields ($ query)
Overloaded call to a MYSQL specific version returning the number of fields returned by a query.
Parameters:
[in] $query the query that was issued (not the SQL string, but the MySQL-specific 'ressource')
Returns:
the number of fields returned by the query
Reimplemented from DAEDatabase.
Definition at line 607 of file daedatabase_db.inc.
DAEMySQLDatabase::q ($ query, $ variables = -1)
Todo:
Substitute variables in query with appropriate mysql_escape_string calls
Definition at line 489 of file daedatabase_db.inc.
References databaseDebugMessage().
The documentation for this class was generated from the following file:
modules/daedatabase/daedatabase_db.inc