DAEDrupalInterface: nusoap_wsdlcache Class Reference
nusoap_wsdlcache Class Reference
Public Member Functions
nusoap_wsdlcache ($cache_dir='.', $cache_lifetime=0)
createFilename ($wsdl)
debug ($string)
get ($wsdl)
obtainMutex ($filename, $mode)
put ($wsdl_instance)
releaseMutex ($filename)
remove ($wsdl)
nusoap_wsdlcache ($cache_dir='.', $cache_lifetime=0)
createFilename ($wsdl)
debug ($string)
get ($wsdl)
obtainMutex ($filename, $mode)
put ($wsdl_instance)
releaseMutex ($filename)
remove ($wsdl)
Public Attributes
$fplock
$cache_lifetime
$cache_dir
$debug_str = ''
Detailed Description
caches instances of the wsdl class
Author:
Scott Nichol <snichol@users.sourceforge.net>
Ingo Fischer <ingo@apollon.de>
Version:
Id
class.wsdlcache.php,v 1.7 2007/04/17 16:34:03 snichol Exp
public
Definition at line 18 of file class.wsdlcache.php.
Member Function Documentation
nusoap_wsdlcache::createFilename ($ wsdl)
creates the filename used to cache a wsdl instance
Parameters:
string $wsdl The URL of the wsdl instance
Returns:
string The filename used to cache the instance private
Definition at line 60 of file class.wsdlcache.php.
References $wsdl.
nusoap_wsdlcache::createFilename ($ wsdl)
creates the filename used to cache a wsdl instance
Parameters:
string $wsdl The URL of the wsdl instance
Returns:
string The filename used to cache the instance private
Definition at line 60 of file class.wsdlcache.php.
References $wsdl.
Referenced by get(), put(), and remove().
nusoap_wsdlcache::debug ($ string)
adds debug data to the class level debug string
Parameters:
string $string debug data private
Definition at line 70 of file class.wsdlcache.php.
nusoap_wsdlcache::debug ($ string)
adds debug data to the class level debug string
Parameters:
string $string debug data private
Definition at line 70 of file class.wsdlcache.php.
Referenced by get(), obtainMutex(), put(), releaseMutex(), and remove().
nusoap_wsdlcache::get ($ wsdl)
gets a wsdl instance from the cache
Parameters:
string $wsdl The URL of the wsdl instance
Returns:
object wsdl The cached wsdl instance, null if the instance is not in the cache public
Definition at line 81 of file class.wsdlcache.php.
References $wsdl, createFilename(), debug(), obtainMutex(), and releaseMutex().
nusoap_wsdlcache::get ($ wsdl)
gets a wsdl instance from the cache
Parameters:
string $wsdl The URL of the wsdl instance
Returns:
object wsdl The cached wsdl instance, null if the instance is not in the cache public
Definition at line 81 of file class.wsdlcache.php.
References $wsdl, createFilename(), debug(), obtainMutex(), and releaseMutex().
nusoap_wsdlcache::nusoap_wsdlcache ($ cache_dir = '.', $ cache_lifetime = 0)
constructor
Parameters:
string $cache_dir directory for cache-files
integer $cache_lifetime lifetime for caching-files in seconds or 0 for unlimited public
Definition at line 47 of file class.wsdlcache.php.
References $cache_dir, and $cache_lifetime.
nusoap_wsdlcache::nusoap_wsdlcache ($ cache_dir = '.', $ cache_lifetime = 0)
constructor
Parameters:
string $cache_dir directory for cache-files
integer $cache_lifetime lifetime for caching-files in seconds or 0 for unlimited public
Definition at line 47 of file class.wsdlcache.php.
References $cache_dir, and $cache_lifetime.
nusoap_wsdlcache::obtainMutex ($ filename, $ mode)
obtains the local mutex
Parameters:
string $filename The Filename of the Cache to lock
string $mode The open-mode ("r" or "w") or the file - affects lock-mode
Returns:
boolean Lock successfully obtained ?! private
Definition at line 124 of file class.wsdlcache.php.
References debug().
nusoap_wsdlcache::obtainMutex ($ filename, $ mode)
obtains the local mutex
Parameters:
string $filename The Filename of the Cache to lock
string $mode The open-mode ("r" or "w") or the file - affects lock-mode
Returns:
boolean Lock successfully obtained ?! private
Definition at line 124 of file class.wsdlcache.php.
References debug().
Referenced by get(), put(), and remove().
nusoap_wsdlcache::put ($ wsdl_instance)
adds a wsdl instance to the cache
Parameters:
object wsdl $wsdl_instance The wsdl instance to add
Returns:
boolean WSDL successfully cached public
Definition at line 144 of file class.wsdlcache.php.
References createFilename(), debug(), obtainMutex(), and releaseMutex().
nusoap_wsdlcache::put ($ wsdl_instance)
adds a wsdl instance to the cache
Parameters:
object wsdl $wsdl_instance The wsdl instance to add
Returns:
boolean WSDL successfully cached public
Definition at line 144 of file class.wsdlcache.php.
References createFilename(), debug(), obtainMutex(), and releaseMutex().
nusoap_wsdlcache::releaseMutex ($ filename)
releases the local mutex
Parameters:
string $filename The Filename of the Cache to lock
Returns:
boolean Lock successfully released private
Definition at line 172 of file class.wsdlcache.php.
References debug().
nusoap_wsdlcache::releaseMutex ($ filename)
releases the local mutex
Parameters:
string $filename The Filename of the Cache to lock
Returns:
boolean Lock successfully released private
Definition at line 172 of file class.wsdlcache.php.
References debug().
Referenced by get(), put(), and remove().
nusoap_wsdlcache::remove ($ wsdl)
removes a wsdl instance from the cache
Parameters:
string $wsdl The URL of the wsdl instance
Returns:
boolean Whether there was an instance to remove public
Definition at line 189 of file class.wsdlcache.php.
References $wsdl, createFilename(), debug(), obtainMutex(), and releaseMutex().
nusoap_wsdlcache::remove ($ wsdl)
removes a wsdl instance from the cache
Parameters:
string $wsdl The URL of the wsdl instance
Returns:
boolean Whether there was an instance to remove public
Definition at line 189 of file class.wsdlcache.php.
References $wsdl, createFilename(), debug(), obtainMutex(), and releaseMutex().
Member Data Documentation
nusoap_wsdlcache::$cache_dir
Definition at line 33 of file class.wsdlcache.php.
Referenced by nusoap_wsdlcache().
nusoap_wsdlcache::$cache_lifetime
Definition at line 28 of file class.wsdlcache.php.
Referenced by nusoap_wsdlcache().
nusoap_wsdlcache::$debug_str = ''
Definition at line 38 of file class.wsdlcache.php.
nusoap_wsdlcache::$fplock
Definition at line 23 of file class.wsdlcache.php.
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.wsdlcache.php
modules/soap_server/nusoap/lib/class.wsdlcache.php