DAEDrupalInterface: nusoap_server Class Reference
nusoap_server Class Reference
Public Member Functions
nusoap_server ($wsdl=false)
service ($data)
parse_http_headers ()
parse_request ($data='')
invoke_method ()
serialize_return ()
send_response ()
verify_method ($operation, $request)
parseRequest ($headers, $data)
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
add_to_map ($methodname, $in, $out)
register ($name, $in=array(), $out=array(), $namespace=false, $soapaction=false, $style=false, $use=false, $documentation='', $encodingStyle='')
fault ($faultcode, $faultstring, $faultactor='', $faultdetail='')
configureWSDL ($serviceName, $namespace=false, $endpoint=false, $style='rpc', $transport= 'http://schemas.xmlsoap.org/soap/http', $schemaTargetNamespace=false)
nusoap_server ($wsdl=false)
service ($data)
parse_http_headers ()
parse_request ($data='')
invoke_method ()
serialize_return ()
send_response ()
verify_method ($operation, $request)
parseRequest ($headers, $data)
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
add_to_map ($methodname, $in, $out)
register ($name, $in=array(), $out=array(), $namespace=false, $soapaction=false, $style=false, $use=false, $documentation='', $encodingStyle='')
fault ($faultcode, $faultstring, $faultactor='', $faultdetail='')
configureWSDL ($serviceName, $namespace=false, $endpoint=false, $style='rpc', $transport= 'http://schemas.xmlsoap.org/soap/http', $schemaTargetNamespace=false)
nusoap_server ($wsdl=false)
service ($data)
parse_http_headers ()
parse_request ($data='')
invoke_method ()
serialize_return ()
send_response ()
verify_method ($operation, $request)
parseRequest ($headers, $data)
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
add_to_map ($methodname, $in, $out)
register ($name, $in=array(), $out=array(), $namespace=false, $soapaction=false, $style=false, $use=false, $documentation='', $encodingStyle='')
fault ($faultcode, $faultstring, $faultactor='', $faultdetail='')
configureWSDL ($serviceName, $namespace=false, $endpoint=false, $style='rpc', $transport= 'http://schemas.xmlsoap.org/soap/http', $schemaTargetNamespace=false)
nusoap_server ($wsdl=false)
service ($data)
parse_http_headers ()
parse_request ($data='')
invoke_method ()
serialize_return ()
send_response ()
verify_method ($operation, $request)
parseRequest ($headers, $data)
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
add_to_map ($methodname, $in, $out)
register ($name, $in=array(), $out=array(), $namespace=false, $soapaction=false, $style=false, $use=false, $documentation='', $encodingStyle='')
fault ($faultcode, $faultstring, $faultactor='', $faultdetail='')
configureWSDL ($serviceName, $namespace=false, $endpoint=false, $style='rpc', $transport= 'http://schemas.xmlsoap.org/soap/http', $schemaTargetNamespace=false)
Public Attributes
$headers = array()
$request = ''
$requestHeaders = ''
$requestHeader = NULL
$document = ''
$requestSOAP = ''
$methodURI = ''
$methodname = ''
$methodparams = array()
$SOAPAction = ''
$xml_encoding = ''
$decode_utf8 = true
$outgoing_headers = array()
$response = ''
$responseHeaders = ''
$responseSOAP = ''
$methodreturn = false
$methodreturnisliteralxml = false
$fault = false
$result = 'successful'
$operations = array()
$wsdl = false
$externalWSDLURL = false
$debug_flag = false
Detailed Description
nusoap_server allows the user to create a SOAP server that is capable of receiving messages and returning responses
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
class.soap_server.php,v 1.63 2010/04/26 20:15:08 snichol Exp
public
nusoap_server allows the user to create a SOAP server that is capable of receiving messages and returning responses
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 16 of file class.soap_server.php.
Member Function Documentation
nusoap_server::add_to_map ($ methodname, $ in, $ out)
add a method to the dispatch map (this has been replaced by the register method)
Parameters:
string $methodname
string $in array of input values
string $out array of output values public
Deprecated:
Definition at line 4402 of file nusoap.php.
References $methodname.
nusoap_server::add_to_map ($ methodname, $ in, $ out)
add a method to the dispatch map (this has been replaced by the register method)
Parameters:
string $methodname
string $in array of input values
string $out array of output values public
Deprecated:
Definition at line 942 of file class.soap_server.php.
References $methodname.
nusoap_server::add_to_map ($ methodname, $ in, $ out)
add a method to the dispatch map (this has been replaced by the register method)
Parameters:
string $methodname
string $in array of input values
string $out array of output values public
Deprecated:
Definition at line 4400 of file nusoap.php.
References $methodname.
nusoap_server::add_to_map ($ methodname, $ in, $ out)
add a method to the dispatch map (this has been replaced by the register method)
Parameters:
string $methodname
string $in array of input values
string $out array of output values public
Deprecated:
Definition at line 942 of file class.soap_server.php.
References $methodname.
nusoap_server::configureWSDL ($ serviceName, $ namespace = false, $ endpoint = false, $ style = 'rpc', $ transport = 'http://schemas.xmlsoap.org/soap/http', $ schemaTargetNamespace = false)
Sets up wsdl object. Acts as a flag to enable internal WSDL generation
Parameters:
string $serviceName, name of the service
mixed $namespace optional 'tns' service namespace or false
mixed $endpoint optional URL of service endpoint or false
string $style optional (rpc|document) WSDL style (also specified by operation)
string $transport optional SOAP transport
mixed $schemaTargetNamespace optional 'types' targetNamespace for service schema or false
Definition at line 4508 of file nusoap.php.
References nusoap_base::setError().
nusoap_server::configureWSDL ($ serviceName, $ namespace = false, $ endpoint = false, $ style = 'rpc', $ transport = 'http://schemas.xmlsoap.org/soap/http', $ schemaTargetNamespace = false)
Sets up wsdl object. Acts as a flag to enable internal WSDL generation
Parameters:
string $serviceName, name of the service
mixed $namespace optional 'tns' service namespace or false
mixed $endpoint optional URL of service endpoint or false
string $style optional (rpc|document) WSDL style (also specified by operation)
string $transport optional SOAP transport
mixed $schemaTargetNamespace optional 'types' targetNamespace for service schema or false
Definition at line 1048 of file class.soap_server.php.
References nusoap_base::setError().
nusoap_server::configureWSDL ($ serviceName, $ namespace = false, $ endpoint = false, $ style = 'rpc', $ transport = 'http://schemas.xmlsoap.org/soap/http', $ schemaTargetNamespace = false)
Sets up wsdl object. Acts as a flag to enable internal WSDL generation
Parameters:
string $serviceName, name of the service
mixed $namespace optional 'tns' service namespace or false
mixed $endpoint optional URL of service endpoint or false
string $style optional (rpc|document) WSDL style (also specified by operation)
string $transport optional SOAP transport
mixed $schemaTargetNamespace optional 'types' targetNamespace for service schema or false
Definition at line 4506 of file nusoap.php.
References nusoap_base::setError().
nusoap_server::configureWSDL ($ serviceName, $ namespace = false, $ endpoint = false, $ style = 'rpc', $ transport = 'http://schemas.xmlsoap.org/soap/http', $ schemaTargetNamespace = false)
Sets up wsdl object. Acts as a flag to enable internal WSDL generation
Parameters:
string $serviceName, name of the service
mixed $namespace optional 'tns' service namespace or false
mixed $endpoint optional URL of service endpoint or false
string $style optional (rpc|document) WSDL style (also specified by operation)
string $transport optional SOAP transport
mixed $schemaTargetNamespace optional 'types' targetNamespace for service schema or false
Definition at line 1048 of file class.soap_server.php.
References nusoap_base::setError().
nusoap_server::fault ($ faultcode, $ faultstring, $ faultactor = '', $ faultdetail = '')
Specify a fault to be returned to the client. This also acts as a flag to the server that a fault has occured.
Parameters:
string $faultcode
string $faultstring
string $faultactor
string $faultdetail public
Definition at line 4489 of file nusoap.php.
References debug_flag, fault(), and nusoap_base::getDebug().
nusoap_server::fault ($ faultcode, $ faultstring, $ faultactor = '', $ faultdetail = '')
Specify a fault to be returned to the client. This also acts as a flag to the server that a fault has occured.
Parameters:
string $faultcode
string $faultstring
string $faultactor
string $faultdetail public
Definition at line 1029 of file class.soap_server.php.
References debug_flag, fault(), and nusoap_base::getDebug().
nusoap_server::fault ($ faultcode, $ faultstring, $ faultactor = '', $ faultdetail = '')
Specify a fault to be returned to the client. This also acts as a flag to the server that a fault has occured.
Parameters:
string $faultcode
string $faultstring
string $faultactor
string $faultdetail public
Definition at line 4487 of file nusoap.php.
References debug_flag, fault(), and nusoap_base::getDebug().
nusoap_server::fault ($ faultcode, $ faultstring, $ faultactor = '', $ faultdetail = '')
Specify a fault to be returned to the client. This also acts as a flag to the server that a fault has occured.
Parameters:
string $faultcode
string $faultstring
string $faultactor
string $faultdetail public
Definition at line 1029 of file class.soap_server.php.
References debug_flag, and nusoap_base::getDebug().
Referenced by fault(), invoke_method(), parse_request(), parseRequest(), send_response(), serialize_return(), and service().
nusoap_server::getHTTPBody ($ soapmsg)
gets the HTTP body for the current response.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4364 of file nusoap.php.
nusoap_server::getHTTPBody ($ soapmsg)
gets the HTTP body for the current response.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 904 of file class.soap_server.php.
nusoap_server::getHTTPBody ($ soapmsg)
gets the HTTP body for the current response.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4362 of file nusoap.php.
nusoap_server::getHTTPBody ($ soapmsg)
gets the HTTP body for the current response.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 904 of file class.soap_server.php.
Referenced by send_response().
nusoap_server::getHTTPContentType ()
gets the HTTP content type for the current response.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4376 of file nusoap.php.
nusoap_server::getHTTPContentType ()
gets the HTTP content type for the current response.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 916 of file class.soap_server.php.
nusoap_server::getHTTPContentType ()
gets the HTTP content type for the current response.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4374 of file nusoap.php.
nusoap_server::getHTTPContentType ()
gets the HTTP content type for the current response.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 916 of file class.soap_server.php.
Referenced by send_response().
nusoap_server::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current response. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4389 of file nusoap.php.
nusoap_server::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current response. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 929 of file class.soap_server.php.
nusoap_server::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current response. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4387 of file nusoap.php.
nusoap_server::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current response. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current response. private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 929 of file class.soap_server.php.
Referenced by send_response().
nusoap_server::invoke_method ()
invokes a PHP function for the requested SOAP method
The following fields are set by this function (when successful)
methodreturn
Note that the PHP function that is called may also set the following fields to affect the response sent to the client
responseHeaders outgoing_headers
This sets the fault field on error
private
Definition at line 3953 of file nusoap.php.
References $param, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::varDump(), and verify_method().
nusoap_server::invoke_method ()
invokes a PHP function for the requested SOAP method
The following fields are set by this function (when successful)
methodreturn
Note that the PHP function that is called may also set the following fields to affect the response sent to the client
responseHeaders outgoing_headers
This sets the fault field on error
private
Definition at line 493 of file class.soap_server.php.
References $param, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::varDump(), and verify_method().
nusoap_server::invoke_method ()
invokes a PHP function for the requested SOAP method
The following fields are set by this function (when successful)
methodreturn
Note that the PHP function that is called may also set the following fields to affect the response sent to the client
responseHeaders outgoing_headers
This sets the fault field on error
private
Definition at line 3951 of file nusoap.php.
References $param, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::varDump(), and verify_method().
nusoap_server::invoke_method ()
invokes a PHP function for the requested SOAP method
The following fields are set by this function (when successful)
methodreturn
Note that the PHP function that is called may also set the following fields to affect the response sent to the client
responseHeaders outgoing_headers
This sets the fault field on error
private
Definition at line 493 of file class.soap_server.php.
References $param, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::varDump(), and verify_method().
Referenced by service().
nusoap_server::nusoap_server ($ wsdl = false)
constructor the optional parameter is a path to a WSDL file that you'd like to bind the server instance to.
Parameters:
mixed $wsdl file path or URL (string), or wsdl instance (object) public
Definition at line 3631 of file nusoap.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_server::nusoap_server ($ wsdl = false)
constructor the optional parameter is a path to a WSDL file that you'd like to bind the server instance to.
Parameters:
mixed $wsdl file path or URL (string), or wsdl instance (object) public
Definition at line 173 of file class.soap_server.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_server::nusoap_server ($ wsdl = false)
constructor the optional parameter is a path to a WSDL file that you'd like to bind the server instance to.
Parameters:
mixed $wsdl file path or URL (string), or wsdl instance (object) public
Definition at line 3631 of file nusoap.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_server::nusoap_server ($ wsdl = false)
constructor the optional parameter is a path to a WSDL file that you'd like to bind the server instance to.
Parameters:
mixed $wsdl file path or URL (string), or wsdl instance (object) public
Definition at line 173 of file class.soap_server.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_server::parse_http_headers ()
parses HTTP request headers.
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction
private
Definition at line 3780 of file nusoap.php.
References $headers, nusoap_base::debug(), and nusoap_base::setError().
nusoap_server::parse_http_headers ()
parses HTTP request headers.
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction
private
Definition at line 320 of file class.soap_server.php.
References $headers, nusoap_base::debug(), and nusoap_base::setError().
nusoap_server::parse_http_headers ()
parses HTTP request headers.
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction
private
Definition at line 3778 of file nusoap.php.
References $headers, nusoap_base::debug(), and nusoap_base::setError().
nusoap_server::parse_http_headers ()
parses HTTP request headers.
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction
private
Definition at line 320 of file class.soap_server.php.
References $headers, nusoap_base::debug(), and nusoap_base::setError().
Referenced by parse_request().
nusoap_server::parse_request ($ data = '')
parses a request
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction request requestSOAP methodURI methodname methodparams requestHeaders document
This sets the fault field on error
Parameters:
string $data XML string private
Definition at line 3906 of file nusoap.php.
References nusoap_base::debug(), fault(), parse_http_headers(), and parseRequest().
nusoap_server::parse_request ($ data = '')
parses a request
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction request requestSOAP methodURI methodname methodparams requestHeaders document
This sets the fault field on error
Parameters:
string $data XML string private
Definition at line 446 of file class.soap_server.php.
References nusoap_base::debug(), fault(), parse_http_headers(), and parseRequest().
nusoap_server::parse_request ($ data = '')
parses a request
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction request requestSOAP methodURI methodname methodparams requestHeaders document
This sets the fault field on error
Parameters:
string $data XML string private
Definition at line 3904 of file nusoap.php.
References nusoap_base::debug(), fault(), parse_http_headers(), and parseRequest().
nusoap_server::parse_request ($ data = '')
parses a request
The following fields are set by this function (when successful)
headers request xml_encoding SOAPAction request requestSOAP methodURI methodname methodparams requestHeaders document
This sets the fault field on error
Parameters:
string $data XML string private
Definition at line 446 of file class.soap_server.php.
References nusoap_base::debug(), fault(), parse_http_headers(), and parseRequest().
Referenced by service().
nusoap_server::parseRequest ($ headers, $ data)
processes SOAP message received from client
Parameters:
array $headers The HTTP headers
string $data unprocessed request data from client
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4308 of file nusoap.php.
References $err, $headers, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_server::parseRequest ($ headers, $ data)
processes SOAP message received from client
Parameters:
array $headers The HTTP headers
string $data unprocessed request data from client
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 848 of file class.soap_server.php.
References $err, $headers, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_server::parseRequest ($ headers, $ data)
processes SOAP message received from client
Parameters:
array $headers The HTTP headers
string $data unprocessed request data from client
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 4306 of file nusoap.php.
References $err, $headers, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_server::parseRequest ($ headers, $ data)
processes SOAP message received from client
Parameters:
array $headers The HTTP headers
string $data unprocessed request data from client
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_server_mime, and nusoap_server_mime.
Definition at line 848 of file class.soap_server.php.
References $err, $headers, nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::setError(), and nusoap_base::varDump().
Referenced by parse_request().
nusoap_server::register ($ name, $ in = array(), $ out = array(), $ namespace = false, $ soapaction = false, $ style = false, $ use = false, $ documentation = '', $ encodingStyle = '')
register a service function with the server
Parameters:
string $name the name of the PHP function, class.method or class..method
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
mixed $namespace the element namespace for the method or false
mixed $soapaction the soapaction for the method or false
mixed $style optional (rpc|document) or false Note: when 'document' is specified, parameter and return wrappers are created for you automatically
mixed $use optional (encoded|literal) or false
string $documentation optional Description to include in WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 4420 of file nusoap.php.
References nusoap_base::setError().
nusoap_server::register ($ name, $ in = array(), $ out = array(), $ namespace = false, $ soapaction = false, $ style = false, $ use = false, $ documentation = '', $ encodingStyle = '')
register a service function with the server
Parameters:
string $name the name of the PHP function, class.method or class..method
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
mixed $namespace the element namespace for the method or false
mixed $soapaction the soapaction for the method or false
mixed $style optional (rpc|document) or false Note: when 'document' is specified, parameter and return wrappers are created for you automatically
mixed $use optional (encoded|literal) or false
string $documentation optional Description to include in WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 960 of file class.soap_server.php.
References nusoap_base::setError().
nusoap_server::register ($ name, $ in = array(), $ out = array(), $ namespace = false, $ soapaction = false, $ style = false, $ use = false, $ documentation = '', $ encodingStyle = '')
register a service function with the server
Parameters:
string $name the name of the PHP function, class.method or class..method
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
mixed $namespace the element namespace for the method or false
mixed $soapaction the soapaction for the method or false
mixed $style optional (rpc|document) or false Note: when 'document' is specified, parameter and return wrappers are created for you automatically
mixed $use optional (encoded|literal) or false
string $documentation optional Description to include in WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 4418 of file nusoap.php.
References nusoap_base::setError().
nusoap_server::register ($ name, $ in = array(), $ out = array(), $ namespace = false, $ soapaction = false, $ style = false, $ use = false, $ documentation = '', $ encodingStyle = '')
register a service function with the server
Parameters:
string $name the name of the PHP function, class.method or class..method
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
mixed $namespace the element namespace for the method or false
mixed $soapaction the soapaction for the method or false
mixed $style optional (rpc|document) or false Note: when 'document' is specified, parameter and return wrappers are created for you automatically
mixed $use optional (encoded|literal) or false
string $documentation optional Description to include in WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 960 of file class.soap_server.php.
References nusoap_base::setError().
nusoap_server::send_response ()
sends an HTTP response
The following fields are set by this function (when successful)
outgoing_headers response
private
Definition at line 4210 of file nusoap.php.
References nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), getHTTPBody(), getHTTPContentType(), and getHTTPContentTypeCharset().
nusoap_server::send_response ()
sends an HTTP response
The following fields are set by this function (when successful)
outgoing_headers response
private
Definition at line 750 of file class.soap_server.php.
References nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), getHTTPBody(), getHTTPContentType(), and getHTTPContentTypeCharset().
nusoap_server::send_response ()
sends an HTTP response
The following fields are set by this function (when successful)
outgoing_headers response
private
Definition at line 4208 of file nusoap.php.
References nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), getHTTPBody(), getHTTPContentType(), and getHTTPContentTypeCharset().
nusoap_server::send_response ()
sends an HTTP response
The following fields are set by this function (when successful)
outgoing_headers response
private
Definition at line 750 of file class.soap_server.php.
References nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), getHTTPBody(), getHTTPContentType(), and getHTTPContentTypeCharset().
Referenced by service().
nusoap_server::serialize_return ()
serializes the return value from a PHP function into a full SOAP Envelope
The following fields are set by this function (when successful)
responseSOAP
This sets the fault field on error
private
Definition at line 4110 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), and nusoap_base::varDump().
nusoap_server::serialize_return ()
serializes the return value from a PHP function into a full SOAP Envelope
The following fields are set by this function (when successful)
responseSOAP
This sets the fault field on error
private
Definition at line 650 of file class.soap_server.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), and nusoap_base::varDump().
nusoap_server::serialize_return ()
serializes the return value from a PHP function into a full SOAP Envelope
The following fields are set by this function (when successful)
responseSOAP
This sets the fault field on error
private
Definition at line 4108 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), and nusoap_base::varDump().
nusoap_server::serialize_return ()
serializes the return value from a PHP function into a full SOAP Envelope
The following fields are set by this function (when successful)
responseSOAP
This sets the fault field on error
private
Definition at line 650 of file class.soap_server.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), fault(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), and nusoap_base::varDump().
Referenced by service().
nusoap_server::service ($ data)
processes request and returns response
Parameters:
string $data usually is the value of $HTTP_RAW_POST_DATA public
Definition at line 3694 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), invoke_method(), parse_request(), send_response(), serialize_return(), and nusoap_base::varDump().
nusoap_server::service ($ data)
processes request and returns response
Parameters:
string $data usually is the value of $HTTP_RAW_POST_DATA public
Definition at line 236 of file class.soap_server.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), invoke_method(), parse_request(), send_response(), serialize_return(), and nusoap_base::varDump().
nusoap_server::service ($ data)
processes request and returns response
Parameters:
string $data usually is the value of $HTTP_RAW_POST_DATA public
Definition at line 3694 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), invoke_method(), parse_request(), send_response(), serialize_return(), and nusoap_base::varDump().
nusoap_server::service ($ data)
processes request and returns response
Parameters:
string $data usually is the value of $HTTP_RAW_POST_DATA public
Definition at line 236 of file class.soap_server.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), debug_flag, fault(), nusoap_base::getDebugAsXMLComment(), invoke_method(), parse_request(), send_response(), serialize_return(), and nusoap_base::varDump().
nusoap_server::verify_method ($ operation, $ request)
takes the value that was created by parsing the request and compares to the method's signature, if available.
Parameters:
string $operation The operation to be invoked
array $request The array of parameter values
Returns:
boolean Whether the operation was found private
Definition at line 4289 of file nusoap.php.
nusoap_server::verify_method ($ operation, $ request)
takes the value that was created by parsing the request and compares to the method's signature, if available.
Parameters:
string $operation The operation to be invoked
array $request The array of parameter values
Returns:
boolean Whether the operation was found private
Definition at line 829 of file class.soap_server.php.
nusoap_server::verify_method ($ operation, $ request)
takes the value that was created by parsing the request and compares to the method's signature, if available.
Parameters:
string $operation The operation to be invoked
array $request The array of parameter values
Returns:
boolean Whether the operation was found private
Definition at line 4287 of file nusoap.php.
nusoap_server::verify_method ($ operation, $ request)
takes the value that was created by parsing the request and compares to the method's signature, if available.
Parameters:
string $operation The operation to be invoked
array $request The array of parameter values
Returns:
boolean Whether the operation was found private
Definition at line 829 of file class.soap_server.php.
Referenced by invoke_method().
Member Data Documentation
nusoap_server::$debug_flag = false
Definition at line 163 of file class.soap_server.php.
nusoap_server::$decode_utf8 = true
Definition at line 88 of file class.soap_server.php.
nusoap_server::$document = ''
Definition at line 46 of file class.soap_server.php.
nusoap_server::$externalWSDLURL = false
Definition at line 157 of file class.soap_server.php.
nusoap_server::$fault = false
Definition at line 131 of file class.soap_server.php.
nusoap_server::$headers = array()
Definition at line 22 of file class.soap_server.php.
Referenced by parse_http_headers(), nusoap_server_mime::parseRequest(), and parseRequest().
nusoap_server::$methodname = ''
Definition at line 64 of file class.soap_server.php.
Referenced by add_to_map().
nusoap_server::$methodparams = array()
Definition at line 70 of file class.soap_server.php.
nusoap_server::$methodreturn = false
Definition at line 119 of file class.soap_server.php.
nusoap_server::$methodreturnisliteralxml = false
Definition at line 125 of file class.soap_server.php.
nusoap_server::$methodURI = ''
Definition at line 58 of file class.soap_server.php.
nusoap_server::$operations = array()
Definition at line 145 of file class.soap_server.php.
nusoap_server::$outgoing_headers = array()
Definition at line 95 of file class.soap_server.php.
nusoap_server::$request = ''
Definition at line 28 of file class.soap_server.php.
nusoap_server::$requestHeader = NULL
Definition at line 40 of file class.soap_server.php.
nusoap_server::$requestHeaders = ''
Definition at line 34 of file class.soap_server.php.
nusoap_server::$requestSOAP = ''
Definition at line 52 of file class.soap_server.php.
nusoap_server::$response = ''
Definition at line 101 of file class.soap_server.php.
nusoap_server::$responseHeaders = ''
Definition at line 107 of file class.soap_server.php.
nusoap_server::$responseSOAP = ''
Definition at line 113 of file class.soap_server.php.
nusoap_server::$result = 'successful'
Definition at line 137 of file class.soap_server.php.
nusoap_server::$SOAPAction = ''
Definition at line 76 of file class.soap_server.php.
nusoap_server::$wsdl = false
Definition at line 151 of file class.soap_server.php.
Referenced by nusoap_server().
nusoap_server::$xml_encoding = ''
Definition at line 82 of file class.soap_server.php.
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.soap_server.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.soap_server.php
modules/soap_server/nusoap/lib/nusoap.php