DAEDrupalInterface: nusoap_base Class Reference
nusoap_base Class Reference
Public Member Functions
nusoap_base ()
getGlobalDebugLevel ()
setGlobalDebugLevel ($level)
getDebugLevel ()
setDebugLevel ($level)
debug ($string)
appendDebug ($string)
clearDebug ()
& getDebug ()
& getDebugAsXMLComment ()
expandEntities ($val)
getError ()
setError ($str)
isArraySimpleOrStruct ($val)
serialize_val ($val, $name=false, $type=false, $name_ns=false, $type_ns=false, $attributes=false, $use='encoded', $soapval=false)
serializeEnvelope ($body, $headers=false, $namespaces=array(), $style='rpc', $use='encoded', $encodingStyle='http://schemas.xmlsoap.org/soap/encoding/')
formatDump ($str)
contractQname ($qname)
expandQname ($qname)
getLocalPart ($str)
getPrefix ($str)
getNamespaceFromPrefix ($prefix)
getPrefixFromNamespace ($ns)
getmicrotime ()
varDump ($data)
__toString ()
nusoap_base ()
getGlobalDebugLevel ()
setGlobalDebugLevel ($level)
getDebugLevel ()
setDebugLevel ($level)
debug ($string)
appendDebug ($string)
clearDebug ()
& getDebug ()
& getDebugAsXMLComment ()
expandEntities ($val)
getError ()
setError ($str)
isArraySimpleOrStruct ($val)
serialize_val ($val, $name=false, $type=false, $name_ns=false, $type_ns=false, $attributes=false, $use='encoded', $soapval=false)
serializeEnvelope ($body, $headers=false, $namespaces=array(), $style='rpc', $use='encoded', $encodingStyle='http://schemas.xmlsoap.org/soap/encoding/')
formatDump ($str)
contractQname ($qname)
expandQname ($qname)
getLocalPart ($str)
getPrefix ($str)
getNamespaceFromPrefix ($prefix)
getPrefixFromNamespace ($ns)
getmicrotime ()
varDump ($data)
__toString ()
nusoap_base ()
getGlobalDebugLevel ()
setGlobalDebugLevel ($level)
getDebugLevel ()
setDebugLevel ($level)
debug ($string)
appendDebug ($string)
clearDebug ()
& getDebug ()
& getDebugAsXMLComment ()
expandEntities ($val)
getError ()
setError ($str)
isArraySimpleOrStruct ($val)
serialize_val ($val, $name=false, $type=false, $name_ns=false, $type_ns=false, $attributes=false, $use='encoded', $soapval=false)
serializeEnvelope ($body, $headers=false, $namespaces=array(), $style='rpc', $use='encoded', $encodingStyle='http://schemas.xmlsoap.org/soap/encoding/')
formatDump ($str)
contractQname ($qname)
expandQname ($qname)
getLocalPart ($str)
getPrefix ($str)
getNamespaceFromPrefix ($prefix)
getPrefixFromNamespace ($ns)
getmicrotime ()
varDump ($data)
__toString ()
nusoap_base ()
getGlobalDebugLevel ()
setGlobalDebugLevel ($level)
getDebugLevel ()
setDebugLevel ($level)
debug ($string)
appendDebug ($string)
clearDebug ()
& getDebug ()
& getDebugAsXMLComment ()
expandEntities ($val)
getError ()
setError ($str)
isArraySimpleOrStruct ($val)
serialize_val ($val, $name=false, $type=false, $name_ns=false, $type_ns=false, $attributes=false, $use='encoded', $soapval=false)
serializeEnvelope ($body, $headers=false, $namespaces=array(), $style='rpc', $use='encoded', $encodingStyle='http://schemas.xmlsoap.org/soap/encoding/')
formatDump ($str)
contractQname ($qname)
expandQname ($qname)
getLocalPart ($str)
getPrefix ($str)
getNamespaceFromPrefix ($prefix)
getPrefixFromNamespace ($ns)
getmicrotime ()
varDump ($data)
__toString ()
Public Attributes
$title = 'NuSOAP'
$version = '0.9.5'
$revision = '$Revision: 1.56 $'
$error_str = ''
$debug_str = ''
$charencoding = true
$debugLevel
$XMLSchemaVersion = 'http://www.w3.org/2001/XMLSchema'
$soap_defencoding = 'ISO-8859-1'
$namespaces
$usedNamespaces = array()
$typemap
$xmlEntities
Detailed Description
nusoap_base
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
class.nusoap_base.php,v 1.56 2010/04/26 20:15:08 snichol Exp
public
nusoap_base
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 85 of file class.nusoap_base.php.
Member Function Documentation
nusoap_base::__toString ()
represents the object as a string
Returns:
string public
Definition at line 887 of file nusoap.php.
References varDump().
nusoap_base::__toString ()
represents the object as a string
Returns:
string public
Definition at line 887 of file class.nusoap_base.php.
References varDump().
nusoap_base::__toString ()
represents the object as a string
Returns:
string public
Definition at line 887 of file nusoap.php.
References varDump().
nusoap_base::__toString ()
represents the object as a string
Returns:
string public
Definition at line 887 of file class.nusoap_base.php.
References varDump().
nusoap_base::appendDebug ($ string)
adds debug data to the instance debug string without formatting
Parameters:
string $string debug data public
Definition at line 287 of file nusoap.php.
nusoap_base::appendDebug ($ string)
adds debug data to the instance debug string without formatting
Parameters:
string $string debug data public
Definition at line 287 of file class.nusoap_base.php.
nusoap_base::appendDebug ($ string)
adds debug data to the instance debug string without formatting
Parameters:
string $string debug data public
Definition at line 287 of file nusoap.php.
nusoap_base::appendDebug ($ string)
adds debug data to the instance debug string without formatting
Parameters:
string $string debug data public
Definition at line 287 of file class.nusoap_base.php.
Referenced by nusoap_client::_getProxyClassCode(), nusoap_xmlschema::addComplexType(), nusoap_xmlschema::addElement(), nusoap_xmlschema::addSimpleType(), nusoap_parser::buildVal(), nusoap_client::call(), nusoap_client::checkWSDL(), soap_transport_http::connect(), debug(), wsdl::end_element(), wsdl::getTypeDef(), nusoap_server::invoke_method(), nusoap_client::nusoap_client(), nusoap_parser::nusoap_parser(), nusoap_server::nusoap_server(), wsdl::parametersMatchWrapped(), nusoap_server::parseRequest(), nusoap_client::parseResponse(), wsdl::parseWSDL(), nusoap_xmlschema::schemaStartElement(), nusoap_client::send(), nusoap_server::serialize_return(), serialize_val(), serializeEnvelope(), wsdl::serializeParameters(), wsdl::serializeRPCParameters(), wsdl::serializeType(), nusoap_server::service(), wsdl::setCredentials(), nusoap_client::setCredentials(), soap_transport_http::setCredentials(), nusoap_client::setCurlOption(), soap_transport_http::setCurlOption(), nusoap_client::setHeaders(), soap_transport_http::soap_transport_http(), and wsdl::start_element().
nusoap_base::clearDebug ()
clears the current debug data for this instance
public
Definition at line 300 of file nusoap.php.
nusoap_base::clearDebug ()
clears the current debug data for this instance
public
Definition at line 300 of file class.nusoap_base.php.
nusoap_base::clearDebug ()
clears the current debug data for this instance
public
Definition at line 300 of file nusoap.php.
nusoap_base::clearDebug ()
clears the current debug data for this instance
public
Definition at line 300 of file class.nusoap_base.php.
nusoap_base::contractQname ($ qname)
contracts (changes namespace to prefix) a qualified name
Parameters:
string $qname qname
Returns:
string contracted qname private
Definition at line 740 of file nusoap.php.
References getPrefixFromNamespace().
nusoap_base::contractQname ($ qname)
contracts (changes namespace to prefix) a qualified name
Parameters:
string $qname qname
Returns:
string contracted qname private
Definition at line 740 of file class.nusoap_base.php.
References getPrefixFromNamespace().
nusoap_base::contractQname ($ qname)
contracts (changes namespace to prefix) a qualified name
Parameters:
string $qname qname
Returns:
string contracted qname private
Definition at line 740 of file nusoap.php.
References getPrefixFromNamespace().
nusoap_base::contractQname ($ qname)
contracts (changes namespace to prefix) a qualified name
Parameters:
string $qname qname
Returns:
string contracted qname private
Definition at line 740 of file class.nusoap_base.php.
References getPrefixFromNamespace().
nusoap_base::debug ($ string)
adds debug data to the instance debug string with formatting
Parameters:
string $string debug data private
Definition at line 275 of file nusoap.php.
References appendDebug(), and getmicrotime().
nusoap_base::debug ($ string)
adds debug data to the instance debug string with formatting
Parameters:
string $string debug data private
Definition at line 275 of file class.nusoap_base.php.
References appendDebug(), and getmicrotime().
nusoap_base::debug ($ string)
adds debug data to the instance debug string with formatting
Parameters:
string $string debug data private
Definition at line 275 of file nusoap.php.
References appendDebug(), and getmicrotime().
nusoap_base::debug ($ string)
adds debug data to the instance debug string with formatting
Parameters:
string $string debug data private
Definition at line 275 of file class.nusoap_base.php.
References appendDebug(), and getmicrotime().
Referenced by nusoap_client::_getProxyClassCode(), soap_transport_http::buildPayload(), nusoap_parser::buildVal(), nusoap_client::call(), nusoap_client::checkCookies(), nusoap_client::checkWSDL(), soap_transport_http::connect(), soap_transport_http::decodeChunked(), nusoap_parser::decodeSimple(), wsdl::end_element(), wsdl::fetchWSDL(), soap_transport_http::getCookiesForRequest(), nusoap_server_mime::getHTTPBody(), nusoap_client_mime::getHTTPBody(), nusoap_client::getOperationData(), wsdl::getOperations(), nusoap_client::getProxy(), soap_transport_http::getResponse(), wsdl::getTypeDef(), nusoap_server::invoke_method(), nusoap_client::loadWSDL(), nusoap_client::nusoap_client(), nusoap_parser::nusoap_parser(), nusoap_server::nusoap_server(), nusoap_xmlschema::nusoap_xmlschema(), wsdl::parametersMatchWrapped(), nusoap_server::parse_http_headers(), nusoap_server::parse_request(), nusoap_xmlschema::parseFile(), nusoap_server_mime::parseRequest(), nusoap_server::parseRequest(), nusoap_client_mime::parseResponse(), nusoap_client::parseResponse(), nusoap_xmlschema::parseString(), wsdl::parseWSDL(), nusoap_client::send(), soap_transport_http::send(), nusoap_server::send_response(), soap_transport_http::sendRequest(), nusoap_server::serialize_return(), serialize_val(), wsdl::serializeComplexTypeAttributes(), wsdl::serializeComplexTypeElements(), serializeEnvelope(), wsdl::serializeParameters(), wsdl::serializeRPCParameters(), wsdl::serializeType(), nusoap_server::service(), wsdl::setCredentials(), nusoap_client::setCredentials(), soap_transport_http::setCredentials(), nusoap_client::setCurlOption(), soap_transport_http::setCurlOption(), nusoap_client::setEndpoint(), soap_transport_http::setHeader(), nusoap_client::setHeaders(), nusoap_client::setHTTPEncoding(), soap_transport_http::setProxy(), soap_transport_http::setURL(), nusoap_client::setUseCURL(), soap_transport_http::soap_transport_http(), wsdl::start_element(), nusoap_parser::start_element(), soap_transport_http::unsetHeader(), nusoap_client::UpdateCookies(), nusoap_client::useHTTPPersistentConnection(), wsdl::wsdl(), and nusoap_xmlschema::xdebug().
nusoap_base::expandEntities ($ val)
expands entities, e.g. changes '<' to '<'.
Parameters:
string $val The string in which to expand entities. private
Definition at line 341 of file nusoap.php.
nusoap_base::expandEntities ($ val)
expands entities, e.g. changes '<' to '<'.
Parameters:
string $val The string in which to expand entities. private
Definition at line 341 of file class.nusoap_base.php.
nusoap_base::expandEntities ($ val)
expands entities, e.g. changes '<' to '<'.
Parameters:
string $val The string in which to expand entities. private
Definition at line 341 of file nusoap.php.
nusoap_base::expandEntities ($ val)
expands entities, e.g. changes '<' to '<'.
Parameters:
string $val The string in which to expand entities. private
Definition at line 341 of file class.nusoap_base.php.
Referenced by serialize_val(), wsdl::serializeComplexTypeAttributes(), and wsdl::serializeType().
nusoap_base::expandQname ($ qname)
expands (changes prefix to namespace) a qualified name
Parameters:
string $qname qname
Returns:
string expanded qname private
Definition at line 765 of file nusoap.php.
nusoap_base::expandQname ($ qname)
expands (changes prefix to namespace) a qualified name
Parameters:
string $qname qname
Returns:
string expanded qname private
Definition at line 765 of file class.nusoap_base.php.
nusoap_base::expandQname ($ qname)
expands (changes prefix to namespace) a qualified name
Parameters:
string $qname qname
Returns:
string expanded qname private
Definition at line 765 of file nusoap.php.
nusoap_base::expandQname ($ qname)
expands (changes prefix to namespace) a qualified name
Parameters:
string $qname qname
Returns:
string expanded qname private
Definition at line 765 of file class.nusoap_base.php.
Referenced by wsdl::addComplexType(), wsdl::addSimpleType(), nusoap_xmlschema::schemaStartElement(), and wsdl::start_element().
nusoap_base::formatDump ($ str)
formats a string to be inserted into an HTML stream
Parameters:
string $str The string to format
Returns:
string The formatted string public
Deprecated:
Definition at line 728 of file nusoap.php.
nusoap_base::formatDump ($ str)
formats a string to be inserted into an HTML stream
Parameters:
string $str The string to format
Returns:
string The formatted string public
Deprecated:
Definition at line 728 of file class.nusoap_base.php.
nusoap_base::formatDump ($ str)
formats a string to be inserted into an HTML stream
Parameters:
string $str The string to format
Returns:
string The formatted string public
Deprecated:
Definition at line 728 of file nusoap.php.
nusoap_base::formatDump ($ str)
formats a string to be inserted into an HTML stream
Parameters:
string $str The string to format
Returns:
string The formatted string public
Deprecated:
Definition at line 728 of file class.nusoap_base.php.
& nusoap_base::getDebug ()
gets the current debug data for this instance
Returns:
debug data public
Definition at line 312 of file nusoap.php.
& nusoap_base::getDebug ()
gets the current debug data for this instance
Returns:
debug data public
Definition at line 312 of file class.nusoap_base.php.
& nusoap_base::getDebug ()
gets the current debug data for this instance
Returns:
debug data public
Definition at line 312 of file nusoap.php.
& nusoap_base::getDebug ()
gets the current debug data for this instance
Returns:
debug data public
Definition at line 312 of file class.nusoap_base.php.
Referenced by nusoap_server::fault().
& nusoap_base::getDebugAsXMLComment ()
gets the current debug data for this instance as an XML comment this may change the contents of the debug data
Returns:
debug data as an XML comment public
Definition at line 325 of file nusoap.php.
& nusoap_base::getDebugAsXMLComment ()
gets the current debug data for this instance as an XML comment this may change the contents of the debug data
Returns:
debug data as an XML comment public
Definition at line 325 of file class.nusoap_base.php.
& nusoap_base::getDebugAsXMLComment ()
gets the current debug data for this instance as an XML comment this may change the contents of the debug data
Returns:
debug data as an XML comment public
Definition at line 325 of file nusoap.php.
& nusoap_base::getDebugAsXMLComment ()
gets the current debug data for this instance as an XML comment this may change the contents of the debug data
Returns:
debug data as an XML comment public
Definition at line 325 of file class.nusoap_base.php.
Referenced by nusoap_server::send_response(), and nusoap_server::service().
nusoap_base::getDebugLevel ()
gets the debug level for this instance
Returns:
int Debug level 0-9, where 0 turns off public
Definition at line 255 of file nusoap.php.
nusoap_base::getDebugLevel ()
gets the debug level for this instance
Returns:
int Debug level 0-9, where 0 turns off public
Definition at line 255 of file class.nusoap_base.php.
nusoap_base::getDebugLevel ()
gets the debug level for this instance
Returns:
int Debug level 0-9, where 0 turns off public
Definition at line 255 of file nusoap.php.
nusoap_base::getDebugLevel ()
gets the debug level for this instance
Returns:
int Debug level 0-9, where 0 turns off public
Definition at line 255 of file class.nusoap_base.php.
nusoap_base::getError ()
returns error string if present
Returns:
mixed error string or false public
Definition at line 358 of file nusoap.php.
nusoap_base::getError ()
returns error string if present
Returns:
mixed error string or false public
Definition at line 358 of file class.nusoap_base.php.
nusoap_base::getError ()
returns error string if present
Returns:
mixed error string or false public
Definition at line 358 of file nusoap.php.
nusoap_base::getError ()
returns error string if present
Returns:
mixed error string or false public
Definition at line 358 of file class.nusoap_base.php.
Referenced by nusoap_client::_getProxyClassCode(), nusoap_client::call(), nusoap_client::getOperationData(), nusoap_client::getProxy(), wsdl::parseWSDL(), and nusoap_client::send().
nusoap_base::getGlobalDebugLevel ()
gets the global debug level, which applies to future instances
Returns:
integer Debug level 0-9, where 0 turns off public
Definition at line 235 of file nusoap.php.
References $GLOBALS.
nusoap_base::getGlobalDebugLevel ()
gets the global debug level, which applies to future instances
Returns:
integer Debug level 0-9, where 0 turns off public
Definition at line 235 of file class.nusoap_base.php.
References $GLOBALS.
nusoap_base::getGlobalDebugLevel ()
gets the global debug level, which applies to future instances
Returns:
integer Debug level 0-9, where 0 turns off public
Definition at line 235 of file nusoap.php.
References $GLOBALS.
nusoap_base::getGlobalDebugLevel ()
gets the global debug level, which applies to future instances
Returns:
integer Debug level 0-9, where 0 turns off public
Definition at line 235 of file class.nusoap_base.php.
References $GLOBALS.
nusoap_base::getLocalPart ($ str)
returns the local part of a prefixed string returns the original string, if not prefixed
Parameters:
string $str The prefixed string
Returns:
string The local part public
Definition at line 790 of file nusoap.php.
nusoap_base::getLocalPart ($ str)
returns the local part of a prefixed string returns the original string, if not prefixed
Parameters:
string $str The prefixed string
Returns:
string The local part public
Definition at line 790 of file class.nusoap_base.php.
nusoap_base::getLocalPart ($ str)
returns the local part of a prefixed string returns the original string, if not prefixed
Parameters:
string $str The prefixed string
Returns:
string The local part public
Definition at line 790 of file nusoap.php.
nusoap_base::getLocalPart ($ str)
returns the local part of a prefixed string returns the original string, if not prefixed
Parameters:
string $str The prefixed string
Returns:
string The local part public
Definition at line 790 of file class.nusoap_base.php.
Referenced by wsdl::addOperation(), nusoap_xmlschema::schemaEndElement(), nusoap_xmlschema::schemaStartElement(), wsdl::serialize(), wsdl::serializeComplexTypeAttributes(), wsdl::serializeComplexTypeElements(), wsdl::serializeType(), wsdl::start_element(), and nusoap_parser::start_element().
nusoap_base::getmicrotime ()
returns the time in ODBC canonical form with microseconds
Returns:
string The time in ODBC canonical form with microseconds public
Definition at line 854 of file nusoap.php.
nusoap_base::getmicrotime ()
returns the time in ODBC canonical form with microseconds
Returns:
string The time in ODBC canonical form with microseconds public
Definition at line 854 of file class.nusoap_base.php.
nusoap_base::getmicrotime ()
returns the time in ODBC canonical form with microseconds
Returns:
string The time in ODBC canonical form with microseconds public
Definition at line 854 of file nusoap.php.
nusoap_base::getmicrotime ()
returns the time in ODBC canonical form with microseconds
Returns:
string The time in ODBC canonical form with microseconds public
Definition at line 854 of file class.nusoap_base.php.
Referenced by debug().
nusoap_base::getNamespaceFromPrefix ($ prefix)
pass it a prefix, it returns a namespace
Parameters:
string $prefix The prefix
Returns:
mixed The namespace, false if no namespace has the specified prefix public
Definition at line 822 of file nusoap.php.
nusoap_base::getNamespaceFromPrefix ($ prefix)
pass it a prefix, it returns a namespace
Parameters:
string $prefix The prefix
Returns:
mixed The namespace, false if no namespace has the specified prefix public
Definition at line 822 of file class.nusoap_base.php.
nusoap_base::getNamespaceFromPrefix ($ prefix)
pass it a prefix, it returns a namespace
Parameters:
string $prefix The prefix
Returns:
mixed The namespace, false if no namespace has the specified prefix public
Definition at line 822 of file nusoap.php.
nusoap_base::getNamespaceFromPrefix ($ prefix)
pass it a prefix, it returns a namespace
Parameters:
string $prefix The prefix
Returns:
mixed The namespace, false if no namespace has the specified prefix public
Definition at line 822 of file class.nusoap_base.php.
Referenced by wsdl::addOperation(), wsdl::parametersMatchWrapped(), nusoap_xmlschema::schemaStartElement(), wsdl::serialize(), wsdl::serializeComplexTypeAttributes(), wsdl::serializeComplexTypeElements(), and wsdl::serializeType().
nusoap_base::getPrefix ($ str)
returns the prefix part of a prefixed string returns false, if not prefixed
Parameters:
string $str The prefixed string
Returns:
mixed The prefix or false if there is no prefix public
Definition at line 807 of file nusoap.php.
nusoap_base::getPrefix ($ str)
returns the prefix part of a prefixed string returns false, if not prefixed
Parameters:
string $str The prefixed string
Returns:
mixed The prefix or false if there is no prefix public
Definition at line 807 of file class.nusoap_base.php.
nusoap_base::getPrefix ($ str)
returns the prefix part of a prefixed string returns false, if not prefixed
Parameters:
string $str The prefixed string
Returns:
mixed The prefix or false if there is no prefix public
Definition at line 807 of file nusoap.php.
nusoap_base::getPrefix ($ str)
returns the prefix part of a prefixed string returns false, if not prefixed
Parameters:
string $str The prefixed string
Returns:
mixed The prefix or false if there is no prefix public
Definition at line 807 of file class.nusoap_base.php.
Referenced by nusoap_xmlschema::addElement(), wsdl::addOperation(), nusoap_xmlschema::schemaEndElement(), nusoap_xmlschema::schemaStartElement(), wsdl::serialize(), wsdl::serializeComplexTypeAttributes(), wsdl::serializeComplexTypeElements(), wsdl::serializeType(), and nusoap_parser::start_element().
nusoap_base::getPrefixFromNamespace ($ ns)
returns the prefix for a given namespace (or prefix) or false if no prefixes registered for the given namespace
Parameters:
string $ns The namespace
Returns:
mixed The prefix, false if the namespace has no prefixes public
Definition at line 838 of file nusoap.php.
nusoap_base::getPrefixFromNamespace ($ ns)
returns the prefix for a given namespace (or prefix) or false if no prefixes registered for the given namespace
Parameters:
string $ns The namespace
Returns:
mixed The prefix, false if the namespace has no prefixes public
Definition at line 838 of file class.nusoap_base.php.
nusoap_base::getPrefixFromNamespace ($ ns)
returns the prefix for a given namespace (or prefix) or false if no prefixes registered for the given namespace
Parameters:
string $ns The namespace
Returns:
mixed The prefix, false if the namespace has no prefixes public
Definition at line 838 of file nusoap.php.
nusoap_base::getPrefixFromNamespace ($ ns)
returns the prefix for a given namespace (or prefix) or false if no prefixes registered for the given namespace
Parameters:
string $ns The namespace
Returns:
mixed The prefix, false if the namespace has no prefixes public
Definition at line 838 of file class.nusoap_base.php.
Referenced by contractQname(), nusoap_xmlschema::schemaStartElement(), wsdl::serialize(), nusoap_xmlschema::serializeSchema(), wsdl::serializeType(), and wsdl::start_element().
nusoap_base::isArraySimpleOrStruct ($ val)
detect if array is a simple array or a struct (associative array)
Parameters:
mixed $val The PHP array
Returns:
string (arraySimple|arrayStruct) private
Definition at line 382 of file nusoap.php.
nusoap_base::isArraySimpleOrStruct ($ val)
detect if array is a simple array or a struct (associative array)
Parameters:
mixed $val The PHP array
Returns:
string (arraySimple|arrayStruct) private
Definition at line 382 of file class.nusoap_base.php.
nusoap_base::isArraySimpleOrStruct ($ val)
detect if array is a simple array or a struct (associative array)
Parameters:
mixed $val The PHP array
Returns:
string (arraySimple|arrayStruct) private
Definition at line 382 of file nusoap.php.
nusoap_base::isArraySimpleOrStruct ($ val)
detect if array is a simple array or a struct (associative array)
Parameters:
mixed $val The PHP array
Returns:
string (arraySimple|arrayStruct) private
Definition at line 382 of file class.nusoap_base.php.
Referenced by serialize_val(), wsdl::serializeComplexTypeElements(), wsdl::serializeParameters(), and wsdl::serializeRPCParameters().
nusoap_base::nusoap_base ()
constructor
public
Definition at line 225 of file nusoap.php.
References $GLOBALS.
nusoap_base::nusoap_base ()
constructor
public
Definition at line 225 of file class.nusoap_base.php.
References $GLOBALS.
nusoap_base::nusoap_base ()
constructor
public
Definition at line 225 of file nusoap.php.
References $GLOBALS.
nusoap_base::nusoap_base ()
constructor
public
Definition at line 225 of file class.nusoap_base.php.
References $GLOBALS.
Referenced by nusoap_client::nusoap_client(), nusoap_fault::nusoap_fault(), nusoap_parser::nusoap_parser(), nusoap_server::nusoap_server(), nusoap_xmlschema::nusoap_xmlschema(), soap_transport_http::soap_transport_http(), soapval::soapval(), and wsdl::wsdl().
nusoap_base::serialize_val ($ val, $ name = false, $ type = false, $ name_ns = false, $ type_ns = false, $ attributes = false, $ use = 'encoded', $ soapval = false)
serializes PHP values in accordance w/ section 5. Type information is not serialized if $use == 'literal'.
Parameters:
mixed $val The value to serialize
string $name The name (local part) of the XML element
string $type The XML schema type (local part) for the element
string $name_ns The namespace for the name of the XML element
string $type_ns The namespace for the type of the element
array $attributes The attributes to serialize as name=>value pairs
string $use The WSDL "use" (encoded|literal)
boolean $soapval Whether this is called from soapval.
Returns:
string The serialized element, possibly with child elements public
Definition at line 407 of file nusoap.php.
References $i, appendDebug(), debug(), expandEntities(), isArraySimpleOrStruct(), serialize_val(), and varDump().
nusoap_base::serialize_val ($ val, $ name = false, $ type = false, $ name_ns = false, $ type_ns = false, $ attributes = false, $ use = 'encoded', $ soapval = false)
serializes PHP values in accordance w/ section 5. Type information is not serialized if $use == 'literal'.
Parameters:
mixed $val The value to serialize
string $name The name (local part) of the XML element
string $type The XML schema type (local part) for the element
string $name_ns The namespace for the name of the XML element
string $type_ns The namespace for the type of the element
array $attributes The attributes to serialize as name=>value pairs
string $use The WSDL "use" (encoded|literal)
boolean $soapval Whether this is called from soapval.
Returns:
string The serialized element, possibly with child elements public
Definition at line 407 of file class.nusoap_base.php.
References $i, appendDebug(), debug(), expandEntities(), isArraySimpleOrStruct(), serialize_val(), and varDump().
nusoap_base::serialize_val ($ val, $ name = false, $ type = false, $ name_ns = false, $ type_ns = false, $ attributes = false, $ use = 'encoded', $ soapval = false)
serializes PHP values in accordance w/ section 5. Type information is not serialized if $use == 'literal'.
Parameters:
mixed $val The value to serialize
string $name The name (local part) of the XML element
string $type The XML schema type (local part) for the element
string $name_ns The namespace for the name of the XML element
string $type_ns The namespace for the type of the element
array $attributes The attributes to serialize as name=>value pairs
string $use The WSDL "use" (encoded|literal)
boolean $soapval Whether this is called from soapval.
Returns:
string The serialized element, possibly with child elements public
Definition at line 407 of file nusoap.php.
References $i, appendDebug(), debug(), expandEntities(), isArraySimpleOrStruct(), serialize_val(), and varDump().
nusoap_base::serialize_val ($ val, $ name = false, $ type = false, $ name_ns = false, $ type_ns = false, $ attributes = false, $ use = 'encoded', $ soapval = false)
serializes PHP values in accordance w/ section 5. Type information is not serialized if $use == 'literal'.
Parameters:
mixed $val The value to serialize
string $name The name (local part) of the XML element
string $type The XML schema type (local part) for the element
string $name_ns The namespace for the name of the XML element
string $type_ns The namespace for the type of the element
array $attributes The attributes to serialize as name=>value pairs
string $use The WSDL "use" (encoded|literal)
boolean $soapval Whether this is called from soapval.
Returns:
string The serialized element, possibly with child elements public
Definition at line 407 of file class.nusoap_base.php.
References $i, appendDebug(), debug(), expandEntities(), isArraySimpleOrStruct(), and varDump().
Referenced by nusoap_client::call(), soapval::serialize(), nusoap_fault::serialize(), nusoap_server::serialize_return(), serialize_val(), wsdl::serializeComplexTypeElements(), serializeEnvelope(), and wsdl::serializeType().
nusoap_base::serializeEnvelope ($ body, $ headers = false, $ namespaces = array(), $ style = 'rpc', $ use = 'encoded', $ encodingStyle = 'http://schemas.xmlsoap.org/soap/encoding/')
serializes a message
Parameters:
string $body the XML of the SOAP body
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
array $namespaces optional the namespaces used in generating the body and headers
string $style optional (rpc|document)
string $use optional (encoded|literal)
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded)
Returns:
string the message public
Definition at line 673 of file nusoap.php.
References $namespaces, appendDebug(), debug(), serialize_val(), and varDump().
nusoap_base::serializeEnvelope ($ body, $ headers = false, $ namespaces = array(), $ style = 'rpc', $ use = 'encoded', $ encodingStyle = 'http://schemas.xmlsoap.org/soap/encoding/')
serializes a message
Parameters:
string $body the XML of the SOAP body
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
array $namespaces optional the namespaces used in generating the body and headers
string $style optional (rpc|document)
string $use optional (encoded|literal)
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded)
Returns:
string the message public
Definition at line 673 of file class.nusoap_base.php.
References $namespaces, appendDebug(), debug(), serialize_val(), and varDump().
nusoap_base::serializeEnvelope ($ body, $ headers = false, $ namespaces = array(), $ style = 'rpc', $ use = 'encoded', $ encodingStyle = 'http://schemas.xmlsoap.org/soap/encoding/')
serializes a message
Parameters:
string $body the XML of the SOAP body
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
array $namespaces optional the namespaces used in generating the body and headers
string $style optional (rpc|document)
string $use optional (encoded|literal)
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded)
Returns:
string the message public
Definition at line 673 of file nusoap.php.
References $namespaces, appendDebug(), debug(), serialize_val(), and varDump().
nusoap_base::serializeEnvelope ($ body, $ headers = false, $ namespaces = array(), $ style = 'rpc', $ use = 'encoded', $ encodingStyle = 'http://schemas.xmlsoap.org/soap/encoding/')
serializes a message
Parameters:
string $body the XML of the SOAP body
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
array $namespaces optional the namespaces used in generating the body and headers
string $style optional (rpc|document)
string $use optional (encoded|literal)
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded)
Returns:
string the message public
Definition at line 673 of file class.nusoap_base.php.
References $namespaces, appendDebug(), debug(), serialize_val(), and varDump().
Referenced by nusoap_client::call(), and nusoap_server::serialize_return().
nusoap_base::setDebugLevel ($ level)
sets the debug level for this instance
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 265 of file nusoap.php.
nusoap_base::setDebugLevel ($ level)
sets the debug level for this instance
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 265 of file class.nusoap_base.php.
nusoap_base::setDebugLevel ($ level)
sets the debug level for this instance
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 265 of file nusoap.php.
nusoap_base::setDebugLevel ($ level)
sets the debug level for this instance
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 265 of file class.nusoap_base.php.
nusoap_base::setError ($ str)
sets error string
Returns:
boolean $string error string private
Definition at line 371 of file nusoap.php.
nusoap_base::setError ($ str)
sets error string
Returns:
boolean $string error string private
Definition at line 371 of file class.nusoap_base.php.
nusoap_base::setError ($ str)
sets error string
Returns:
boolean $string error string private
Definition at line 371 of file nusoap.php.
nusoap_base::setError ($ str)
sets error string
Returns:
boolean $string error string private
Definition at line 371 of file class.nusoap_base.php.
Referenced by nusoap_client::_getProxyClassCode(), nusoap_client::call(), nusoap_client::checkWSDL(), nusoap_server::configureWSDL(), soap_transport_http::connect(), soap_transport_http::getResponse(), nusoap_parser::nusoap_parser(), nusoap_server::parse_http_headers(), nusoap_xmlschema::parseFile(), nusoap_server_mime::parseRequest(), nusoap_server::parseRequest(), nusoap_client_mime::parseResponse(), nusoap_client::parseResponse(), nusoap_xmlschema::parseString(), wsdl::parseWSDL(), nusoap_server::register(), nusoap_client::send(), soap_transport_http::send(), soap_transport_http::sendRequest(), wsdl::serializeParameters(), wsdl::serializeRPCParameters(), wsdl::serializeType(), and wsdl::webDescription().
nusoap_base::setGlobalDebugLevel ($ level)
sets the global debug level, which applies to future instances
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 245 of file nusoap.php.
References $GLOBALS.
nusoap_base::setGlobalDebugLevel ($ level)
sets the global debug level, which applies to future instances
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 245 of file class.nusoap_base.php.
References $GLOBALS.
nusoap_base::setGlobalDebugLevel ($ level)
sets the global debug level, which applies to future instances
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 245 of file nusoap.php.
References $GLOBALS.
nusoap_base::setGlobalDebugLevel ($ level)
sets the global debug level, which applies to future instances
Parameters:
int $level Debug level 0-9, where 0 turns off public
Definition at line 245 of file class.nusoap_base.php.
References $GLOBALS.
nusoap_base::varDump ($ data)
Returns a string with the output of var_dump
Parameters:
mixed $data The variable to var_dump
Returns:
string The output of var_dump public
Definition at line 873 of file nusoap.php.
nusoap_base::varDump ($ data)
Returns a string with the output of var_dump
Parameters:
mixed $data The variable to var_dump
Returns:
string The output of var_dump public
Definition at line 873 of file class.nusoap_base.php.
nusoap_base::varDump ($ data)
Returns a string with the output of var_dump
Parameters:
mixed $data The variable to var_dump
Returns:
string The output of var_dump public
Definition at line 873 of file nusoap.php.
nusoap_base::varDump ($ data)
Returns a string with the output of var_dump
Parameters:
mixed $data The variable to var_dump
Returns:
string The output of var_dump public
Definition at line 873 of file class.nusoap_base.php.
Referenced by __toString(), nusoap_client::_getProxyClassCode(), nusoap_xmlschema::addComplexType(), nusoap_xmlschema::addElement(), nusoap_xmlschema::addSimpleType(), nusoap_parser::buildVal(), nusoap_client::call(), soap_transport_http::connect(), nusoap_xmlschema::getTypeDef(), wsdl::getTypeDef(), nusoap_server::invoke_method(), nusoap_client::nusoap_client(), nusoap_parser::nusoap_parser(), nusoap_server::nusoap_server(), wsdl::parametersMatchWrapped(), nusoap_server::parseRequest(), nusoap_client::parseResponse(), nusoap_xmlschema::schemaEndElement(), nusoap_xmlschema::schemaStartElement(), nusoap_server::serialize_return(), serialize_val(), serializeEnvelope(), wsdl::serializeParameters(), wsdl::serializeRPCParameters(), wsdl::serializeType(), nusoap_server::service(), wsdl::setCredentials(), nusoap_client::setCredentials(), soap_transport_http::setCredentials(), nusoap_client::setCurlOption(), soap_transport_http::setCurlOption(), nusoap_client::setHeaders(), and soap_transport_http::soap_transport_http().
Member Data Documentation
nusoap_base::$charencoding = true
Definition at line 128 of file class.nusoap_base.php.
nusoap_base::$debug_str = ''
Definition at line 120 of file class.nusoap_base.php.
nusoap_base::$debugLevel
Definition at line 135 of file class.nusoap_base.php.
nusoap_base::$error_str = ''
Definition at line 113 of file class.nusoap_base.php.
nusoap_base::$namespaces
Initial value:
 array(
                'SOAP-ENV' => 'http://schemas.xmlsoap.org/soap/envelope/',
                'xsd' => 'http://www.w3.org/2001/XMLSchema',
                'xsi' => 'http://www.w3.org/2001/XMLSchema-instance',
                'SOAP-ENC' => 'http://schemas.xmlsoap.org/soap/encoding/'
                )
Reimplemented in nusoap_parser.
Definition at line 162 of file class.nusoap_base.php.
Referenced by nusoap_xmlschema::nusoap_xmlschema(), and serializeEnvelope().
nusoap_base::$revision = '$Revision: 1.56 $'
Definition at line 106 of file class.nusoap_base.php.
nusoap_base::$soap_defencoding = 'ISO-8859-1'
Definition at line 151 of file class.nusoap_base.php.
nusoap_base::$title = 'NuSOAP'
Definition at line 92 of file class.nusoap_base.php.
nusoap_base::$typemap
Initial value:
 array(
        'http://www.w3.org/2001/XMLSchema' => array(
                'string'=>'string','boolean'=>'boolean','float'=>'double','double'=>'double','decimal'=>'double',
                'duration'=>'','dateTime'=>'string','time'=>'string','date'=>'string','gYearMonth'=>'',
                'gYear'=>'','gMonthDay'=>'','gDay'=>'','gMonth'=>'','hexBinary'=>'string','base64Binary'=>'string',
                'anyType'=>'string','anySimpleType'=>'string',
                'normalizedString'=>'string','token'=>'string','language'=>'','NMTOKEN'=>'','NMTOKENS'=>'','Name'=>'','NCName'=>'','ID'=>'',
                'IDREF'=>'','IDREFS'=>'','ENTITY'=>'','ENTITIES'=>'','integer'=>'integer','nonPositiveInteger'=>'integer',
                'negativeInteger'=>'integer','long'=>'integer','int'=>'integer','short'=>'integer','byte'=>'integer','nonNegativeInteger'=>'integer',
                'unsignedLong'=>'','unsignedInt'=>'','unsignedShort'=>'','unsignedByte'=>'','positiveInteger'=>''),
        'http://www.w3.org/2000/10/XMLSchema' => array(
                'i4'=>'','int'=>'integer','boolean'=>'boolean','string'=>'string','double'=>'double',
                'float'=>'double','dateTime'=>'string',
                'timeInstant'=>'string','base64Binary'=>'string','base64'=>'string','ur-type'=>'array'),
        'http://www.w3.org/1999/XMLSchema' => array(
                'i4'=>'','int'=>'integer','boolean'=>'boolean','string'=>'string','double'=>'double',
                'float'=>'double','dateTime'=>'string',
                'timeInstant'=>'string','base64Binary'=>'string','base64'=>'string','ur-type'=>'array'),
        'http://soapinterop.org/xsd' => array('SOAPStruct'=>'struct'),
        'http://schemas.xmlsoap.org/soap/encoding/' => array('base64'=>'string','array'=>'array','Array'=>'array'),
    'http://xml.apache.org/xml-soap' => array('Map')
        )
Definition at line 184 of file class.nusoap_base.php.
nusoap_base::$usedNamespaces = array()
Definition at line 175 of file class.nusoap_base.php.
Referenced by nusoap_client::call().
nusoap_base::$version = '0.9.5'
Definition at line 99 of file class.nusoap_base.php.
nusoap_base::$xmlEntities
Initial value:
 array('quot' => '"','amp' => '&',
                'lt' => '<','gt' => '>','apos' => "'")
Definition at line 217 of file class.nusoap_base.php.
nusoap_base::$XMLSchemaVersion = 'http://www.w3.org/2001/XMLSchema'
Definition at line 143 of file class.nusoap_base.php.
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.nusoap_base.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.nusoap_base.php
modules/soap_server/nusoap/lib/nusoap.php