DAEDrupalInterface: MyUploadsPage Class Reference
MyUploadsPage Class Reference
Public Member Functions
build_uploads_page ()
getUsageString ($used)
sizeString ($bytes)
getUsage ()
displayMessage ()
getBreadcrumbs ()
getDirs ()
getCurrentDir ()
getFiles ()
getSelectors ()
getOperations ()
getMoveToDirs ()
getBatchForm ()
Public Attributes
$url
The drupal base URL for viewing uploads so that directory views can be linked to.
$loc
The arguments of the page after uploads/view/.
$output
The HTML to be returned to create the page.
$currentDirectory
The subdirectory currently being viewed.
$files
Array of files and folders in the directory currently being viewed ($currentDirectory)
$from
The base filesystem path to the user's home folder.
$moveTo
Options where files and folders may be moved.
$ui
The dae_ui instance which renders folder and file rows.
$row_no
The number row in the list of files and folders.
Detailed Description
MyUploadsPage class. This class is used to put all the pieces of the My Uploads page together.
Definition at line 47 of file home_directory_uploads.inc.
Member Function Documentation
MyUploadsPage::build_uploads_page ()
Gathers all the bits of output to create the uploads page
Definition at line 71 of file home_directory_uploads.inc.
References $output, $uploads, $user, displayMessage(), getBatchForm(), getBreadcrumbs(), getCurrentDir(), getDirs(), getFiles(), getOperations(), getSelectors(), and getUsage().
MyUploadsPage::displayMessage ()
Displays a message above the uploads page if part of the arguments
Definition at line 186 of file home_directory_uploads.inc.
Referenced by build_uploads_page().
MyUploadsPage::getBatchForm ()
Definition at line 413 of file home_directory_uploads.inc.
Referenced by build_uploads_page().
MyUploadsPage::getBreadcrumbs ()
getBreadcrumbs
Definition at line 226 of file home_directory_uploads.inc.
Referenced by build_uploads_page().
MyUploadsPage::getCurrentDir ()
Definition at line 282 of file home_directory_uploads.inc.
Referenced by build_uploads_page().
MyUploadsPage::getDirs ()
getDirectories
Definition at line 255 of file home_directory_uploads.inc.
References $output.
Referenced by build_uploads_page().
MyUploadsPage::getFiles ()
getFiles
Definition at line 306 of file home_directory_uploads.inc.
References $output, home_directory_check_image(), home_directory_get_file_extension(), and sizeString().
Referenced by build_uploads_page().
MyUploadsPage::getMoveToDirs ()
Definition at line 392 of file home_directory_uploads.inc.
Referenced by getOperations().
MyUploadsPage::getOperations ()
Definition at line 376 of file home_directory_uploads.inc.
References $output, and getMoveToDirs().
Referenced by build_uploads_page().
MyUploadsPage::getSelectors ()
Definition at line 371 of file home_directory_uploads.inc.
References $output.
Referenced by build_uploads_page().
MyUploadsPage::getUsage ()
Retrieves user's usage amount from the database
Definition at line 153 of file home_directory_uploads.inc.
References $user, and getUsageString().
Referenced by build_uploads_page().
MyUploadsPage::getUsageString ($ used)
Gets a formmated string expressing the users remaining space
Definition at line 122 of file home_directory_uploads.inc.
References sizeString().
Referenced by getUsage().
MyUploadsPage::sizeString ($ bytes)
Formats a quantity of bytes into the largest possible measure with two decimal places
Definition at line 135 of file home_directory_uploads.inc.
Referenced by getFiles(), and getUsageString().
Member Data Documentation
MyUploadsPage::$currentDirectory
The subdirectory currently being viewed.
Definition at line 56 of file home_directory_uploads.inc.
MyUploadsPage::$files
Array of files and folders in the directory currently being viewed ($currentDirectory)
Definition at line 58 of file home_directory_uploads.inc.
MyUploadsPage::$from
The base filesystem path to the user's home folder.
Definition at line 60 of file home_directory_uploads.inc.
MyUploadsPage::$loc
The arguments of the page after uploads/view/.
Definition at line 52 of file home_directory_uploads.inc.
MyUploadsPage::$moveTo
Options where files and folders may be moved.
Definition at line 62 of file home_directory_uploads.inc.
MyUploadsPage::$output
The HTML to be returned to create the page.
Definition at line 54 of file home_directory_uploads.inc.
Referenced by build_uploads_page(), getDirs(), getFiles(), getOperations(), and getSelectors().
MyUploadsPage::$row_no
The number row in the list of files and folders.
Definition at line 66 of file home_directory_uploads.inc.
MyUploadsPage::$ui
The dae_ui instance which renders folder and file rows.
Definition at line 64 of file home_directory_uploads.inc.
MyUploadsPage::$url
The drupal base URL for viewing uploads so that directory views can be linked to.
Definition at line 50 of file home_directory_uploads.inc.
The documentation for this class was generated from the following file:
modules/home_directory/home_directory_uploads.inc