DAEDrupalInterface: soap_transport_http Class Reference
soap_transport_http Class Reference
Public Member Functions
soap_transport_http ($url, $curl_options=NULL, $use_curl=false)
setCurlOption ($option, $value)
setHeader ($name, $value)
unsetHeader ($name)
setURL ($url)
io_method ()
connect ($connection_timeout=0, $response_timeout=30)
send ($data, $timeout=0, $response_timeout=30, $cookies=NULL)
sendHTTPS ($data, $timeout=0, $response_timeout=30, $cookies)
setCredentials ($username, $password, $authtype= 'basic', $digestRequest=array(), $certRequest=array())
setSOAPAction ($soapaction)
setEncoding ($enc='gzip, deflate')
setProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '', $proxyauthtype= 'basic')
isSkippableCurlHeader (&$data)
decodeChunked ($buffer, $lb)
buildPayload ($data, $cookie_str= '')
sendRequest ($data, $cookies=NULL)
getResponse ()
setContentType ($type, $charset=false)
usePersistentConnection ()
parseCookie ($cookie_str)
getCookiesForRequest ($cookies, $secure=false)
soap_transport_http ($url, $curl_options=NULL, $use_curl=false)
setCurlOption ($option, $value)
setHeader ($name, $value)
unsetHeader ($name)
setURL ($url)
io_method ()
connect ($connection_timeout=0, $response_timeout=30)
send ($data, $timeout=0, $response_timeout=30, $cookies=NULL)
sendHTTPS ($data, $timeout=0, $response_timeout=30, $cookies)
setCredentials ($username, $password, $authtype= 'basic', $digestRequest=array(), $certRequest=array())
setSOAPAction ($soapaction)
setEncoding ($enc='gzip, deflate')
setProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '', $proxyauthtype= 'basic')
isSkippableCurlHeader (&$data)
decodeChunked ($buffer, $lb)
buildPayload ($data, $cookie_str= '')
sendRequest ($data, $cookies=NULL)
getResponse ()
setContentType ($type, $charset=false)
usePersistentConnection ()
parseCookie ($cookie_str)
getCookiesForRequest ($cookies, $secure=false)
soap_transport_http ($url, $curl_options=NULL, $use_curl=false)
setCurlOption ($option, $value)
setHeader ($name, $value)
unsetHeader ($name)
setURL ($url)
io_method ()
connect ($connection_timeout=0, $response_timeout=30)
send ($data, $timeout=0, $response_timeout=30, $cookies=NULL)
sendHTTPS ($data, $timeout=0, $response_timeout=30, $cookies)
setCredentials ($username, $password, $authtype= 'basic', $digestRequest=array(), $certRequest=array())
setSOAPAction ($soapaction)
setEncoding ($enc='gzip, deflate')
setProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '', $proxyauthtype= 'basic')
isSkippableCurlHeader (&$data)
decodeChunked ($buffer, $lb)
buildPayload ($data, $cookie_str= '')
sendRequest ($data, $cookies=NULL)
getResponse ()
setContentType ($type, $charset=false)
usePersistentConnection ()
parseCookie ($cookie_str)
getCookiesForRequest ($cookies, $secure=false)
soap_transport_http ($url, $curl_options=NULL, $use_curl=false)
setCurlOption ($option, $value)
setHeader ($name, $value)
unsetHeader ($name)
setURL ($url)
io_method ()
connect ($connection_timeout=0, $response_timeout=30)
send ($data, $timeout=0, $response_timeout=30, $cookies=NULL)
sendHTTPS ($data, $timeout=0, $response_timeout=30, $cookies)
setCredentials ($username, $password, $authtype= 'basic', $digestRequest=array(), $certRequest=array())
setSOAPAction ($soapaction)
setEncoding ($enc='gzip, deflate')
setProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '', $proxyauthtype= 'basic')
isSkippableCurlHeader (&$data)
decodeChunked ($buffer, $lb)
buildPayload ($data, $cookie_str= '')
sendRequest ($data, $cookies=NULL)
getResponse ()
setContentType ($type, $charset=false)
usePersistentConnection ()
parseCookie ($cookie_str)
getCookiesForRequest ($cookies, $secure=false)
Public Attributes
$url = ''
$uri = ''
$digest_uri = ''
$scheme = ''
$host = ''
$port = ''
$path = ''
$request_method = 'POST'
$protocol_version = '1.0'
$encoding = ''
$outgoing_headers = array()
$incoming_headers = array()
$incoming_cookies = array()
$outgoing_payload = ''
$incoming_payload = ''
$response_status_line
$useSOAPAction = true
$persistentConnection = false
$ch = false
$ch_options = array()
$use_curl = false
$proxy = null
$username = ''
$password = ''
$authtype = ''
$digestRequest = array()
$certRequest = array()
Detailed Description
transport class for sending/receiving data via HTTP and HTTPS NOTE: PHP must be compiled with the CURL extension for HTTPS support
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
class.soap_transport_http.php,v 1.68 2010/04/26 20:15:08 snichol Exp
public
transport class for sending/receiving data via HTTP and HTTPS NOTE: PHP must be compiled with the CURL extension for HTTPS support
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 15 of file class.soap_transport_http.php.
Member Function Documentation
soap_transport_http::buildPayload ($ data, $ cookie_str = '')
Writes the payload, including HTTP headers, to $this->outgoing_payload.
Parameters:
string $data HTTP body
string $cookie_str data for HTTP Cookie header
Returns:
void private
Definition at line 2842 of file nusoap.php.
References $uri, nusoap_base::debug(), and setHeader().
soap_transport_http::buildPayload ($ data, $ cookie_str = '')
Writes the payload, including HTTP headers, to $this->outgoing_payload.
Parameters:
string $data HTTP body
string $cookie_str data for HTTP Cookie header
Returns:
void private
Definition at line 688 of file class.soap_transport_http.php.
References $uri, nusoap_base::debug(), and setHeader().
soap_transport_http::buildPayload ($ data, $ cookie_str = '')
Writes the payload, including HTTP headers, to $this->outgoing_payload.
Parameters:
string $data HTTP body
string $cookie_str data for HTTP Cookie header
Returns:
void private
Definition at line 2842 of file nusoap.php.
References $uri, nusoap_base::debug(), and setHeader().
soap_transport_http::buildPayload ($ data, $ cookie_str = '')
Writes the payload, including HTTP headers, to $this->outgoing_payload.
Parameters:
string $data HTTP body
string $cookie_str data for HTTP Cookie header
Returns:
void private
Definition at line 688 of file class.soap_transport_http.php.
References $uri, nusoap_base::debug(), and setHeader().
Referenced by sendRequest().
soap_transport_http::connect ($ connection_timeout = 0, $ response_timeout = 30)
establish an HTTP connection
Parameters:
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
boolean true if connected, false if not private
Definition at line 2331 of file nusoap.php.
References $host, $port, nusoap_base::appendDebug(), nusoap_base::debug(), io_method(), setCurlOption(), nusoap_base::setError(), setHeader(), and nusoap_base::varDump().
soap_transport_http::connect ($ connection_timeout = 0, $ response_timeout = 30)
establish an HTTP connection
Parameters:
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
boolean true if connected, false if not private
Definition at line 177 of file class.soap_transport_http.php.
References $host, $port, nusoap_base::appendDebug(), nusoap_base::debug(), io_method(), setCurlOption(), nusoap_base::setError(), setHeader(), and nusoap_base::varDump().
soap_transport_http::connect ($ connection_timeout = 0, $ response_timeout = 30)
establish an HTTP connection
Parameters:
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
boolean true if connected, false if not private
Definition at line 2331 of file nusoap.php.
References $host, $port, nusoap_base::appendDebug(), nusoap_base::debug(), io_method(), setCurlOption(), nusoap_base::setError(), setHeader(), and nusoap_base::varDump().
soap_transport_http::connect ($ connection_timeout = 0, $ response_timeout = 30)
establish an HTTP connection
Parameters:
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
boolean true if connected, false if not private
Definition at line 177 of file class.soap_transport_http.php.
References $host, $port, nusoap_base::appendDebug(), nusoap_base::debug(), io_method(), setCurlOption(), nusoap_base::setError(), setHeader(), and nusoap_base::varDump().
Referenced by send().
soap_transport_http::decodeChunked ($ buffer, $ lb)
decode a string that is encoded w/ "chunked' transfer encoding as defined in RFC2068 19.4.6
Parameters:
string $buffer
string $lb
Returns:
string public
Deprecated:
Definition at line 2785 of file nusoap.php.
References nusoap_base::debug().
soap_transport_http::decodeChunked ($ buffer, $ lb)
decode a string that is encoded w/ "chunked' transfer encoding as defined in RFC2068 19.4.6
Parameters:
string $buffer
string $lb
Returns:
string public
Deprecated:
Definition at line 631 of file class.soap_transport_http.php.
References nusoap_base::debug().
soap_transport_http::decodeChunked ($ buffer, $ lb)
decode a string that is encoded w/ "chunked' transfer encoding as defined in RFC2068 19.4.6
Parameters:
string $buffer
string $lb
Returns:
string public
Deprecated:
Definition at line 2785 of file nusoap.php.
References nusoap_base::debug().
soap_transport_http::decodeChunked ($ buffer, $ lb)
decode a string that is encoded w/ "chunked' transfer encoding as defined in RFC2068 19.4.6
Parameters:
string $buffer
string $lb
Returns:
string public
Deprecated:
Definition at line 631 of file class.soap_transport_http.php.
References nusoap_base::debug().
soap_transport_http::getCookiesForRequest ($ cookies, $ secure = false)
sort out cookies for the current request
Parameters:
array $cookies array with all cookies
boolean $secure is the send-content secure or not?
Returns:
string for Cookie-HTTP-Header private
Definition at line 3420 of file nusoap.php.
References $path, and nusoap_base::debug().
soap_transport_http::getCookiesForRequest ($ cookies, $ secure = false)
sort out cookies for the current request
Parameters:
array $cookies array with all cookies
boolean $secure is the send-content secure or not?
Returns:
string for Cookie-HTTP-Header private
Definition at line 1266 of file class.soap_transport_http.php.
References $path, and nusoap_base::debug().
soap_transport_http::getCookiesForRequest ($ cookies, $ secure = false)
sort out cookies for the current request
Parameters:
array $cookies array with all cookies
boolean $secure is the send-content secure or not?
Returns:
string for Cookie-HTTP-Header private
Definition at line 3420 of file nusoap.php.
References $path, and nusoap_base::debug().
soap_transport_http::getCookiesForRequest ($ cookies, $ secure = false)
sort out cookies for the current request
Parameters:
array $cookies array with all cookies
boolean $secure is the send-content secure or not?
Returns:
string for Cookie-HTTP-Header private
Definition at line 1266 of file class.soap_transport_http.php.
References $path, and nusoap_base::debug().
Referenced by sendRequest().
soap_transport_http::getResponse ()
gets the SOAP response via HTTP[S]
Returns:
string the response (also sets member variables like incoming_payload) private
Definition at line 2948 of file nusoap.php.
References $digestRequest, $err, nusoap_base::debug(), io_method(), isSkippableCurlHeader(), parseCookie(), setCredentials(), nusoap_base::setError(), and setURL().
soap_transport_http::getResponse ()
gets the SOAP response via HTTP[S]
Returns:
string the response (also sets member variables like incoming_payload) private
Definition at line 794 of file class.soap_transport_http.php.
References $digestRequest, $err, nusoap_base::debug(), io_method(), isSkippableCurlHeader(), parseCookie(), setCredentials(), nusoap_base::setError(), and setURL().
soap_transport_http::getResponse ()
gets the SOAP response via HTTP[S]
Returns:
string the response (also sets member variables like incoming_payload) private
Definition at line 2948 of file nusoap.php.
References $digestRequest, $err, nusoap_base::debug(), io_method(), isSkippableCurlHeader(), parseCookie(), setCredentials(), nusoap_base::setError(), and setURL().
soap_transport_http::getResponse ()
gets the SOAP response via HTTP[S]
Returns:
string the response (also sets member variables like incoming_payload) private
Definition at line 794 of file class.soap_transport_http.php.
References $digestRequest, $err, nusoap_base::debug(), io_method(), isSkippableCurlHeader(), parseCookie(), setCredentials(), nusoap_base::setError(), and setURL().
Referenced by send().
soap_transport_http::io_method ()
gets the I/O method to use
Returns:
string I/O method to use (socket|curl|unknown) private
Definition at line 2315 of file nusoap.php.
soap_transport_http::io_method ()
gets the I/O method to use
Returns:
string I/O method to use (socket|curl|unknown) private
Definition at line 161 of file class.soap_transport_http.php.
soap_transport_http::io_method ()
gets the I/O method to use
Returns:
string I/O method to use (socket|curl|unknown) private
Definition at line 2315 of file nusoap.php.
soap_transport_http::io_method ()
gets the I/O method to use
Returns:
string I/O method to use (socket|curl|unknown) private
Definition at line 161 of file class.soap_transport_http.php.
Referenced by connect(), getResponse(), and sendRequest().
soap_transport_http::isSkippableCurlHeader (&$ data)
Test if the given string starts with a header that is to be skipped. Skippable headers result from chunked transfer and proxy requests.
Parameters:
string $data The string to check.
Returns:
boolean Whether a skippable header was found. private
Definition at line 2758 of file nusoap.php.
soap_transport_http::isSkippableCurlHeader (&$ data)
Test if the given string starts with a header that is to be skipped. Skippable headers result from chunked transfer and proxy requests.
Parameters:
string $data The string to check.
Returns:
boolean Whether a skippable header was found. private
Definition at line 604 of file class.soap_transport_http.php.
soap_transport_http::isSkippableCurlHeader (&$ data)
Test if the given string starts with a header that is to be skipped. Skippable headers result from chunked transfer and proxy requests.
Parameters:
string $data The string to check.
Returns:
boolean Whether a skippable header was found. private
Definition at line 2758 of file nusoap.php.
soap_transport_http::isSkippableCurlHeader (&$ data)
Test if the given string starts with a header that is to be skipped. Skippable headers result from chunked transfer and proxy requests.
Parameters:
string $data The string to check.
Returns:
boolean Whether a skippable header was found. private
Definition at line 604 of file class.soap_transport_http.php.
Referenced by getResponse().
soap_transport_http::parseCookie ($ cookie_str)
parse an incoming Cookie into it's parts
Parameters:
string $cookie_str content of cookie
Returns:
array with data of that cookie private
Definition at line 3356 of file nusoap.php.
References $path.
soap_transport_http::parseCookie ($ cookie_str)
parse an incoming Cookie into it's parts
Parameters:
string $cookie_str content of cookie
Returns:
array with data of that cookie private
Definition at line 1202 of file class.soap_transport_http.php.
References $path.
soap_transport_http::parseCookie ($ cookie_str)
parse an incoming Cookie into it's parts
Parameters:
string $cookie_str content of cookie
Returns:
array with data of that cookie private
Definition at line 3356 of file nusoap.php.
References $path.
soap_transport_http::parseCookie ($ cookie_str)
parse an incoming Cookie into it's parts
Parameters:
string $cookie_str content of cookie
Returns:
array with data of that cookie private
Definition at line 1202 of file class.soap_transport_http.php.
References $path.
Referenced by getResponse().
soap_transport_http::send ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies = NULL)
sends the SOAP request and gets the SOAP response via HTTP[S]
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Definition at line 2567 of file nusoap.php.
References connect(), nusoap_base::debug(), getResponse(), sendRequest(), and nusoap_base::setError().
soap_transport_http::send ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies = NULL)
sends the SOAP request and gets the SOAP response via HTTP[S]
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Definition at line 413 of file class.soap_transport_http.php.
References connect(), nusoap_base::debug(), getResponse(), sendRequest(), and nusoap_base::setError().
soap_transport_http::send ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies = NULL)
sends the SOAP request and gets the SOAP response via HTTP[S]
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Definition at line 2567 of file nusoap.php.
References connect(), nusoap_base::debug(), getResponse(), sendRequest(), and nusoap_base::setError().
soap_transport_http::send ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies = NULL)
sends the SOAP request and gets the SOAP response via HTTP[S]
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Definition at line 413 of file class.soap_transport_http.php.
References connect(), nusoap_base::debug(), getResponse(), sendRequest(), and nusoap_base::setError().
Referenced by sendHTTPS().
soap_transport_http::sendHTTPS ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies)
sends the SOAP request and gets the SOAP response via HTTPS using CURL
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Deprecated:
Definition at line 2608 of file nusoap.php.
References send().
soap_transport_http::sendHTTPS ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies)
sends the SOAP request and gets the SOAP response via HTTPS using CURL
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Deprecated:
Definition at line 454 of file class.soap_transport_http.php.
References send().
soap_transport_http::sendHTTPS ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies)
sends the SOAP request and gets the SOAP response via HTTPS using CURL
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Deprecated:
Definition at line 2608 of file nusoap.php.
References send().
soap_transport_http::sendHTTPS ($ data, $ timeout = 0, $ response_timeout = 30, $ cookies)
sends the SOAP request and gets the SOAP response via HTTPS using CURL
Parameters:
string $data message data
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
array $cookies cookies to send
Returns:
string data public
Deprecated:
Definition at line 454 of file class.soap_transport_http.php.
References send().
soap_transport_http::sendRequest ($ data, $ cookies = NULL)
sends the SOAP request via HTTP[S]
Parameters:
string $data message data
array $cookies cookies to send
Returns:
boolean true if OK, false if problem private
Definition at line 2891 of file nusoap.php.
References buildPayload(), nusoap_base::debug(), getCookiesForRequest(), io_method(), setCurlOption(), and nusoap_base::setError().
soap_transport_http::sendRequest ($ data, $ cookies = NULL)
sends the SOAP request via HTTP[S]
Parameters:
string $data message data
array $cookies cookies to send
Returns:
boolean true if OK, false if problem private
Definition at line 737 of file class.soap_transport_http.php.
References buildPayload(), nusoap_base::debug(), getCookiesForRequest(), io_method(), setCurlOption(), and nusoap_base::setError().
soap_transport_http::sendRequest ($ data, $ cookies = NULL)
sends the SOAP request via HTTP[S]
Parameters:
string $data message data
array $cookies cookies to send
Returns:
boolean true if OK, false if problem private
Definition at line 2891 of file nusoap.php.
References buildPayload(), nusoap_base::debug(), getCookiesForRequest(), io_method(), setCurlOption(), and nusoap_base::setError().
soap_transport_http::sendRequest ($ data, $ cookies = NULL)
sends the SOAP request via HTTP[S]
Parameters:
string $data message data
array $cookies cookies to send
Returns:
boolean true if OK, false if problem private
Definition at line 737 of file class.soap_transport_http.php.
References buildPayload(), nusoap_base::debug(), getCookiesForRequest(), io_method(), setCurlOption(), and nusoap_base::setError().
Referenced by send().
soap_transport_http::setContentType ($ type, $ charset = false)
sets the content-type for the SOAP message to be sent
Parameters:
string $type the content type, MIME style
mixed $charset character set used for encoding (or false) public
Definition at line 3326 of file nusoap.php.
References setHeader().
soap_transport_http::setContentType ($ type, $ charset = false)
sets the content-type for the SOAP message to be sent
Parameters:
string $type the content type, MIME style
mixed $charset character set used for encoding (or false) public
Definition at line 1172 of file class.soap_transport_http.php.
References setHeader().
soap_transport_http::setContentType ($ type, $ charset = false)
sets the content-type for the SOAP message to be sent
Parameters:
string $type the content type, MIME style
mixed $charset character set used for encoding (or false) public
Definition at line 3326 of file nusoap.php.
References setHeader().
soap_transport_http::setContentType ($ type, $ charset = false)
sets the content-type for the SOAP message to be sent
Parameters:
string $type the content type, MIME style
mixed $charset character set used for encoding (or false) public
Definition at line 1172 of file class.soap_transport_http.php.
References setHeader().
soap_transport_http::setCredentials ($ username, $ password, $ authtype = 'basic', $ digestRequest = array(), $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $digestRequest (keys must be nonce, nc, realm, qop)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 2622 of file nusoap.php.
References $authtype, $certRequest, $digestRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), setHeader(), and nusoap_base::varDump().
soap_transport_http::setCredentials ($ username, $ password, $ authtype = 'basic', $ digestRequest = array(), $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $digestRequest (keys must be nonce, nc, realm, qop)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 468 of file class.soap_transport_http.php.
References $authtype, $certRequest, $digestRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), setHeader(), and nusoap_base::varDump().
soap_transport_http::setCredentials ($ username, $ password, $ authtype = 'basic', $ digestRequest = array(), $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $digestRequest (keys must be nonce, nc, realm, qop)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 2622 of file nusoap.php.
References $authtype, $certRequest, $digestRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), setHeader(), and nusoap_base::varDump().
soap_transport_http::setCredentials ($ username, $ password, $ authtype = 'basic', $ digestRequest = array(), $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $digestRequest (keys must be nonce, nc, realm, qop)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 468 of file class.soap_transport_http.php.
References $authtype, $certRequest, $digestRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), setHeader(), and nusoap_base::varDump().
Referenced by getResponse(), and setURL().
soap_transport_http::setCurlOption ($ option, $ value)
sets a cURL option
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value private
Definition at line 2234 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
soap_transport_http::setCurlOption ($ option, $ value)
sets a cURL option
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value private
Definition at line 80 of file class.soap_transport_http.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
soap_transport_http::setCurlOption ($ option, $ value)
sets a cURL option
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value private
Definition at line 2234 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
soap_transport_http::setCurlOption ($ option, $ value)
sets a cURL option
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value private
Definition at line 80 of file class.soap_transport_http.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
Referenced by connect(), and sendRequest().
soap_transport_http::setEncoding ($ enc = 'gzip, deflate')
use http encoding
Parameters:
string $enc encoding style. supported values: gzip, deflate, or both public
Definition at line 2706 of file nusoap.php.
References setHeader().
soap_transport_http::setEncoding ($ enc = 'gzip, deflate')
use http encoding
Parameters:
string $enc encoding style. supported values: gzip, deflate, or both public
Definition at line 552 of file class.soap_transport_http.php.
References setHeader().
soap_transport_http::setEncoding ($ enc = 'gzip, deflate')
use http encoding
Parameters:
string $enc encoding style. supported values: gzip, deflate, or both public
Definition at line 2706 of file nusoap.php.
References setHeader().
soap_transport_http::setEncoding ($ enc = 'gzip, deflate')
use http encoding
Parameters:
string $enc encoding style. supported values: gzip, deflate, or both public
Definition at line 552 of file class.soap_transport_http.php.
References setHeader().
soap_transport_http::setHeader ($ name, $ value)
sets an HTTP header
Parameters:
string $name The name of the header
string $value The value of the header private
Definition at line 2247 of file nusoap.php.
References nusoap_base::debug().
soap_transport_http::setHeader ($ name, $ value)
sets an HTTP header
Parameters:
string $name The name of the header
string $value The value of the header private
Definition at line 93 of file class.soap_transport_http.php.
References nusoap_base::debug().
soap_transport_http::setHeader ($ name, $ value)
sets an HTTP header
Parameters:
string $name The name of the header
string $value The value of the header private
Definition at line 2247 of file nusoap.php.
References nusoap_base::debug().
soap_transport_http::setHeader ($ name, $ value)
sets an HTTP header
Parameters:
string $name The name of the header
string $value The value of the header private
Definition at line 93 of file class.soap_transport_http.php.
References nusoap_base::debug().
Referenced by buildPayload(), connect(), setContentType(), setCredentials(), setEncoding(), setProxy(), setSOAPAction(), setURL(), soap_transport_http(), and usePersistentConnection().
soap_transport_http::setProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '', $ proxyauthtype = 'basic')
set proxy info here
Parameters:
string $proxyhost use an empty string to remove proxy
string $proxyport
string $proxyusername
string $proxypassword
string $proxyauthtype (basic|ntlm) public
Definition at line 2730 of file nusoap.php.
References $proxy, nusoap_base::debug(), setHeader(), and unsetHeader().
soap_transport_http::setProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '', $ proxyauthtype = 'basic')
set proxy info here
Parameters:
string $proxyhost use an empty string to remove proxy
string $proxyport
string $proxyusername
string $proxypassword
string $proxyauthtype (basic|ntlm) public
Definition at line 576 of file class.soap_transport_http.php.
References $proxy, nusoap_base::debug(), setHeader(), and unsetHeader().
soap_transport_http::setProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '', $ proxyauthtype = 'basic')
set proxy info here
Parameters:
string $proxyhost use an empty string to remove proxy
string $proxyport
string $proxyusername
string $proxypassword
string $proxyauthtype (basic|ntlm) public
Definition at line 2730 of file nusoap.php.
References $proxy, nusoap_base::debug(), setHeader(), and unsetHeader().
soap_transport_http::setProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '', $ proxyauthtype = 'basic')
set proxy info here
Parameters:
string $proxyhost use an empty string to remove proxy
string $proxyport
string $proxyusername
string $proxypassword
string $proxyauthtype (basic|ntlm) public
Definition at line 576 of file class.soap_transport_http.php.
References $proxy, nusoap_base::debug(), setHeader(), and unsetHeader().
soap_transport_http::setSOAPAction ($ soapaction)
set the soapaction value
Parameters:
string $soapaction public
Definition at line 2696 of file nusoap.php.
References setHeader().
soap_transport_http::setSOAPAction ($ soapaction)
set the soapaction value
Parameters:
string $soapaction public
Definition at line 542 of file class.soap_transport_http.php.
References setHeader().
soap_transport_http::setSOAPAction ($ soapaction)
set the soapaction value
Parameters:
string $soapaction public
Definition at line 2696 of file nusoap.php.
References setHeader().
soap_transport_http::setSOAPAction ($ soapaction)
set the soapaction value
Parameters:
string $soapaction public
Definition at line 542 of file class.soap_transport_http.php.
References setHeader().
soap_transport_http::setURL ($ url)
sets the URL to which to connect
Parameters:
string $url The URL to which to connect private
Definition at line 2271 of file nusoap.php.
References $url, nusoap_base::debug(), setCredentials(), and setHeader().
soap_transport_http::setURL ($ url)
sets the URL to which to connect
Parameters:
string $url The URL to which to connect private
Definition at line 117 of file class.soap_transport_http.php.
References $url, nusoap_base::debug(), setCredentials(), and setHeader().
soap_transport_http::setURL ($ url)
sets the URL to which to connect
Parameters:
string $url The URL to which to connect private
Definition at line 2271 of file nusoap.php.
References $url, nusoap_base::debug(), setCredentials(), and setHeader().
soap_transport_http::setURL ($ url)
sets the URL to which to connect
Parameters:
string $url The URL to which to connect private
Definition at line 117 of file class.soap_transport_http.php.
References $url, nusoap_base::debug(), setCredentials(), and setHeader().
Referenced by getResponse(), and soap_transport_http().
soap_transport_http::soap_transport_http ($ url, $ curl_options = NULL, $ use_curl = false)
constructor
Parameters:
string $url The URL to which to connect
array $curl_options User-specified cURL options
boolean $use_curl Whether to try to force cURL use public
Definition at line 2214 of file nusoap.php.
References $url, $use_curl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::nusoap_base(), setHeader(), setURL(), and nusoap_base::varDump().
soap_transport_http::soap_transport_http ($ url, $ curl_options = NULL, $ use_curl = false)
constructor
Parameters:
string $url The URL to which to connect
array $curl_options User-specified cURL options
boolean $use_curl Whether to try to force cURL use public
Definition at line 60 of file class.soap_transport_http.php.
References $url, $use_curl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::nusoap_base(), setHeader(), setURL(), and nusoap_base::varDump().
soap_transport_http::soap_transport_http ($ url, $ curl_options = NULL, $ use_curl = false)
constructor
Parameters:
string $url The URL to which to connect
array $curl_options User-specified cURL options
boolean $use_curl Whether to try to force cURL use public
Definition at line 2214 of file nusoap.php.
References $url, $use_curl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::nusoap_base(), setHeader(), setURL(), and nusoap_base::varDump().
soap_transport_http::soap_transport_http ($ url, $ curl_options = NULL, $ use_curl = false)
constructor
Parameters:
string $url The URL to which to connect
array $curl_options User-specified cURL options
boolean $use_curl Whether to try to force cURL use public
Definition at line 60 of file class.soap_transport_http.php.
References $url, $use_curl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::nusoap_base(), setHeader(), setURL(), and nusoap_base::varDump().
soap_transport_http::unsetHeader ($ name)
unsets an HTTP header
Parameters:
string $name The name of the header private
Definition at line 2258 of file nusoap.php.
References nusoap_base::debug().
soap_transport_http::unsetHeader ($ name)
unsets an HTTP header
Parameters:
string $name The name of the header private
Definition at line 104 of file class.soap_transport_http.php.
References nusoap_base::debug().
soap_transport_http::unsetHeader ($ name)
unsets an HTTP header
Parameters:
string $name The name of the header private
Definition at line 2258 of file nusoap.php.
References nusoap_base::debug().
soap_transport_http::unsetHeader ($ name)
unsets an HTTP header
Parameters:
string $name The name of the header private
Definition at line 104 of file class.soap_transport_http.php.
References nusoap_base::debug().
Referenced by setProxy().
soap_transport_http::usePersistentConnection ()
specifies that an HTTP persistent connection should be used
Returns:
boolean whether the request was honored by this method. public
Definition at line 3336 of file nusoap.php.
References setHeader().
soap_transport_http::usePersistentConnection ()
specifies that an HTTP persistent connection should be used
Returns:
boolean whether the request was honored by this method. public
Definition at line 1182 of file class.soap_transport_http.php.
References setHeader().
soap_transport_http::usePersistentConnection ()
specifies that an HTTP persistent connection should be used
Returns:
boolean whether the request was honored by this method. public
Definition at line 3336 of file nusoap.php.
References setHeader().
soap_transport_http::usePersistentConnection ()
specifies that an HTTP persistent connection should be used
Returns:
boolean whether the request was honored by this method. public
Definition at line 1182 of file class.soap_transport_http.php.
References setHeader().
Member Data Documentation
soap_transport_http::$authtype = ''
Definition at line 41 of file class.soap_transport_http.php.
Referenced by setCredentials().
soap_transport_http::$certRequest = array()
Definition at line 43 of file class.soap_transport_http.php.
Referenced by setCredentials().
soap_transport_http::$ch = false
Definition at line 35 of file class.soap_transport_http.php.
soap_transport_http::$ch_options = array()
Definition at line 36 of file class.soap_transport_http.php.
soap_transport_http::$digest_uri = ''
Definition at line 19 of file class.soap_transport_http.php.
soap_transport_http::$digestRequest = array()
Definition at line 42 of file class.soap_transport_http.php.
Referenced by getResponse(), and setCredentials().
soap_transport_http::$encoding = ''
Definition at line 26 of file class.soap_transport_http.php.
soap_transport_http::$host = ''
Definition at line 21 of file class.soap_transport_http.php.
Referenced by connect().
soap_transport_http::$incoming_cookies = array()
Definition at line 29 of file class.soap_transport_http.php.
soap_transport_http::$incoming_headers = array()
Definition at line 28 of file class.soap_transport_http.php.
soap_transport_http::$incoming_payload = ''
Definition at line 31 of file class.soap_transport_http.php.
soap_transport_http::$outgoing_headers = array()
Definition at line 27 of file class.soap_transport_http.php.
soap_transport_http::$outgoing_payload = ''
Definition at line 30 of file class.soap_transport_http.php.
soap_transport_http::$password = ''
Definition at line 40 of file class.soap_transport_http.php.
Referenced by setCredentials().
soap_transport_http::$path = ''
Definition at line 23 of file class.soap_transport_http.php.
Referenced by getCookiesForRequest(), and parseCookie().
soap_transport_http::$persistentConnection = false
Definition at line 34 of file class.soap_transport_http.php.
soap_transport_http::$port = ''
Definition at line 22 of file class.soap_transport_http.php.
Referenced by connect().
soap_transport_http::$protocol_version = '1.0'
Definition at line 25 of file class.soap_transport_http.php.
soap_transport_http::$proxy = null
Definition at line 38 of file class.soap_transport_http.php.
Referenced by setProxy().
soap_transport_http::$request_method = 'POST'
Definition at line 24 of file class.soap_transport_http.php.
soap_transport_http::$response_status_line
Definition at line 32 of file class.soap_transport_http.php.
soap_transport_http::$scheme = ''
Definition at line 20 of file class.soap_transport_http.php.
soap_transport_http::$uri = ''
Definition at line 18 of file class.soap_transport_http.php.
Referenced by buildPayload().
soap_transport_http::$url = ''
Definition at line 17 of file class.soap_transport_http.php.
Referenced by setURL(), and soap_transport_http().
soap_transport_http::$use_curl = false
Definition at line 37 of file class.soap_transport_http.php.
Referenced by soap_transport_http().
soap_transport_http::$username = ''
Definition at line 39 of file class.soap_transport_http.php.
Referenced by setCredentials().
soap_transport_http::$useSOAPAction = true
Definition at line 33 of file class.soap_transport_http.php.
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.soap_transport_http.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.soap_transport_http.php
modules/soap_server/nusoap/lib/nusoap.php