DAEDrupalInterface: nusoap_parser Class Reference
nusoap_parser Class Reference
Public Member Functions
nusoap_parser ($xml, $encoding='UTF-8', $method='', $decode_utf8=true)
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
get_response ()
get_soapbody ()
get_soapheader ()
getHeaders ()
decodeSimple ($value, $type, $typens)
buildVal ($pos)
nusoap_parser ($xml, $encoding='UTF-8', $method='', $decode_utf8=true)
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
get_response ()
get_soapbody ()
get_soapheader ()
getHeaders ()
decodeSimple ($value, $type, $typens)
buildVal ($pos)
nusoap_parser ($xml, $encoding='UTF-8', $method='', $decode_utf8=true)
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
get_response ()
get_soapbody ()
get_soapheader ()
getHeaders ()
decodeSimple ($value, $type, $typens)
buildVal ($pos)
nusoap_parser ($xml, $encoding='UTF-8', $method='', $decode_utf8=true)
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
get_response ()
get_soapbody ()
get_soapheader ()
getHeaders ()
decodeSimple ($value, $type, $typens)
buildVal ($pos)
Public Attributes
$xml = ''
$xml_encoding = ''
$method = ''
$root_struct = ''
$root_struct_name = ''
$root_struct_namespace = ''
$root_header = ''
$document = ''
$status = ''
$position = 0
$depth = 0
$default_namespace = ''
$namespaces = array()
$message = array()
$parent = ''
$fault = false
$fault_code = ''
$fault_str = ''
$fault_detail = ''
$depth_array = array()
$debug_flag = true
$soapresponse = NULL
$soapheader = NULL
$responseHeaders = ''
$body_position = 0
$ids = array()
$multirefs = array()
$decode_utf8 = true
Detailed Description
nusoap_parser class parses SOAP XML messages into native PHP values
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
class.soap_parser.php,v 1.42 2010/04/26 20:15:08 snichol Exp
public
nusoap_parser class parses SOAP XML messages into native PHP values
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 15 of file class.soap_parser.php.
Member Function Documentation
nusoap_parser::buildVal ($ pos)
builds response structures for compound values (arrays/structs) and scalars
Parameters:
integer $pos position in node tree
Returns:
mixed PHP value private
Definition at line 7048 of file nusoap.php.
References $parent, nusoap_base::appendDebug(), nusoap_base::debug(), decodeSimple(), and nusoap_base::varDump().
nusoap_parser::buildVal ($ pos)
builds response structures for compound values (arrays/structs) and scalars
Parameters:
integer $pos position in node tree
Returns:
mixed PHP value private
Definition at line 528 of file class.soap_parser.php.
References $parent, nusoap_base::appendDebug(), nusoap_base::debug(), decodeSimple(), and nusoap_base::varDump().
nusoap_parser::buildVal ($ pos)
builds response structures for compound values (arrays/structs) and scalars
Parameters:
integer $pos position in node tree
Returns:
mixed PHP value private
Definition at line 7046 of file nusoap.php.
References $parent, nusoap_base::appendDebug(), nusoap_base::debug(), decodeSimple(), and nusoap_base::varDump().
nusoap_parser::buildVal ($ pos)
builds response structures for compound values (arrays/structs) and scalars
Parameters:
integer $pos position in node tree
Returns:
mixed PHP value private
Definition at line 528 of file class.soap_parser.php.
References $parent, nusoap_base::appendDebug(), nusoap_base::debug(), decodeSimple(), and nusoap_base::varDump().
Referenced by end_element(), and nusoap_parser().
nusoap_parser::character_data ($ parser, $ data)
element content handler
Parameters:
resource $parser XML parser object
string $data element content private
Definition at line 6935 of file nusoap.php.
nusoap_parser::character_data ($ parser, $ data)
element content handler
Parameters:
resource $parser XML parser object
string $data element content private
Definition at line 415 of file class.soap_parser.php.
nusoap_parser::character_data ($ parser, $ data)
element content handler
Parameters:
resource $parser XML parser object
string $data element content private
Definition at line 6933 of file nusoap.php.
nusoap_parser::character_data ($ parser, $ data)
element content handler
Parameters:
resource $parser XML parser object
string $data element content private
Definition at line 415 of file class.soap_parser.php.
nusoap_parser::decodeSimple ($ value, $ type, $ typens)
decodes simple types into PHP variables
Parameters:
string $value value to decode
string $type XML type to decode
string $typens XML type namespace to decode
Returns:
mixed PHP value private
Definition at line 7004 of file nusoap.php.
References nusoap_base::debug().
nusoap_parser::decodeSimple ($ value, $ type, $ typens)
decodes simple types into PHP variables
Parameters:
string $value value to decode
string $type XML type to decode
string $typens XML type namespace to decode
Returns:
mixed PHP value private
Definition at line 484 of file class.soap_parser.php.
References nusoap_base::debug().
nusoap_parser::decodeSimple ($ value, $ type, $ typens)
decodes simple types into PHP variables
Parameters:
string $value value to decode
string $type XML type to decode
string $typens XML type namespace to decode
Returns:
mixed PHP value private
Definition at line 7002 of file nusoap.php.
References nusoap_base::debug().
nusoap_parser::decodeSimple ($ value, $ type, $ typens)
decodes simple types into PHP variables
Parameters:
string $value value to decode
string $type XML type to decode
string $typens XML type namespace to decode
Returns:
mixed PHP value private
Definition at line 484 of file class.soap_parser.php.
References nusoap_base::debug().
Referenced by buildVal(), and end_element().
nusoap_parser::end_element ($ parser, $ name)
end-element handler
Parameters:
resource $parser XML parser object
string $name element name private
Definition at line 6829 of file nusoap.php.
References $parent, buildVal(), and decodeSimple().
nusoap_parser::end_element ($ parser, $ name)
end-element handler
Parameters:
resource $parser XML parser object
string $name element name private
Definition at line 309 of file class.soap_parser.php.
References $parent, buildVal(), and decodeSimple().
nusoap_parser::end_element ($ parser, $ name)
end-element handler
Parameters:
resource $parser XML parser object
string $name element name private
Definition at line 6827 of file nusoap.php.
References $parent, buildVal(), and decodeSimple().
nusoap_parser::end_element ($ parser, $ name)
end-element handler
Parameters:
resource $parser XML parser object
string $name element name private
Definition at line 309 of file class.soap_parser.php.
References $parent, buildVal(), and decodeSimple().
nusoap_parser::get_response ()
get the parsed message (SOAP Body)
Returns:
mixed public
Deprecated:
use get_soapbody instead
Definition at line 6961 of file nusoap.php.
nusoap_parser::get_response ()
get the parsed message (SOAP Body)
Returns:
mixed public
Deprecated:
use get_soapbody instead
Definition at line 441 of file class.soap_parser.php.
nusoap_parser::get_response ()
get the parsed message (SOAP Body)
Returns:
mixed public
Deprecated:
use get_soapbody instead
Definition at line 6959 of file nusoap.php.
nusoap_parser::get_response ()
get the parsed message (SOAP Body)
Returns:
mixed public
Deprecated:
use get_soapbody instead
Definition at line 441 of file class.soap_parser.php.
nusoap_parser::get_soapbody ()
get the parsed SOAP Body (NULL if there was none)
Returns:
mixed public
Definition at line 6971 of file nusoap.php.
nusoap_parser::get_soapbody ()
get the parsed SOAP Body (NULL if there was none)
Returns:
mixed public
Definition at line 451 of file class.soap_parser.php.
nusoap_parser::get_soapbody ()
get the parsed SOAP Body (NULL if there was none)
Returns:
mixed public
Definition at line 6969 of file nusoap.php.
nusoap_parser::get_soapbody ()
get the parsed SOAP Body (NULL if there was none)
Returns:
mixed public
Definition at line 451 of file class.soap_parser.php.
nusoap_parser::get_soapheader ()
get the parsed SOAP Header (NULL if there was none)
Returns:
mixed public
Definition at line 6981 of file nusoap.php.
nusoap_parser::get_soapheader ()
get the parsed SOAP Header (NULL if there was none)
Returns:
mixed public
Definition at line 461 of file class.soap_parser.php.
nusoap_parser::get_soapheader ()
get the parsed SOAP Header (NULL if there was none)
Returns:
mixed public
Definition at line 6979 of file nusoap.php.
nusoap_parser::get_soapheader ()
get the parsed SOAP Header (NULL if there was none)
Returns:
mixed public
Definition at line 461 of file class.soap_parser.php.
nusoap_parser::getHeaders ()
get the unparsed SOAP Header
Returns:
string XML or empty if no Header public
Definition at line 6991 of file nusoap.php.
nusoap_parser::getHeaders ()
get the unparsed SOAP Header
Returns:
string XML or empty if no Header public
Definition at line 471 of file class.soap_parser.php.
nusoap_parser::getHeaders ()
get the unparsed SOAP Header
Returns:
string XML or empty if no Header public
Definition at line 6989 of file nusoap.php.
nusoap_parser::getHeaders ()
get the unparsed SOAP Header
Returns:
string XML or empty if no Header public
Definition at line 471 of file class.soap_parser.php.
nusoap_parser::nusoap_parser ($ xml, $ encoding = 'UTF-8', $ method = '', $ decode_utf8 = true)
constructor that actually does the parsing
Parameters:
string $xml SOAP message
string $encoding character encoding scheme of message
string $method method for which XML is parsed (unused?)
string $decode_utf8 whether to decode UTF-8 to ISO-8859-1 public
Definition at line 6580 of file nusoap.php.
References $decode_utf8, $err, $method, $xml, $xml_encoding, nusoap_base::appendDebug(), buildVal(), nusoap_base::debug(), nusoap_base::nusoap_base(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_parser::nusoap_parser ($ xml, $ encoding = 'UTF-8', $ method = '', $ decode_utf8 = true)
constructor that actually does the parsing
Parameters:
string $xml SOAP message
string $encoding character encoding scheme of message
string $method method for which XML is parsed (unused?)
string $decode_utf8 whether to decode UTF-8 to ISO-8859-1 public
Definition at line 60 of file class.soap_parser.php.
References $decode_utf8, $err, $method, $xml, $xml_encoding, nusoap_base::appendDebug(), buildVal(), nusoap_base::debug(), nusoap_base::nusoap_base(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_parser::nusoap_parser ($ xml, $ encoding = 'UTF-8', $ method = '', $ decode_utf8 = true)
constructor that actually does the parsing
Parameters:
string $xml SOAP message
string $encoding character encoding scheme of message
string $method method for which XML is parsed (unused?)
string $decode_utf8 whether to decode UTF-8 to ISO-8859-1 public
Definition at line 6578 of file nusoap.php.
References $decode_utf8, $err, $method, $xml, $xml_encoding, nusoap_base::appendDebug(), buildVal(), nusoap_base::debug(), nusoap_base::nusoap_base(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_parser::nusoap_parser ($ xml, $ encoding = 'UTF-8', $ method = '', $ decode_utf8 = true)
constructor that actually does the parsing
Parameters:
string $xml SOAP message
string $encoding character encoding scheme of message
string $method method for which XML is parsed (unused?)
string $decode_utf8 whether to decode UTF-8 to ISO-8859-1 public
Definition at line 60 of file class.soap_parser.php.
References $decode_utf8, $err, $method, $xml, $xml_encoding, nusoap_base::appendDebug(), buildVal(), nusoap_base::debug(), nusoap_base::nusoap_base(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_parser::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
resource $parser XML parser object
string $name element name
array $attrs associative array of attributes private
Definition at line 6674 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), and nusoap_base::getPrefix().
nusoap_parser::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
resource $parser XML parser object
string $name element name
array $attrs associative array of attributes private
Definition at line 154 of file class.soap_parser.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), and nusoap_base::getPrefix().
nusoap_parser::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
resource $parser XML parser object
string $name element name
array $attrs associative array of attributes private
Definition at line 6672 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), and nusoap_base::getPrefix().
nusoap_parser::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
resource $parser XML parser object
string $name element name
array $attrs associative array of attributes private
Definition at line 154 of file class.soap_parser.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), and nusoap_base::getPrefix().
Member Data Documentation
nusoap_parser::$body_position = 0
Definition at line 42 of file class.soap_parser.php.
nusoap_parser::$debug_flag = true
Definition at line 38 of file class.soap_parser.php.
nusoap_parser::$decode_utf8 = true
Definition at line 49 of file class.soap_parser.php.
Referenced by nusoap_parser().
nusoap_parser::$default_namespace = ''
Definition at line 29 of file class.soap_parser.php.
nusoap_parser::$depth = 0
Definition at line 28 of file class.soap_parser.php.
nusoap_parser::$depth_array = array()
Definition at line 37 of file class.soap_parser.php.
nusoap_parser::$document = ''
Definition at line 24 of file class.soap_parser.php.
nusoap_parser::$fault = false
Definition at line 33 of file class.soap_parser.php.
nusoap_parser::$fault_code = ''
Definition at line 34 of file class.soap_parser.php.
nusoap_parser::$fault_detail = ''
Definition at line 36 of file class.soap_parser.php.
nusoap_parser::$fault_str = ''
Definition at line 35 of file class.soap_parser.php.
nusoap_parser::$ids = array()
Definition at line 45 of file class.soap_parser.php.
nusoap_parser::$message = array()
Definition at line 31 of file class.soap_parser.php.
nusoap_parser::$method = ''
Definition at line 19 of file class.soap_parser.php.
Referenced by nusoap_parser().
nusoap_parser::$multirefs = array()
Definition at line 47 of file class.soap_parser.php.
nusoap_parser::$namespaces = array()
Reimplemented from nusoap_base.
Definition at line 30 of file class.soap_parser.php.
nusoap_parser::$parent = ''
Definition at line 32 of file class.soap_parser.php.
Referenced by buildVal(), and end_element().
nusoap_parser::$position = 0
Definition at line 27 of file class.soap_parser.php.
nusoap_parser::$responseHeaders = ''
Definition at line 41 of file class.soap_parser.php.
nusoap_parser::$root_header = ''
Definition at line 23 of file class.soap_parser.php.
nusoap_parser::$root_struct = ''
Definition at line 20 of file class.soap_parser.php.
nusoap_parser::$root_struct_name = ''
Definition at line 21 of file class.soap_parser.php.
nusoap_parser::$root_struct_namespace = ''
Definition at line 22 of file class.soap_parser.php.
nusoap_parser::$soapheader = NULL
Definition at line 40 of file class.soap_parser.php.
nusoap_parser::$soapresponse = NULL
Definition at line 39 of file class.soap_parser.php.
nusoap_parser::$status = ''
Definition at line 26 of file class.soap_parser.php.
nusoap_parser::$xml = ''
Definition at line 17 of file class.soap_parser.php.
Referenced by nusoap_parser().
nusoap_parser::$xml_encoding = ''
Definition at line 18 of file class.soap_parser.php.
Referenced by nusoap_parser().
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.soap_parser.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.soap_parser.php
modules/soap_server/nusoap/lib/nusoap.php