DAEDrupalInterface: nusoap_client_mime Class Reference
nusoap_client_mime Class Reference
Public Member Functions
addAttachment ($data, $filename= '', $contenttype= 'application/octet-stream', $cid=false)
clearAttachments ()
getAttachments ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
parseResponse ($headers, $data)
addAttachment ($data, $filename= '', $contenttype= 'application/octet-stream', $cid=false)
clearAttachments ()
getAttachments ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
parseResponse ($headers, $data)
Public Attributes
$requestAttachments = array()
$responseAttachments
$mimeContentType
Detailed Description
nusoap_client_mime client supporting MIME attachments defined at http://www.w3.org/TR/SOAP-attachments. It depends on the PEAR Mail_MIME library.
Author:
Scott Nichol <snichol@users.sourceforge.net>
Thanks to Guillaume and Henning Reich for posting great attachment code to the mail list
Version:
Id
nusoapmime.php,v 1.13 2010/04/26 20:15:08 snichol Exp
public
Definition at line 54 of file nusoapmime.php.
Member Function Documentation
nusoap_client_mime::addAttachment ($ data, $ filename = '', $ contenttype = 'application/octet-stream', $ cid = false)
adds a MIME attachment to the current request.
If the $data parameter contains an empty string, this method will read the contents of the file named by the $filename parameter.
If the $cid parameter is false, this method will generate the cid.
Parameters:
string $data The data of the attachment
string $filename The filename of the attachment (default is empty string)
string $contenttype The MIME Content-Type of the attachment (default is application/octet-stream)
string $cid The content-id (cid) of the attachment (default is false)
Returns:
string The content-id (cid) of the attachment public
Definition at line 88 of file nusoapmime.php.
nusoap_client_mime::addAttachment ($ data, $ filename = '', $ contenttype = 'application/octet-stream', $ cid = false)
adds a MIME attachment to the current request.
If the $data parameter contains an empty string, this method will read the contents of the file named by the $filename parameter.
If the $cid parameter is false, this method will generate the cid.
Parameters:
string $data The data of the attachment
string $filename The filename of the attachment (default is empty string)
string $contenttype The MIME Content-Type of the attachment (default is application/octet-stream)
string $cid The content-id (cid) of the attachment (default is false)
Returns:
string The content-id (cid) of the attachment public
Definition at line 88 of file nusoapmime.php.
nusoap_client_mime::clearAttachments ()
clears the MIME attachments for the current request.
public
Definition at line 108 of file nusoapmime.php.
nusoap_client_mime::clearAttachments ()
clears the MIME attachments for the current request.
public
Definition at line 108 of file nusoapmime.php.
nusoap_client_mime::getAttachments ()
gets the MIME attachments from the current response.
Each array element in the return is an associative array with keys data, filename, contenttype, cid. These keys correspond to the parameters for addAttachment.
Returns:
array The attachments. public
Definition at line 122 of file nusoapmime.php.
nusoap_client_mime::getAttachments ()
gets the MIME attachments from the current response.
Each array element in the return is an associative array with keys data, filename, contenttype, cid. These keys correspond to the parameters for addAttachment.
Returns:
array The attachments. public
Definition at line 122 of file nusoapmime.php.
nusoap_client_mime::getHTTPBody ($ soapmsg)
gets the HTTP body for the current request.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented from nusoap_client.
Definition at line 133 of file nusoapmime.php.
References nusoap_base::debug(), and getHTTPBody().
nusoap_client_mime::getHTTPBody ($ soapmsg)
gets the HTTP body for the current request.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented from nusoap_client.
Definition at line 133 of file nusoapmime.php.
References nusoap_base::debug().
Referenced by getHTTPBody().
nusoap_client_mime::getHTTPContentType ()
gets the HTTP content type for the current request.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current request. private
Reimplemented from nusoap_client.
Definition at line 192 of file nusoapmime.php.
References getHTTPContentType().
nusoap_client_mime::getHTTPContentType ()
gets the HTTP content type for the current request.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current request. private
Reimplemented from nusoap_client.
Definition at line 192 of file nusoapmime.php.
Referenced by getHTTPContentType().
nusoap_client_mime::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current request. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current request. private
Reimplemented from nusoap_client.
Definition at line 208 of file nusoapmime.php.
References getHTTPContentTypeCharset().
nusoap_client_mime::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current request. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current request. private
Reimplemented from nusoap_client.
Definition at line 208 of file nusoapmime.php.
Referenced by getHTTPContentTypeCharset().
nusoap_client_mime::parseResponse ($ headers, $ data)
processes SOAP message returned from server
Parameters:
array $headers The HTTP headers
string $data unprocessed response data from server
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented from nusoap_client.
Definition at line 223 of file nusoapmime.php.
References $input, nusoap_base::debug(), parseResponse(), and nusoap_base::setError().
nusoap_client_mime::parseResponse ($ headers, $ data)
processes SOAP message returned from server
Parameters:
array $headers The HTTP headers
string $data unprocessed response data from server
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented from nusoap_client.
Definition at line 223 of file nusoapmime.php.
References $input, nusoap_base::debug(), and nusoap_base::setError().
Referenced by parseResponse().
Member Data Documentation
nusoap_client_mime::$mimeContentType
Definition at line 71 of file nusoapmime.php.
nusoap_client_mime::$requestAttachments = array()
Definition at line 60 of file nusoapmime.php.
nusoap_client_mime::$responseAttachments
Definition at line 66 of file nusoapmime.php.
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/nusoapmime.php
modules/soap_server/nusoap/lib/nusoapmime.php