DAEDrupalInterface: DatasetPage Class Reference
DatasetPage Class Reference
Public Member Functions
__construct ($content)
list_builder_datasets (&$array, &$dataset_names, &$i)
getOutput ()
Detailed Description
Definition at line 578 of file dae_ui.module.
Member Function Documentation
DatasetPage::__construct ($ content)
Definition at line 580 of file dae_ui.module.
References list_builder_datasets().
DatasetPage::getOutput ()
Definition at line 643 of file dae_ui.module.
DatasetPage::list_builder_datasets (&$ array, &$ dataset_names, &$ i)
Definition at line 605 of file dae_ui.module.
References getDAEDatabase(), and parse_tree().
Referenced by __construct().
The documentation for this class was generated from the following file:
modules/dae_ui/dae_ui.module