DAEDrupalInterface: nusoap_fault Class Reference
nusoap_fault Class Reference
Public Member Functions
nusoap_fault ($faultcode, $faultactor='', $faultstring='', $faultdetail='')
serialize ()
nusoap_fault ($faultcode, $faultactor='', $faultstring='', $faultdetail='')
serialize ()
nusoap_fault ($faultcode, $faultactor='', $faultstring='', $faultdetail='')
serialize ()
nusoap_fault ($faultcode, $faultactor='', $faultstring='', $faultdetail='')
serialize ()
Public Attributes
$faultcode
$faultactor
$faultstring
$faultdetail
Detailed Description
Contains information for a SOAP fault. Mainly used for returning faults from deployed functions in a server instance.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Version:
Id
class.soap_fault.php,v 1.14 2007/04/11 15:49:47 snichol Exp
public
Contains information for a SOAP fault. Mainly used for returning faults from deployed functions in a server instance.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 14 of file class.soap_fault.php.
Member Function Documentation
nusoap_fault::nusoap_fault ($ faultcode, $ faultactor = '', $ faultstring = '', $ faultdetail = '')
constructor
Parameters:
string $faultcode (SOAP-ENV:Client | SOAP-ENV:Server)
string $faultactor only used when msg routed between multiple actors
string $faultstring human readable error message
mixed $faultdetail detail, typically a string or array of string
Definition at line 1041 of file nusoap.php.
References $faultactor, $faultcode, $faultdetail, $faultstring, and nusoap_base::nusoap_base().
nusoap_fault::nusoap_fault ($ faultcode, $ faultactor = '', $ faultstring = '', $ faultdetail = '')
constructor
Parameters:
string $faultcode (SOAP-ENV:Client | SOAP-ENV:Server)
string $faultactor only used when msg routed between multiple actors
string $faultstring human readable error message
mixed $faultdetail detail, typically a string or array of string
Definition at line 48 of file class.soap_fault.php.
References $faultactor, $faultcode, $faultdetail, $faultstring, and nusoap_base::nusoap_base().
nusoap_fault::nusoap_fault ($ faultcode, $ faultactor = '', $ faultstring = '', $ faultdetail = '')
constructor
Parameters:
string $faultcode (SOAP-ENV:Client | SOAP-ENV:Server)
string $faultactor only used when msg routed between multiple actors
string $faultstring human readable error message
mixed $faultdetail detail, typically a string or array of string
Definition at line 1041 of file nusoap.php.
References $faultactor, $faultcode, $faultdetail, $faultstring, and nusoap_base::nusoap_base().
nusoap_fault::nusoap_fault ($ faultcode, $ faultactor = '', $ faultstring = '', $ faultdetail = '')
constructor
Parameters:
string $faultcode (SOAP-ENV:Client | SOAP-ENV:Server)
string $faultactor only used when msg routed between multiple actors
string $faultstring human readable error message
mixed $faultdetail detail, typically a string or array of string
Definition at line 48 of file class.soap_fault.php.
References $faultactor, $faultcode, $faultdetail, $faultstring, and nusoap_base::nusoap_base().
nusoap_fault::serialize ()
serialize a fault
Returns:
string The serialization of the fault instance. public
Definition at line 1055 of file nusoap.php.
References nusoap_base::serialize_val().
nusoap_fault::serialize ()
serialize a fault
Returns:
string The serialization of the fault instance. public
Definition at line 62 of file class.soap_fault.php.
References nusoap_base::serialize_val().
nusoap_fault::serialize ()
serialize a fault
Returns:
string The serialization of the fault instance. public
Definition at line 1055 of file nusoap.php.
References nusoap_base::serialize_val().
nusoap_fault::serialize ()
serialize a fault
Returns:
string The serialization of the fault instance. public
Definition at line 62 of file class.soap_fault.php.
References nusoap_base::serialize_val().
Member Data Documentation
nusoap_fault::$faultactor
Definition at line 26 of file class.soap_fault.php.
Referenced by nusoap_fault().
nusoap_fault::$faultcode
Definition at line 20 of file class.soap_fault.php.
Referenced by nusoap_fault().
nusoap_fault::$faultdetail
Definition at line 38 of file class.soap_fault.php.
Referenced by nusoap_fault().
nusoap_fault::$faultstring
Definition at line 32 of file class.soap_fault.php.
Referenced by nusoap_fault().
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.soap_fault.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.soap_fault.php
modules/soap_server/nusoap/lib/nusoap.php