DAEDrupalInterface: wsdl Class Reference
wsdl Class Reference
Public Member Functions
wsdl ($wsdl= '', $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $curl_options=null, $use_curl=false)
fetchWSDL ($wsdl)
parseWSDL ($wsdl= '')
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
getBindingData ($binding)
getOperations ($portName= '', $bindingType= 'soap')
getOperationData ($operation, $bindingType= 'soap')
getOperationDataForSoapAction ($soapAction, $bindingType= 'soap')
getTypeDef ($type, $ns)
webDescription ()
serialize ($debug=0)
parametersMatchWrapped ($type, &$parameters)
serializeRPCParameters ($operation, $direction, $parameters, $bindingType= 'soap')
serializeParameters ($operation, $direction, $parameters)
serializeType ($name, $type, $value, $use='encoded', $encodingStyle=false, $unqualified=false)
serializeComplexTypeAttributes ($typeDef, $value, $ns, $uqType)
serializeComplexTypeElements ($typeDef, $value, $ns, $uqType, $use='encoded', $encodingStyle=false)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
addOperation ($name, $in=false, $out=false, $namespace=false, $soapaction=false, $style= 'rpc', $use= 'encoded', $documentation= '', $encodingStyle= '')
wsdl ($wsdl= '', $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $curl_options=null, $use_curl=false)
fetchWSDL ($wsdl)
parseWSDL ($wsdl= '')
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
getBindingData ($binding)
getOperations ($portName= '', $bindingType= 'soap')
getOperationData ($operation, $bindingType= 'soap')
getOperationDataForSoapAction ($soapAction, $bindingType= 'soap')
getTypeDef ($type, $ns)
webDescription ()
serialize ($debug=0)
parametersMatchWrapped ($type, &$parameters)
serializeRPCParameters ($operation, $direction, $parameters, $bindingType= 'soap')
serializeParameters ($operation, $direction, $parameters)
serializeType ($name, $type, $value, $use='encoded', $encodingStyle=false, $unqualified=false)
serializeComplexTypeAttributes ($typeDef, $value, $ns, $uqType)
serializeComplexTypeElements ($typeDef, $value, $ns, $uqType, $use='encoded', $encodingStyle=false)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
addOperation ($name, $in=false, $out=false, $namespace=false, $soapaction=false, $style= 'rpc', $use= 'encoded', $documentation= '', $encodingStyle= '')
wsdl ($wsdl= '', $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $curl_options=null, $use_curl=false)
fetchWSDL ($wsdl)
parseWSDL ($wsdl= '')
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
getBindingData ($binding)
getOperations ($portName= '', $bindingType= 'soap')
getOperationData ($operation, $bindingType= 'soap')
getOperationDataForSoapAction ($soapAction, $bindingType= 'soap')
getTypeDef ($type, $ns)
webDescription ()
serialize ($debug=0)
parametersMatchWrapped ($type, &$parameters)
serializeRPCParameters ($operation, $direction, $parameters, $bindingType= 'soap')
serializeParameters ($operation, $direction, $parameters)
serializeType ($name, $type, $value, $use='encoded', $encodingStyle=false, $unqualified=false)
serializeComplexTypeAttributes ($typeDef, $value, $ns, $uqType)
serializeComplexTypeElements ($typeDef, $value, $ns, $uqType, $use='encoded', $encodingStyle=false)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
addOperation ($name, $in=false, $out=false, $namespace=false, $soapaction=false, $style= 'rpc', $use= 'encoded', $documentation= '', $encodingStyle= '')
wsdl ($wsdl= '', $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $curl_options=null, $use_curl=false)
fetchWSDL ($wsdl)
parseWSDL ($wsdl= '')
start_element ($parser, $name, $attrs)
end_element ($parser, $name)
character_data ($parser, $data)
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
getBindingData ($binding)
getOperations ($portName= '', $bindingType= 'soap')
getOperationData ($operation, $bindingType= 'soap')
getOperationDataForSoapAction ($soapAction, $bindingType= 'soap')
getTypeDef ($type, $ns)
webDescription ()
serialize ($debug=0)
parametersMatchWrapped ($type, &$parameters)
serializeRPCParameters ($operation, $direction, $parameters, $bindingType= 'soap')
serializeParameters ($operation, $direction, $parameters)
serializeType ($name, $type, $value, $use='encoded', $encodingStyle=false, $unqualified=false)
serializeComplexTypeAttributes ($typeDef, $value, $ns, $uqType)
serializeComplexTypeElements ($typeDef, $value, $ns, $uqType, $use='encoded', $encodingStyle=false)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
addOperation ($name, $in=false, $out=false, $namespace=false, $soapaction=false, $style= 'rpc', $use= 'encoded', $documentation= '', $encodingStyle= '')
Public Attributes
$wsdl
$schemas = array()
$currentSchema
$message = array()
$complexTypes = array()
$messages = array()
$currentMessage
$currentOperation
$portTypes = array()
$currentPortType
$bindings = array()
$currentBinding
$ports = array()
$currentPort
$opData = array()
$status = ''
$documentation = false
$endpoint = ''
$import = array()
$parser
$position = 0
$depth = 0
$depth_array = array()
$proxyhost = ''
$proxyport = ''
$proxyusername = ''
$proxypassword = ''
$timeout = 0
$response_timeout = 30
$curl_options = array()
$use_curl = false
$username = ''
$password = ''
$authtype = ''
$certRequest = array()
Detailed Description
parses a WSDL file, allows access to it's data, other utility methods. also builds WSDL structures programmatically.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
class.wsdl.php,v 1.76 2010/04/26 20:15:08 snichol Exp
public
parses a WSDL file, allows access to it's data, other utility methods. also builds WSDL structures programmatically.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 15 of file class.wsdl.php.
Member Function Documentation
wsdl::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds an XML Schema complex type to the WSDL types
Parameters:
string $name
string $typeClass (complexType|simpleType|attribute)
string $phpType currently supported are array and struct (php assoc array)
string $compositor (all|sequence|choice)
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
array $elements e.g. array (name => array(name=>'',type=>''))
array $attrs e.g. array(array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'xsd:string[]'))
string $arrayType as namespace:name (xsd:string)
See also:
nusoap_xmlschema public
Definition at line 6367 of file nusoap.php.
References nusoap_base::expandQname().
wsdl::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds an XML Schema complex type to the WSDL types
Parameters:
string $name
string $typeClass (complexType|simpleType|attribute)
string $phpType currently supported are array and struct (php assoc array)
string $compositor (all|sequence|choice)
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
array $elements e.g. array (name => array(name=>'',type=>''))
array $attrs e.g. array(array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'xsd:string[]'))
string $arrayType as namespace:name (xsd:string)
See also:
nusoap_xmlschema public
Definition at line 1782 of file class.wsdl.php.
References nusoap_base::expandQname().
wsdl::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds an XML Schema complex type to the WSDL types
Parameters:
string $name
string $typeClass (complexType|simpleType|attribute)
string $phpType currently supported are array and struct (php assoc array)
string $compositor (all|sequence|choice)
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
array $elements e.g. array (name => array(name=>'',type=>''))
array $attrs e.g. array(array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'xsd:string[]'))
string $arrayType as namespace:name (xsd:string)
See also:
nusoap_xmlschema public
Definition at line 6365 of file nusoap.php.
References nusoap_base::expandQname().
wsdl::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds an XML Schema complex type to the WSDL types
Parameters:
string $name
string $typeClass (complexType|simpleType|attribute)
string $phpType currently supported are array and struct (php assoc array)
string $compositor (all|sequence|choice)
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
array $elements e.g. array (name => array(name=>'',type=>''))
array $attrs e.g. array(array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'xsd:string[]'))
string $arrayType as namespace:name (xsd:string)
See also:
nusoap_xmlschema public
Definition at line 1782 of file class.wsdl.php.
References nusoap_base::expandQname().
Referenced by addOperation().
wsdl::addElement ($ attrs)
adds an element to the WSDL types
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 6428 of file nusoap.php.
wsdl::addElement ($ attrs)
adds an element to the WSDL types
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 1843 of file class.wsdl.php.
wsdl::addElement ($ attrs)
adds an element to the WSDL types
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 6426 of file nusoap.php.
wsdl::addElement ($ attrs)
adds an element to the WSDL types
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 1843 of file class.wsdl.php.
Referenced by addOperation().
wsdl::addOperation ($ name, $ in = false, $ out = false, $ namespace = false, $ soapaction = false, $ style = 'rpc', $ use = 'encoded', $ documentation = '', $ encodingStyle = '')
register an operation with the server
Parameters:
string $name operation (method) name
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
string $namespace optional The namespace for the operation
string $soapaction optional The soapaction for the operation
string $style (rpc|document) optional The style for the operation Note: when 'document' is specified, parameter and return wrappers are created for you automatically
string $use (encoded|literal) optional The use for the parameters (cannot mix right now)
string $documentation optional The description to include in the WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 6447 of file nusoap.php.
References $documentation, addComplexType(), addElement(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), and nusoap_base::getPrefix().
wsdl::addOperation ($ name, $ in = false, $ out = false, $ namespace = false, $ soapaction = false, $ style = 'rpc', $ use = 'encoded', $ documentation = '', $ encodingStyle = '')
register an operation with the server
Parameters:
string $name operation (method) name
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
string $namespace optional The namespace for the operation
string $soapaction optional The soapaction for the operation
string $style (rpc|document) optional The style for the operation Note: when 'document' is specified, parameter and return wrappers are created for you automatically
string $use (encoded|literal) optional The use for the parameters (cannot mix right now)
string $documentation optional The description to include in the WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 1862 of file class.wsdl.php.
References $documentation, addComplexType(), addElement(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), and nusoap_base::getPrefix().
wsdl::addOperation ($ name, $ in = false, $ out = false, $ namespace = false, $ soapaction = false, $ style = 'rpc', $ use = 'encoded', $ documentation = '', $ encodingStyle = '')
register an operation with the server
Parameters:
string $name operation (method) name
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
string $namespace optional The namespace for the operation
string $soapaction optional The soapaction for the operation
string $style (rpc|document) optional The style for the operation Note: when 'document' is specified, parameter and return wrappers are created for you automatically
string $use (encoded|literal) optional The use for the parameters (cannot mix right now)
string $documentation optional The description to include in the WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 6445 of file nusoap.php.
References $documentation, addComplexType(), addElement(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), and nusoap_base::getPrefix().
wsdl::addOperation ($ name, $ in = false, $ out = false, $ namespace = false, $ soapaction = false, $ style = 'rpc', $ use = 'encoded', $ documentation = '', $ encodingStyle = '')
register an operation with the server
Parameters:
string $name operation (method) name
array $in assoc array of input values: key = param name, value = param type
array $out assoc array of output values: key = param name, value = param type
string $namespace optional The namespace for the operation
string $soapaction optional The soapaction for the operation
string $style (rpc|document) optional The style for the operation Note: when 'document' is specified, parameter and return wrappers are created for you automatically
string $use (encoded|literal) optional The use for the parameters (cannot mix right now)
string $documentation optional The description to include in the WSDL
string $encodingStyle optional (usually 'http://schemas.xmlsoap.org/soap/encoding/' for encoded) public
Definition at line 1862 of file class.wsdl.php.
References $documentation, addComplexType(), addElement(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), and nusoap_base::getPrefix().
wsdl::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds an XML Schema simple type to the WSDL types
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values
See also:
nusoap_xmlschema public
Definition at line 6414 of file nusoap.php.
References nusoap_base::expandQname().
wsdl::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds an XML Schema simple type to the WSDL types
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values
See also:
nusoap_xmlschema public
Definition at line 1829 of file class.wsdl.php.
References nusoap_base::expandQname().
wsdl::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds an XML Schema simple type to the WSDL types
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values
See also:
nusoap_xmlschema public
Definition at line 6412 of file nusoap.php.
References nusoap_base::expandQname().
wsdl::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds an XML Schema simple type to the WSDL types
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values
See also:
nusoap_xmlschema public
Definition at line 1829 of file class.wsdl.php.
References nusoap_base::expandQname().
wsdl::character_data ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 5126 of file nusoap.php.
wsdl::character_data ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 542 of file class.wsdl.php.
wsdl::character_data ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 5124 of file nusoap.php.
wsdl::character_data ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 542 of file class.wsdl.php.
wsdl::end_element ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 5096 of file nusoap.php.
References $parser, nusoap_base::appendDebug(), and nusoap_base::debug().
wsdl::end_element ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 512 of file class.wsdl.php.
References $parser, nusoap_base::appendDebug(), and nusoap_base::debug().
wsdl::end_element ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 5094 of file nusoap.php.
References $parser, nusoap_base::appendDebug(), and nusoap_base::debug().
wsdl::end_element ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 512 of file class.wsdl.php.
References $parser, nusoap_base::appendDebug(), and nusoap_base::debug().
wsdl::fetchWSDL ($ wsdl)
fetches the WSDL document and parses it
public
Definition at line 4676 of file nusoap.php.
References $wsdl, nusoap_base::debug(), and parseWSDL().
wsdl::fetchWSDL ($ wsdl)
fetches the WSDL document and parses it
public
Definition at line 92 of file class.wsdl.php.
References $wsdl, nusoap_base::debug(), and parseWSDL().
wsdl::fetchWSDL ($ wsdl)
fetches the WSDL document and parses it
public
Definition at line 4674 of file nusoap.php.
References $wsdl, nusoap_base::debug(), and parseWSDL().
wsdl::fetchWSDL ($ wsdl)
fetches the WSDL document and parses it
public
Definition at line 92 of file class.wsdl.php.
References $wsdl, nusoap_base::debug(), and parseWSDL().
Referenced by wsdl().
wsdl::getBindingData ($ binding)
Definition at line 5155 of file nusoap.php.
wsdl::getBindingData ($ binding)
Definition at line 571 of file class.wsdl.php.
wsdl::getBindingData ($ binding)
Definition at line 5153 of file nusoap.php.
wsdl::getBindingData ($ binding)
Definition at line 571 of file class.wsdl.php.
wsdl::getOperationData ($ operation, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $operation name of operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 5210 of file nusoap.php.
References $opData.
wsdl::getOperationData ($ operation, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $operation name of operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 626 of file class.wsdl.php.
References $opData.
wsdl::getOperationData ($ operation, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $operation name of operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 5208 of file nusoap.php.
References $opData.
wsdl::getOperationData ($ operation, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $operation name of operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 626 of file class.wsdl.php.
References $opData.
Referenced by serializeParameters(), and serializeRPCParameters().
wsdl::getOperationDataForSoapAction ($ soapAction, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $soapAction soapAction for operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 5242 of file nusoap.php.
References $opData.
wsdl::getOperationDataForSoapAction ($ soapAction, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $soapAction soapAction for operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 658 of file class.wsdl.php.
References $opData.
wsdl::getOperationDataForSoapAction ($ soapAction, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $soapAction soapAction for operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 5240 of file nusoap.php.
References $opData.
wsdl::getOperationDataForSoapAction ($ soapAction, $ bindingType = 'soap')
returns an associative array of data necessary for calling an operation
Parameters:
string $soapAction soapAction for operation
string $bindingType type of binding eg: soap, soap12
Returns:
array public
Definition at line 658 of file class.wsdl.php.
References $opData.
wsdl::getOperations ($ portName = '', $ bindingType = 'soap')
returns an assoc array of operation names => operation data
Parameters:
string $portName WSDL port name
string $bindingType eg: soap, smtp, dime (only soap and soap12 are currently supported)
Returns:
array public
Definition at line 5170 of file nusoap.php.
References nusoap_base::debug().
wsdl::getOperations ($ portName = '', $ bindingType = 'soap')
returns an assoc array of operation names => operation data
Parameters:
string $portName WSDL port name
string $bindingType eg: soap, smtp, dime (only soap and soap12 are currently supported)
Returns:
array public
Definition at line 586 of file class.wsdl.php.
References nusoap_base::debug().
wsdl::getOperations ($ portName = '', $ bindingType = 'soap')
returns an assoc array of operation names => operation data
Parameters:
string $portName WSDL port name
string $bindingType eg: soap, smtp, dime (only soap and soap12 are currently supported)
Returns:
array public
Definition at line 5168 of file nusoap.php.
References nusoap_base::debug().
wsdl::getOperations ($ portName = '', $ bindingType = 'soap')
returns an assoc array of operation names => operation data
Parameters:
string $portName WSDL port name
string $bindingType eg: soap, smtp, dime (only soap and soap12 are currently supported)
Returns:
array public
Definition at line 586 of file class.wsdl.php.
References nusoap_base::debug().
Referenced by webDescription().
wsdl::getTypeDef ($ type, $ ns)
returns an array of information about a given type returns false if no type exists by the given name
typeDef = array('elements' => array(), // refs to elements array 'restrictionBase' => '', 'phpType' => '', 'order' => '(sequence|all)', 'attrs' => array() // refs to attributes array)
Parameters:
string $type the type
string $ns namespace (not prefix) of the type
Returns:
mixed public
See also:
nusoap_xmlschema
Definition at line 5280 of file nusoap.php.
References $i, nusoap_base::appendDebug(), nusoap_base::debug(), getTypeDef(), and nusoap_base::varDump().
wsdl::getTypeDef ($ type, $ ns)
returns an array of information about a given type returns false if no type exists by the given name
typeDef = array('elements' => array(), // refs to elements array 'restrictionBase' => '', 'phpType' => '', 'order' => '(sequence|all)', 'attrs' => array() // refs to attributes array)
Parameters:
string $type the type
string $ns namespace (not prefix) of the type
Returns:
mixed public
See also:
nusoap_xmlschema
Definition at line 696 of file class.wsdl.php.
References $i, nusoap_base::appendDebug(), nusoap_base::debug(), getTypeDef(), and nusoap_base::varDump().
wsdl::getTypeDef ($ type, $ ns)
returns an array of information about a given type returns false if no type exists by the given name
typeDef = array('elements' => array(), // refs to elements array 'restrictionBase' => '', 'phpType' => '', 'order' => '(sequence|all)', 'attrs' => array() // refs to attributes array)
Parameters:
string $type the type
string $ns namespace (not prefix) of the type
Returns:
mixed public
See also:
nusoap_xmlschema
Definition at line 5278 of file nusoap.php.
References $i, nusoap_base::appendDebug(), nusoap_base::debug(), getTypeDef(), and nusoap_base::varDump().
wsdl::getTypeDef ($ type, $ ns)
returns an array of information about a given type returns false if no type exists by the given name
typeDef = array('elements' => array(), // refs to elements array 'restrictionBase' => '', 'phpType' => '', 'order' => '(sequence|all)', 'attrs' => array() // refs to attributes array)
Parameters:
string $type the type
string $ns namespace (not prefix) of the type
Returns:
mixed public
See also:
nusoap_xmlschema
Definition at line 696 of file class.wsdl.php.
References $i, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
Referenced by getTypeDef(), parametersMatchWrapped(), serialize(), serializeComplexTypeAttributes(), serializeComplexTypeElements(), and serializeType().
wsdl::parametersMatchWrapped ($ type, &$ parameters)
determine whether a set of parameters are unwrapped when they are expect to be wrapped, Microsoft-style.
Parameters:
string $type the type (element name) of the wrapper
array $parameters the parameter values for the SOAP call
Returns:
boolean whether they parameters are unwrapped (and should be wrapped) private
Definition at line 5614 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getNamespaceFromPrefix(), getTypeDef(), and nusoap_base::varDump().
wsdl::parametersMatchWrapped ($ type, &$ parameters)
determine whether a set of parameters are unwrapped when they are expect to be wrapped, Microsoft-style.
Parameters:
string $type the type (element name) of the wrapper
array $parameters the parameter values for the SOAP call
Returns:
boolean whether they parameters are unwrapped (and should be wrapped) private
Definition at line 1029 of file class.wsdl.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getNamespaceFromPrefix(), getTypeDef(), and nusoap_base::varDump().
wsdl::parametersMatchWrapped ($ type, &$ parameters)
determine whether a set of parameters are unwrapped when they are expect to be wrapped, Microsoft-style.
Parameters:
string $type the type (element name) of the wrapper
array $parameters the parameter values for the SOAP call
Returns:
boolean whether they parameters are unwrapped (and should be wrapped) private
Definition at line 5612 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getNamespaceFromPrefix(), getTypeDef(), and nusoap_base::varDump().
wsdl::parametersMatchWrapped ($ type, &$ parameters)
determine whether a set of parameters are unwrapped when they are expect to be wrapped, Microsoft-style.
Parameters:
string $type the type (element name) of the wrapper
array $parameters the parameter values for the SOAP call
Returns:
boolean whether they parameters are unwrapped (and should be wrapped) private
Definition at line 1029 of file class.wsdl.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getNamespaceFromPrefix(), getTypeDef(), and nusoap_base::varDump().
Referenced by serializeRPCParameters().
wsdl::parseWSDL ($ wsdl = '')
parses the wsdl document
Parameters:
string $wsdl path or URL private
Definition at line 4779 of file nusoap.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), and nusoap_base::setError().
wsdl::parseWSDL ($ wsdl = '')
parses the wsdl document
Parameters:
string $wsdl path or URL private
Definition at line 195 of file class.wsdl.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), and nusoap_base::setError().
wsdl::parseWSDL ($ wsdl = '')
parses the wsdl document
Parameters:
string $wsdl path or URL private
Definition at line 4777 of file nusoap.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), and nusoap_base::setError().
wsdl::parseWSDL ($ wsdl = '')
parses the wsdl document
Parameters:
string $wsdl path or URL private
Definition at line 195 of file class.wsdl.php.
References $err, $wsdl, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), and nusoap_base::setError().
Referenced by fetchWSDL().
wsdl::serialize ($ debug = 0)
serialize the parsed wsdl
Parameters:
mixed $debug whether to put debug=1 in endpoint URL
Returns:
string serialization of WSDL public
Definition at line 5475 of file nusoap.php.
References nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), and getTypeDef().
wsdl::serialize ($ debug = 0)
serialize the parsed wsdl
Parameters:
mixed $debug whether to put debug=1 in endpoint URL
Returns:
string serialization of WSDL public
Definition at line 890 of file class.wsdl.php.
References nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), and getTypeDef().
wsdl::serialize ($ debug = 0)
serialize the parsed wsdl
Parameters:
mixed $debug whether to put debug=1 in endpoint URL
Returns:
string serialization of WSDL public
Definition at line 5473 of file nusoap.php.
References nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), and getTypeDef().
wsdl::serialize ($ debug = 0)
serialize the parsed wsdl
Parameters:
mixed $debug whether to put debug=1 in endpoint URL
Returns:
string serialization of WSDL public
Definition at line 890 of file class.wsdl.php.
References nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), and getTypeDef().
wsdl::serializeComplexTypeAttributes ($ typeDef, $ value, $ ns, $ uqType)
serializes the attributes for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
Returns:
string value serialized as an XML string private
Definition at line 6196 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), getTypeDef(), and serializeComplexTypeAttributes().
wsdl::serializeComplexTypeAttributes ($ typeDef, $ value, $ ns, $ uqType)
serializes the attributes for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
Returns:
string value serialized as an XML string private
Definition at line 1611 of file class.wsdl.php.
References nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), getTypeDef(), and serializeComplexTypeAttributes().
wsdl::serializeComplexTypeAttributes ($ typeDef, $ value, $ ns, $ uqType)
serializes the attributes for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
Returns:
string value serialized as an XML string private
Definition at line 6194 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), getTypeDef(), and serializeComplexTypeAttributes().
wsdl::serializeComplexTypeAttributes ($ typeDef, $ value, $ ns, $ uqType)
serializes the attributes for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
Returns:
string value serialized as an XML string private
Definition at line 1611 of file class.wsdl.php.
References nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), and getTypeDef().
Referenced by serializeComplexTypeAttributes(), and serializeType().
wsdl::serializeComplexTypeElements ($ typeDef, $ value, $ ns, $ uqType, $ use = 'encoded', $ encodingStyle = false)
serializes the elements for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
Returns:
string value serialized as an XML string private
Definition at line 6259 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), getTypeDef(), nusoap_base::isArraySimpleOrStruct(), nusoap_base::serialize_val(), serializeComplexTypeElements(), and serializeType().
wsdl::serializeComplexTypeElements ($ typeDef, $ value, $ ns, $ uqType, $ use = 'encoded', $ encodingStyle = false)
serializes the elements for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
Returns:
string value serialized as an XML string private
Definition at line 1674 of file class.wsdl.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), getTypeDef(), nusoap_base::isArraySimpleOrStruct(), nusoap_base::serialize_val(), serializeComplexTypeElements(), and serializeType().
wsdl::serializeComplexTypeElements ($ typeDef, $ value, $ ns, $ uqType, $ use = 'encoded', $ encodingStyle = false)
serializes the elements for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
Returns:
string value serialized as an XML string private
Definition at line 6257 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), getTypeDef(), nusoap_base::isArraySimpleOrStruct(), nusoap_base::serialize_val(), serializeComplexTypeElements(), and serializeType().
wsdl::serializeComplexTypeElements ($ typeDef, $ value, $ ns, $ uqType, $ use = 'encoded', $ encodingStyle = false)
serializes the elements for a complexType
Parameters:
array $typeDef our internal representation of an XML schema type (or element)
mixed $value a native PHP value (parameter value)
string $ns the namespace of the type
string $uqType the local part of the type
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
Returns:
string value serialized as an XML string private
Definition at line 1674 of file class.wsdl.php.
References nusoap_base::debug(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), getTypeDef(), nusoap_base::isArraySimpleOrStruct(), nusoap_base::serialize_val(), and serializeType().
Referenced by serializeComplexTypeElements(), and serializeType().
wsdl::serializeParameters ($ operation, $ direction, $ parameters)
serialize a PHP value according to a WSDL message definition
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Deprecated:
Definition at line 5798 of file nusoap.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeParameters ($ operation, $ direction, $ parameters)
serialize a PHP value according to a WSDL message definition
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Deprecated:
Definition at line 1213 of file class.wsdl.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeParameters ($ operation, $ direction, $ parameters)
serialize a PHP value according to a WSDL message definition
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Deprecated:
Definition at line 5796 of file nusoap.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeParameters ($ operation, $ direction, $ parameters)
serialize a PHP value according to a WSDL message definition
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Deprecated:
Definition at line 1213 of file class.wsdl.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeRPCParameters ($ operation, $ direction, $ parameters, $ bindingType = 'soap')
serialize PHP values according to a WSDL message definition contrary to the method name, this is not limited to RPC
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
string $bindingType (soap|soap12)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Definition at line 5697 of file nusoap.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), parametersMatchWrapped(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeRPCParameters ($ operation, $ direction, $ parameters, $ bindingType = 'soap')
serialize PHP values according to a WSDL message definition contrary to the method name, this is not limited to RPC
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
string $bindingType (soap|soap12)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Definition at line 1112 of file class.wsdl.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), parametersMatchWrapped(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeRPCParameters ($ operation, $ direction, $ parameters, $ bindingType = 'soap')
serialize PHP values according to a WSDL message definition contrary to the method name, this is not limited to RPC
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
string $bindingType (soap|soap12)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Definition at line 5695 of file nusoap.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), parametersMatchWrapped(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeRPCParameters ($ operation, $ direction, $ parameters, $ bindingType = 'soap')
serialize PHP values according to a WSDL message definition contrary to the method name, this is not limited to RPC
TODO
multi-ref serialization
validate PHP values against type definitions, return errors if invalid
Parameters:
string $operation operation name
string $direction (input|output)
mixed $parameters parameter value(s)
string $bindingType (soap|soap12)
Returns:
mixed parameters serialized as XML or false on error (e.g. operation not found) public
Definition at line 1112 of file class.wsdl.php.
References $opData, nusoap_base::appendDebug(), nusoap_base::debug(), getOperationData(), nusoap_base::isArraySimpleOrStruct(), parametersMatchWrapped(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeType ($ name, $ type, $ value, $ use = 'encoded', $ encodingStyle = false, $ unqualified = false)
serializes a PHP value according a given type definition
Parameters:
string $name name of value (part or element)
string $type XML schema type of value (type or element)
mixed $value a native PHP value (parameter value)
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
boolean $unqualified a kludge for what should be XML namespace form handling
Returns:
string value serialized as an XML string private
Definition at line 5877 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), getTypeDef(), nusoap_base::serialize_val(), serializeComplexTypeAttributes(), serializeComplexTypeElements(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeType ($ name, $ type, $ value, $ use = 'encoded', $ encodingStyle = false, $ unqualified = false)
serializes a PHP value according a given type definition
Parameters:
string $name name of value (part or element)
string $type XML schema type of value (type or element)
mixed $value a native PHP value (parameter value)
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
boolean $unqualified a kludge for what should be XML namespace form handling
Returns:
string value serialized as an XML string private
Definition at line 1292 of file class.wsdl.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), getTypeDef(), nusoap_base::serialize_val(), serializeComplexTypeAttributes(), serializeComplexTypeElements(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeType ($ name, $ type, $ value, $ use = 'encoded', $ encodingStyle = false, $ unqualified = false)
serializes a PHP value according a given type definition
Parameters:
string $name name of value (part or element)
string $type XML schema type of value (type or element)
mixed $value a native PHP value (parameter value)
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
boolean $unqualified a kludge for what should be XML namespace form handling
Returns:
string value serialized as an XML string private
Definition at line 5875 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), getTypeDef(), nusoap_base::serialize_val(), serializeComplexTypeAttributes(), serializeComplexTypeElements(), serializeType(), nusoap_base::setError(), and nusoap_base::varDump().
wsdl::serializeType ($ name, $ type, $ value, $ use = 'encoded', $ encodingStyle = false, $ unqualified = false)
serializes a PHP value according a given type definition
Parameters:
string $name name of value (part or element)
string $type XML schema type of value (type or element)
mixed $value a native PHP value (parameter value)
string $use use for part (encoded|literal)
string $encodingStyle SOAP encoding style for the value (if different than the enclosing style)
boolean $unqualified a kludge for what should be XML namespace form handling
Returns:
string value serialized as an XML string private
Definition at line 1292 of file class.wsdl.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandEntities(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), getTypeDef(), nusoap_base::serialize_val(), serializeComplexTypeAttributes(), serializeComplexTypeElements(), nusoap_base::setError(), and nusoap_base::varDump().
Referenced by serializeComplexTypeElements(), serializeParameters(), serializeRPCParameters(), and serializeType().
wsdl::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 5146 of file nusoap.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
wsdl::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 562 of file class.wsdl.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
wsdl::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 5144 of file nusoap.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
wsdl::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, certpassword (optional), verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 562 of file class.wsdl.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
wsdl::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 4883 of file nusoap.php.
References $depth, $parser, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), and nusoap_base::getPrefixFromNamespace().
wsdl::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 299 of file class.wsdl.php.
References $depth, $parser, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), and nusoap_base::getPrefixFromNamespace().
wsdl::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 4881 of file nusoap.php.
References $depth, $parser, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), and nusoap_base::getPrefixFromNamespace().
wsdl::start_element ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 299 of file class.wsdl.php.
References $depth, $parser, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), and nusoap_base::getPrefixFromNamespace().
wsdl::webDescription ()
prints html description of services
private
Definition at line 5340 of file nusoap.php.
References getOperations(), and nusoap_base::setError().
wsdl::webDescription ()
prints html description of services
private
Definition at line 756 of file class.wsdl.php.
References getOperations(), and nusoap_base::setError().
wsdl::webDescription ()
prints html description of services
private
Definition at line 5338 of file nusoap.php.
References getOperations(), and nusoap_base::setError().
wsdl::webDescription ()
prints html description of services
private
Definition at line 756 of file class.wsdl.php.
References getOperations(), and nusoap_base::setError().
wsdl::wsdl ($ wsdl = '', $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ curl_options = null, $ use_curl = false)
constructor
Parameters:
string $wsdl WSDL document URL
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
array $curl_options user-specified cURL options
boolean $use_curl try to use cURL public
Definition at line 4656 of file nusoap.php.
References $curl_options, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $use_curl, $wsdl, nusoap_base::debug(), fetchWSDL(), and nusoap_base::nusoap_base().
wsdl::wsdl ($ wsdl = '', $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ curl_options = null, $ use_curl = false)
constructor
Parameters:
string $wsdl WSDL document URL
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
array $curl_options user-specified cURL options
boolean $use_curl try to use cURL public
Definition at line 72 of file class.wsdl.php.
References $curl_options, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $use_curl, $wsdl, nusoap_base::debug(), fetchWSDL(), and nusoap_base::nusoap_base().
wsdl::wsdl ($ wsdl = '', $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ curl_options = null, $ use_curl = false)
constructor
Parameters:
string $wsdl WSDL document URL
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
array $curl_options user-specified cURL options
boolean $use_curl try to use cURL public
Definition at line 4654 of file nusoap.php.
References $curl_options, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $use_curl, $wsdl, nusoap_base::debug(), fetchWSDL(), and nusoap_base::nusoap_base().
wsdl::wsdl ($ wsdl = '', $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ curl_options = null, $ use_curl = false)
constructor
Parameters:
string $wsdl WSDL document URL
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
array $curl_options user-specified cURL options
boolean $use_curl try to use cURL public
Definition at line 72 of file class.wsdl.php.
References $curl_options, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $use_curl, $wsdl, nusoap_base::debug(), fetchWSDL(), and nusoap_base::nusoap_base().
Member Data Documentation
wsdl::$authtype = ''
Definition at line 55 of file class.wsdl.php.
Referenced by setCredentials().
wsdl::$bindings = array()
Definition at line 28 of file class.wsdl.php.
wsdl::$certRequest = array()
Definition at line 56 of file class.wsdl.php.
Referenced by setCredentials().
wsdl::$complexTypes = array()
Definition at line 22 of file class.wsdl.php.
wsdl::$curl_options = array()
Definition at line 50 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$currentBinding
Definition at line 29 of file class.wsdl.php.
wsdl::$currentMessage
Definition at line 24 of file class.wsdl.php.
wsdl::$currentOperation
Definition at line 25 of file class.wsdl.php.
wsdl::$currentPort
Definition at line 31 of file class.wsdl.php.
wsdl::$currentPortType
Definition at line 27 of file class.wsdl.php.
wsdl::$currentSchema
Definition at line 20 of file class.wsdl.php.
wsdl::$depth = 0
Definition at line 41 of file class.wsdl.php.
Referenced by start_element().
wsdl::$depth_array = array()
Definition at line 42 of file class.wsdl.php.
wsdl::$documentation = false
Definition at line 34 of file class.wsdl.php.
Referenced by addOperation().
wsdl::$endpoint = ''
Definition at line 35 of file class.wsdl.php.
wsdl::$import = array()
Definition at line 37 of file class.wsdl.php.
wsdl::$message = array()
Definition at line 21 of file class.wsdl.php.
wsdl::$messages = array()
Definition at line 23 of file class.wsdl.php.
wsdl::$opData = array()
Definition at line 32 of file class.wsdl.php.
Referenced by getOperationData(), getOperationDataForSoapAction(), serializeParameters(), and serializeRPCParameters().
wsdl::$parser
Definition at line 39 of file class.wsdl.php.
Referenced by end_element(), and start_element().
wsdl::$password = ''
Definition at line 54 of file class.wsdl.php.
Referenced by setCredentials().
wsdl::$ports = array()
Definition at line 30 of file class.wsdl.php.
wsdl::$portTypes = array()
Definition at line 26 of file class.wsdl.php.
wsdl::$position = 0
Definition at line 40 of file class.wsdl.php.
wsdl::$proxyhost = ''
Definition at line 44 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$proxypassword = ''
Definition at line 47 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$proxyport = ''
Definition at line 45 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$proxyusername = ''
Definition at line 46 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$response_timeout = 30
Definition at line 49 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$schemas = array()
Definition at line 19 of file class.wsdl.php.
wsdl::$status = ''
Definition at line 33 of file class.wsdl.php.
wsdl::$timeout = 0
Definition at line 48 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$use_curl = false
Definition at line 51 of file class.wsdl.php.
Referenced by wsdl().
wsdl::$username = ''
Definition at line 53 of file class.wsdl.php.
Referenced by setCredentials().
wsdl::$wsdl
Definition at line 17 of file class.wsdl.php.
Referenced by fetchWSDL(), parseWSDL(), and wsdl().
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.wsdl.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.wsdl.php
modules/soap_server/nusoap/lib/nusoap.php