DAEDrupalInterface: soapval Class Reference
soapval Class Reference
Public Member Functions
soapval ($name='soapval', $type=false, $value=-1, $element_ns=false, $type_ns=false, $attributes=false)
serialize ($use='encoded')
decode ()
soapval ($name='soapval', $type=false, $value=-1, $element_ns=false, $type_ns=false, $attributes=false)
serialize ($use='encoded')
decode ()
soapval ($name='soapval', $type=false, $value=-1, $element_ns=false, $type_ns=false, $attributes=false)
serialize ($use='encoded')
decode ()
soapval ($name='soapval', $type=false, $value=-1, $element_ns=false, $type_ns=false, $attributes=false)
serialize ($use='encoded')
decode ()
Public Attributes
$name
$type
$value
$element_ns
$type_ns
$attributes
Detailed Description
For creating serializable abstractions of native PHP types. This class allows element name/namespace, XSD type, and XML attributes to be associated with a value. This is extremely useful when WSDL is not used, but is also useful when WSDL is used with polymorphic types, including xsd:anyType and user-defined types.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Version:
Id
class.soap_val.php,v 1.11 2007/04/06 13:56:32 snichol Exp
public
For creating serializable abstractions of native PHP types. This class allows element name/namespace, XSD type, and XML attributes to be associated with a value. This is extremely useful when WSDL is not used, but is also useful when WSDL is used with polymorphic types, including xsd:anyType and user-defined types.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 17 of file class.soap_val.php.
Member Function Documentation
soapval::decode ()
decodes a soapval object into a PHP native type
Returns:
mixed public
Definition at line 2149 of file nusoap.php.
soapval::decode ()
decodes a soapval object into a PHP native type
Returns:
mixed public
Definition at line 99 of file class.soap_val.php.
soapval::decode ()
decodes a soapval object into a PHP native type
Returns:
mixed public
Definition at line 2149 of file nusoap.php.
soapval::decode ()
decodes a soapval object into a PHP native type
Returns:
mixed public
Definition at line 99 of file class.soap_val.php.
soapval::serialize ($ use = 'encoded')
return serialized value
Parameters:
string $use The WSDL use value (encoded|literal)
Returns:
string XML data public
Definition at line 2139 of file nusoap.php.
References nusoap_base::serialize_val().
soapval::serialize ($ use = 'encoded')
return serialized value
Parameters:
string $use The WSDL use value (encoded|literal)
Returns:
string XML data public
Definition at line 89 of file class.soap_val.php.
References nusoap_base::serialize_val().
soapval::serialize ($ use = 'encoded')
return serialized value
Parameters:
string $use The WSDL use value (encoded|literal)
Returns:
string XML data public
Definition at line 2139 of file nusoap.php.
References nusoap_base::serialize_val().
soapval::serialize ($ use = 'encoded')
return serialized value
Parameters:
string $use The WSDL use value (encoded|literal)
Returns:
string XML data public
Definition at line 89 of file class.soap_val.php.
References nusoap_base::serialize_val().
soapval::soapval ($ name = 'soapval', $ type = false, $ value = -1, $ element_ns = false, $ type_ns = false, $ attributes = false)
constructor
Parameters:
string $name optional name
mixed $type optional type name
mixed $value optional value
mixed $element_ns optional namespace of value
mixed $type_ns optional namespace of type
mixed $attributes associative array of attributes to add to element serialization public
Definition at line 2122 of file nusoap.php.
References $attributes, $element_ns, $name, $type, $type_ns, $value, and nusoap_base::nusoap_base().
soapval::soapval ($ name = 'soapval', $ type = false, $ value = -1, $ element_ns = false, $ type_ns = false, $ attributes = false)
constructor
Parameters:
string $name optional name
mixed $type optional type name
mixed $value optional value
mixed $element_ns optional namespace of value
mixed $type_ns optional namespace of type
mixed $attributes associative array of attributes to add to element serialization public
Definition at line 72 of file class.soap_val.php.
References $attributes, $element_ns, $name, $type, $type_ns, $value, and nusoap_base::nusoap_base().
soapval::soapval ($ name = 'soapval', $ type = false, $ value = -1, $ element_ns = false, $ type_ns = false, $ attributes = false)
constructor
Parameters:
string $name optional name
mixed $type optional type name
mixed $value optional value
mixed $element_ns optional namespace of value
mixed $type_ns optional namespace of type
mixed $attributes associative array of attributes to add to element serialization public
Definition at line 2122 of file nusoap.php.
References $attributes, $element_ns, $name, $type, $type_ns, $value, and nusoap_base::nusoap_base().
soapval::soapval ($ name = 'soapval', $ type = false, $ value = -1, $ element_ns = false, $ type_ns = false, $ attributes = false)
constructor
Parameters:
string $name optional name
mixed $type optional type name
mixed $value optional value
mixed $element_ns optional namespace of value
mixed $type_ns optional namespace of type
mixed $attributes associative array of attributes to add to element serialization public
Definition at line 72 of file class.soap_val.php.
References $attributes, $element_ns, $name, $type, $type_ns, $value, and nusoap_base::nusoap_base().
Member Data Documentation
soapval::$attributes
Definition at line 59 of file class.soap_val.php.
Referenced by soapval().
soapval::$element_ns
Definition at line 45 of file class.soap_val.php.
Referenced by soapval().
soapval::$name
Definition at line 24 of file class.soap_val.php.
Referenced by soapval().
soapval::$type
Definition at line 31 of file class.soap_val.php.
Referenced by soapval().
soapval::$type_ns
Definition at line 52 of file class.soap_val.php.
Referenced by soapval().
soapval::$value
Definition at line 38 of file class.soap_val.php.
Referenced by soapval().
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.soap_val.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.soap_val.php
modules/soap_server/nusoap/lib/nusoap.php