DAEDrupalInterface: nusoap_client Class Reference
nusoap_client Class Reference
Public Member Functions
nusoap_client ($endpoint, $wsdl=false, $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $portName= '')
call ($operation, $params=array(), $namespace='http://tempuri.org', $soapAction='', $headers=false, $rpcParams=null, $style='rpc', $use='encoded')
checkWSDL ()
loadWSDL ()
getOperationData ($operation)
send ($msg, $soapaction= '', $timeout=0, $response_timeout=30)
parseResponse ($headers, $data)
setCurlOption ($option, $value)
setEndpoint ($endpoint)
setHeaders ($headers)
getHeaders ()
getHeader ()
setHTTPProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '')
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
setHTTPEncoding ($enc='gzip, deflate')
setUseCURL ($use)
useHTTPPersistentConnection ()
getDefaultRpcParams ()
setDefaultRpcParams ($rpcParams)
getProxy ()
_getProxyClassCode ($r)
getProxyClassCode ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
decodeUTF8 ($bool)
setCookie ($name, $value)
getCookies ()
checkCookies ()
UpdateCookies ($cookies)
nusoap_client ($endpoint, $wsdl=false, $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $portName= '')
call ($operation, $params=array(), $namespace='http://tempuri.org', $soapAction='', $headers=false, $rpcParams=null, $style='rpc', $use='encoded')
checkWSDL ()
loadWSDL ()
getOperationData ($operation)
send ($msg, $soapaction= '', $timeout=0, $response_timeout=30)
parseResponse ($headers, $data)
setCurlOption ($option, $value)
setEndpoint ($endpoint)
setHeaders ($headers)
getHeaders ()
getHeader ()
setHTTPProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '')
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
setHTTPEncoding ($enc='gzip, deflate')
setUseCURL ($use)
useHTTPPersistentConnection ()
getDefaultRpcParams ()
setDefaultRpcParams ($rpcParams)
getProxy ()
_getProxyClassCode ($r)
getProxyClassCode ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
decodeUTF8 ($bool)
setCookie ($name, $value)
getCookies ()
checkCookies ()
UpdateCookies ($cookies)
nusoap_client ($endpoint, $wsdl=false, $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $portName= '')
call ($operation, $params=array(), $namespace='http://tempuri.org', $soapAction='', $headers=false, $rpcParams=null, $style='rpc', $use='encoded')
checkWSDL ()
loadWSDL ()
getOperationData ($operation)
send ($msg, $soapaction= '', $timeout=0, $response_timeout=30)
parseResponse ($headers, $data)
setCurlOption ($option, $value)
setEndpoint ($endpoint)
setHeaders ($headers)
getHeaders ()
getHeader ()
setHTTPProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '')
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
setHTTPEncoding ($enc='gzip, deflate')
setUseCURL ($use)
useHTTPPersistentConnection ()
getDefaultRpcParams ()
setDefaultRpcParams ($rpcParams)
getProxy ()
_getProxyClassCode ($r)
getProxyClassCode ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
decodeUTF8 ($bool)
setCookie ($name, $value)
getCookies ()
checkCookies ()
UpdateCookies ($cookies)
nusoap_client ($endpoint, $wsdl=false, $proxyhost=false, $proxyport=false, $proxyusername=false, $proxypassword=false, $timeout=0, $response_timeout=30, $portName= '')
call ($operation, $params=array(), $namespace='http://tempuri.org', $soapAction='', $headers=false, $rpcParams=null, $style='rpc', $use='encoded')
checkWSDL ()
loadWSDL ()
getOperationData ($operation)
send ($msg, $soapaction= '', $timeout=0, $response_timeout=30)
parseResponse ($headers, $data)
setCurlOption ($option, $value)
setEndpoint ($endpoint)
setHeaders ($headers)
getHeaders ()
getHeader ()
setHTTPProxy ($proxyhost, $proxyport, $proxyusername= '', $proxypassword= '')
setCredentials ($username, $password, $authtype= 'basic', $certRequest=array())
setHTTPEncoding ($enc='gzip, deflate')
setUseCURL ($use)
useHTTPPersistentConnection ()
getDefaultRpcParams ()
setDefaultRpcParams ($rpcParams)
getProxy ()
_getProxyClassCode ($r)
getProxyClassCode ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
decodeUTF8 ($bool)
setCookie ($name, $value)
getCookies ()
checkCookies ()
UpdateCookies ($cookies)
Public Attributes
$username = ''
$password = ''
$authtype = ''
$certRequest = array()
$requestHeaders = false
$responseHeaders = ''
$responseHeader = NULL
$document = ''
$endpoint
$forceEndpoint = ''
$proxyhost = ''
$proxyport = ''
$proxyusername = ''
$proxypassword = ''
$portName = ''
$xml_encoding = ''
$http_encoding = false
$timeout = 0
$response_timeout = 30
$endpointType = ''
$persistentConnection = false
$defaultRpcParams = false
$request = ''
$response = ''
$responseData = ''
$cookies = array()
$decode_utf8 = true
$operations = array()
$curl_options = array()
$bindingType = ''
$use_curl = false
$fault
$faultcode
$faultstring
$faultdetail
Detailed Description
[nu]soapclient higher level class for easy usage.
usage:
// instantiate client with server info $soapclient = new nusoap_client(string path [ ,mixed wsdl]);
// call method, get results echo $soapclient->call(string methodname [ ,array parameters]);
// bye bye client unset($soapclient);
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
class.soapclient.php,v 1.69 2010/04/26 20:15:08 snichol Exp
public
[nu]soapclient higher level class for easy usage.
usage:
// instantiate client with server info $soapclient = new nusoap_client(string path [ ,mixed wsdl]);
// call method, get results echo $soapclient->call(string methodname [ ,array parameters]);
// bye bye client unset($soapclient);
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 26 of file class.soapclient.php.
Member Function Documentation
nusoap_client::_getProxyClassCode ($ r)
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class private
Definition at line 7909 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), loadWSDL(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::_getProxyClassCode ($ r)
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class private
Definition at line 749 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), loadWSDL(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::_getProxyClassCode ($ r)
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class private
Definition at line 7907 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), loadWSDL(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::_getProxyClassCode ($ r)
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class private
Definition at line 749 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), loadWSDL(), nusoap_base::setError(), and nusoap_base::varDump().
Referenced by getProxy(), and getProxyClassCode().
nusoap_client::call ($ operation, $ params = array(), $ namespace = 'http://tempuri.org', $ soapAction = '', $ headers = false, $ rpcParams = null, $ style = 'rpc', $ use = 'encoded')
calls method, returns PHP native type
Parameters:
string $operation SOAP server URL or path
mixed $params An array, associative or simple, of the parameters for the method call, or a string that is the XML for the call. For rpc style, this call will wrap the XML in a tag named after the method, as well as the SOAP Envelope and Body. For document style, this will only wrap with the Envelope and Body. IMPORTANT: when using an array with document style, in which case there is really one parameter, the root of the fragment used in the call, which encloses what programmers normally think of parameters. A parameter array *must* include the wrapper.
string $namespace optional method namespace (WSDL can override)
string $soapAction optional SOAPAction value (WSDL can override)
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
boolean $rpcParams optional (no longer used)
string $style optional (rpc|document) the style to use when serializing parameters (WSDL can override)
string $use optional (encoded|literal) the use when serializing parameters (WSDL can override)
Returns:
mixed response from SOAP call, normally an associative array mirroring the structure of the XML response, false for certain fatal errors public
Definition at line 7317 of file nusoap.php.
References nusoap_base::$usedNamespaces, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), getHTTPBody(), getOperationData(), loadWSDL(), send(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::call ($ operation, $ params = array(), $ namespace = 'http://tempuri.org', $ soapAction = '', $ headers = false, $ rpcParams = null, $ style = 'rpc', $ use = 'encoded')
calls method, returns PHP native type
Parameters:
string $operation SOAP server URL or path
mixed $params An array, associative or simple, of the parameters for the method call, or a string that is the XML for the call. For rpc style, this call will wrap the XML in a tag named after the method, as well as the SOAP Envelope and Body. For document style, this will only wrap with the Envelope and Body. IMPORTANT: when using an array with document style, in which case there is really one parameter, the root of the fragment used in the call, which encloses what programmers normally think of parameters. A parameter array *must* include the wrapper.
string $namespace optional method namespace (WSDL can override)
string $soapAction optional SOAPAction value (WSDL can override)
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
boolean $rpcParams optional (no longer used)
string $style optional (rpc|document) the style to use when serializing parameters (WSDL can override)
string $use optional (encoded|literal) the use when serializing parameters (WSDL can override)
Returns:
mixed response from SOAP call, normally an associative array mirroring the structure of the XML response, false for certain fatal errors public
Definition at line 157 of file class.soapclient.php.
References nusoap_base::$usedNamespaces, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), getHTTPBody(), getOperationData(), loadWSDL(), send(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::call ($ operation, $ params = array(), $ namespace = 'http://tempuri.org', $ soapAction = '', $ headers = false, $ rpcParams = null, $ style = 'rpc', $ use = 'encoded')
calls method, returns PHP native type
Parameters:
string $operation SOAP server URL or path
mixed $params An array, associative or simple, of the parameters for the method call, or a string that is the XML for the call. For rpc style, this call will wrap the XML in a tag named after the method, as well as the SOAP Envelope and Body. For document style, this will only wrap with the Envelope and Body. IMPORTANT: when using an array with document style, in which case there is really one parameter, the root of the fragment used in the call, which encloses what programmers normally think of parameters. A parameter array *must* include the wrapper.
string $namespace optional method namespace (WSDL can override)
string $soapAction optional SOAPAction value (WSDL can override)
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
boolean $rpcParams optional (no longer used)
string $style optional (rpc|document) the style to use when serializing parameters (WSDL can override)
string $use optional (encoded|literal) the use when serializing parameters (WSDL can override)
Returns:
mixed response from SOAP call, normally an associative array mirroring the structure of the XML response, false for certain fatal errors public
Definition at line 7315 of file nusoap.php.
References nusoap_base::$usedNamespaces, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), getHTTPBody(), getOperationData(), loadWSDL(), send(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::call ($ operation, $ params = array(), $ namespace = 'http://tempuri.org', $ soapAction = '', $ headers = false, $ rpcParams = null, $ style = 'rpc', $ use = 'encoded')
calls method, returns PHP native type
Parameters:
string $operation SOAP server URL or path
mixed $params An array, associative or simple, of the parameters for the method call, or a string that is the XML for the call. For rpc style, this call will wrap the XML in a tag named after the method, as well as the SOAP Envelope and Body. For document style, this will only wrap with the Envelope and Body. IMPORTANT: when using an array with document style, in which case there is really one parameter, the root of the fragment used in the call, which encloses what programmers normally think of parameters. A parameter array *must* include the wrapper.
string $namespace optional method namespace (WSDL can override)
string $soapAction optional SOAPAction value (WSDL can override)
mixed $headers optional string of XML with SOAP header content, or array of soapval objects for SOAP headers, or associative array
boolean $rpcParams optional (no longer used)
string $style optional (rpc|document) the style to use when serializing parameters (WSDL can override)
string $use optional (encoded|literal) the use when serializing parameters (WSDL can override)
Returns:
mixed response from SOAP call, normally an associative array mirroring the structure of the XML response, false for certain fatal errors public
Definition at line 157 of file class.soapclient.php.
References nusoap_base::$usedNamespaces, nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::getError(), getHTTPBody(), getOperationData(), loadWSDL(), send(), nusoap_base::serialize_val(), nusoap_base::serializeEnvelope(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::checkCookies ()
checks all Cookies and delete those which are expired
Returns:
boolean always return true private
Definition at line 8052 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::checkCookies ()
checks all Cookies and delete those which are expired
Returns:
boolean always return true private
Definition at line 892 of file class.soapclient.php.
References nusoap_base::debug().
nusoap_client::checkCookies ()
checks all Cookies and delete those which are expired
Returns:
boolean always return true private
Definition at line 8050 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::checkCookies ()
checks all Cookies and delete those which are expired
Returns:
boolean always return true private
Definition at line 892 of file class.soapclient.php.
References nusoap_base::debug().
Referenced by send().
nusoap_client::checkWSDL ()
check WSDL passed as an instance or pulled from an endpoint
private
Definition at line 7499 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::setError().
nusoap_client::checkWSDL ()
check WSDL passed as an instance or pulled from an endpoint
private
Definition at line 339 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::setError().
nusoap_client::checkWSDL ()
check WSDL passed as an instance or pulled from an endpoint
private
Definition at line 7497 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::setError().
nusoap_client::checkWSDL ()
check WSDL passed as an instance or pulled from an endpoint
private
Definition at line 339 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::setError().
Referenced by loadWSDL(), and nusoap_client().
nusoap_client::decodeUTF8 ($ bool)
Definition at line 8015 of file nusoap.php.
nusoap_client::decodeUTF8 ($ bool)
Definition at line 855 of file class.soapclient.php.
nusoap_client::decodeUTF8 ($ bool)
Definition at line 8013 of file nusoap.php.
nusoap_client::decodeUTF8 ($ bool)
Definition at line 855 of file class.soapclient.php.
nusoap_client::getCookies ()
gets all Cookies
Returns:
array with all internal cookies public
Definition at line 8042 of file nusoap.php.
nusoap_client::getCookies ()
gets all Cookies
Returns:
array with all internal cookies public
Definition at line 882 of file class.soapclient.php.
nusoap_client::getCookies ()
gets all Cookies
Returns:
array with all internal cookies public
Definition at line 8040 of file nusoap.php.
nusoap_client::getCookies ()
gets all Cookies
Returns:
array with all internal cookies public
Definition at line 882 of file class.soapclient.php.
nusoap_client::getDefaultRpcParams ()
gets the default RPC parameter setting. If true, default is that call params are like RPC even for document style. Each call() can override this value.
This is no longer used.
Returns:
boolean public
Deprecated:
Definition at line 7835 of file nusoap.php.
nusoap_client::getDefaultRpcParams ()
gets the default RPC parameter setting. If true, default is that call params are like RPC even for document style. Each call() can override this value.
This is no longer used.
Returns:
boolean public
Deprecated:
Definition at line 675 of file class.soapclient.php.
nusoap_client::getDefaultRpcParams ()
gets the default RPC parameter setting. If true, default is that call params are like RPC even for document style. Each call() can override this value.
This is no longer used.
Returns:
boolean public
Deprecated:
Definition at line 7833 of file nusoap.php.
nusoap_client::getDefaultRpcParams ()
gets the default RPC parameter setting. If true, default is that call params are like RPC even for document style. Each call() can override this value.
This is no longer used.
Returns:
boolean public
Deprecated:
Definition at line 675 of file class.soapclient.php.
nusoap_client::getHeader ()
get the SOAP response Header (parsed)
Returns:
mixed public
Definition at line 7754 of file nusoap.php.
nusoap_client::getHeader ()
get the SOAP response Header (parsed)
Returns:
mixed public
Definition at line 594 of file class.soapclient.php.
nusoap_client::getHeader ()
get the SOAP response Header (parsed)
Returns:
mixed public
Definition at line 7752 of file nusoap.php.
nusoap_client::getHeader ()
get the SOAP response Header (parsed)
Returns:
mixed public
Definition at line 594 of file class.soapclient.php.
nusoap_client::getHeaders ()
get the SOAP response headers (namespace resolution incomplete)
Returns:
string public
Definition at line 7744 of file nusoap.php.
nusoap_client::getHeaders ()
get the SOAP response headers (namespace resolution incomplete)
Returns:
string public
Definition at line 584 of file class.soapclient.php.
nusoap_client::getHeaders ()
get the SOAP response headers (namespace resolution incomplete)
Returns:
string public
Definition at line 7742 of file nusoap.php.
nusoap_client::getHeaders ()
get the SOAP response headers (namespace resolution incomplete)
Returns:
string public
Definition at line 584 of file class.soapclient.php.
nusoap_client::getHTTPBody ($ soapmsg)
gets the HTTP body for the current request.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 7980 of file nusoap.php.
nusoap_client::getHTTPBody ($ soapmsg)
gets the HTTP body for the current request.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 820 of file class.soapclient.php.
nusoap_client::getHTTPBody ($ soapmsg)
gets the HTTP body for the current request.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 7978 of file nusoap.php.
nusoap_client::getHTTPBody ($ soapmsg)
gets the HTTP body for the current request.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 820 of file class.soapclient.php.
Referenced by call().
nusoap_client::getHTTPContentType ()
gets the HTTP content type for the current request.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 7992 of file nusoap.php.
nusoap_client::getHTTPContentType ()
gets the HTTP content type for the current request.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 832 of file class.soapclient.php.
nusoap_client::getHTTPContentType ()
gets the HTTP content type for the current request.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 7990 of file nusoap.php.
nusoap_client::getHTTPContentType ()
gets the HTTP content type for the current request.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 832 of file class.soapclient.php.
Referenced by send().
nusoap_client::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current request. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 8005 of file nusoap.php.
nusoap_client::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current request. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 845 of file class.soapclient.php.
nusoap_client::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current request. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 8003 of file nusoap.php.
nusoap_client::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current request. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current request. private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 845 of file class.soapclient.php.
Referenced by send().
nusoap_client::getOperationData ($ operation)
get available data pertaining to an operation
Parameters:
string $operation operation name
Returns:
array array of data pertaining to the operation public
Definition at line 7548 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::getError(), and loadWSDL().
nusoap_client::getOperationData ($ operation)
get available data pertaining to an operation
Parameters:
string $operation operation name
Returns:
array array of data pertaining to the operation public
Definition at line 388 of file class.soapclient.php.
References nusoap_base::debug(), nusoap_base::getError(), and loadWSDL().
nusoap_client::getOperationData ($ operation)
get available data pertaining to an operation
Parameters:
string $operation operation name
Returns:
array array of data pertaining to the operation public
Definition at line 7546 of file nusoap.php.
References nusoap_base::debug(), nusoap_base::getError(), and loadWSDL().
nusoap_client::getOperationData ($ operation)
get available data pertaining to an operation
Parameters:
string $operation operation name
Returns:
array array of data pertaining to the operation public
Definition at line 388 of file class.soapclient.php.
References nusoap_base::debug(), nusoap_base::getError(), and loadWSDL().
Referenced by call().
nusoap_client::getProxy ()
dynamically creates an instance of a proxy class, allowing user to directly call methods from wsdl
Returns:
object soap_proxy object public
Definition at line 7861 of file nusoap.php.
References _getProxyClassCode(), nusoap_base::debug(), and nusoap_base::getError().
nusoap_client::getProxy ()
dynamically creates an instance of a proxy class, allowing user to directly call methods from wsdl
Returns:
object soap_proxy object public
Definition at line 701 of file class.soapclient.php.
References _getProxyClassCode(), nusoap_base::debug(), and nusoap_base::getError().
nusoap_client::getProxy ()
dynamically creates an instance of a proxy class, allowing user to directly call methods from wsdl
Returns:
object soap_proxy object public
Definition at line 7859 of file nusoap.php.
References _getProxyClassCode(), nusoap_base::debug(), and nusoap_base::getError().
nusoap_client::getProxy ()
dynamically creates an instance of a proxy class, allowing user to directly call methods from wsdl
Returns:
object soap_proxy object public
Definition at line 701 of file class.soapclient.php.
References _getProxyClassCode(), nusoap_base::debug(), and nusoap_base::getError().
nusoap_client::getProxyClassCode ()
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class public
Definition at line 7968 of file nusoap.php.
References _getProxyClassCode().
nusoap_client::getProxyClassCode ()
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class public
Definition at line 808 of file class.soapclient.php.
References _getProxyClassCode().
nusoap_client::getProxyClassCode ()
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class public
Definition at line 7966 of file nusoap.php.
References _getProxyClassCode().
nusoap_client::getProxyClassCode ()
dynamically creates proxy class code
Returns:
string PHP/NuSOAP code for the proxy class public
Definition at line 808 of file class.soapclient.php.
References _getProxyClassCode().
nusoap_client::loadWSDL ()
instantiate wsdl object and parse wsdl file
public
Definition at line 7533 of file nusoap.php.
References checkWSDL(), and nusoap_base::debug().
nusoap_client::loadWSDL ()
instantiate wsdl object and parse wsdl file
public
Definition at line 373 of file class.soapclient.php.
References checkWSDL(), and nusoap_base::debug().
nusoap_client::loadWSDL ()
instantiate wsdl object and parse wsdl file
public
Definition at line 7531 of file nusoap.php.
References checkWSDL(), and nusoap_base::debug().
nusoap_client::loadWSDL ()
instantiate wsdl object and parse wsdl file
public
Definition at line 373 of file class.soapclient.php.
References checkWSDL(), and nusoap_base::debug().
Referenced by _getProxyClassCode(), call(), and getOperationData().
nusoap_client::nusoap_client ($ endpoint, $ wsdl = false, $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ portName = '')
constructor
Parameters:
mixed $endpoint SOAP server or WSDL URL (string), or wsdl instance (object)
mixed $wsdl optional, set to 'wsdl' or true if using WSDL
string $proxyhost optional
string $proxyport optional
string $proxyusername optional
string $proxypassword optional
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
string $portName optional portName in WSDL document public
Definition at line 7258 of file nusoap.php.
References $endpoint, $portName, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $wsdl, nusoap_base::appendDebug(), checkWSDL(), nusoap_base::debug(), nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_client::nusoap_client ($ endpoint, $ wsdl = false, $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ portName = '')
constructor
Parameters:
mixed $endpoint SOAP server or WSDL URL (string), or wsdl instance (object)
mixed $wsdl optional, set to 'wsdl' or true if using WSDL
string $proxyhost optional
string $proxyport optional
string $proxyusername optional
string $proxypassword optional
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
string $portName optional portName in WSDL document public
Definition at line 98 of file class.soapclient.php.
References $endpoint, $portName, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $wsdl, nusoap_base::appendDebug(), checkWSDL(), nusoap_base::debug(), nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_client::nusoap_client ($ endpoint, $ wsdl = false, $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ portName = '')
constructor
Parameters:
mixed $endpoint SOAP server or WSDL URL (string), or wsdl instance (object)
mixed $wsdl optional, set to 'wsdl' or true if using WSDL
string $proxyhost optional
string $proxyport optional
string $proxyusername optional
string $proxypassword optional
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
string $portName optional portName in WSDL document public
Definition at line 7256 of file nusoap.php.
References $endpoint, $portName, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $wsdl, nusoap_base::appendDebug(), checkWSDL(), nusoap_base::debug(), nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_client::nusoap_client ($ endpoint, $ wsdl = false, $ proxyhost = false, $ proxyport = false, $ proxyusername = false, $ proxypassword = false, $ timeout = 0, $ response_timeout = 30, $ portName = '')
constructor
Parameters:
mixed $endpoint SOAP server or WSDL URL (string), or wsdl instance (object)
mixed $wsdl optional, set to 'wsdl' or true if using WSDL
string $proxyhost optional
string $proxyport optional
string $proxyusername optional
string $proxypassword optional
integer $timeout set the connection timeout
integer $response_timeout set the response timeout
string $portName optional portName in WSDL document public
Definition at line 98 of file class.soapclient.php.
References $endpoint, $portName, $proxyhost, $proxypassword, $proxyport, $proxyusername, $response_timeout, $timeout, $wsdl, nusoap_base::appendDebug(), checkWSDL(), nusoap_base::debug(), nusoap_base::nusoap_base(), and nusoap_base::varDump().
nusoap_client::parseResponse ($ headers, $ data)
processes SOAP message returned from server
Parameters:
array $headers The HTTP headers
string $data unprocessed response data from server
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 7653 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::parseResponse ($ headers, $ data)
processes SOAP message returned from server
Parameters:
array $headers The HTTP headers
string $data unprocessed response data from server
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 493 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::parseResponse ($ headers, $ data)
processes SOAP message returned from server
Parameters:
array $headers The HTTP headers
string $data unprocessed response data from server
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 7651 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::setError(), and nusoap_base::varDump().
nusoap_client::parseResponse ($ headers, $ data)
processes SOAP message returned from server
Parameters:
array $headers The HTTP headers
string $data unprocessed response data from server
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented in nusoap_client_mime, and nusoap_client_mime.
Definition at line 493 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), nusoap_base::setError(), and nusoap_base::varDump().
Referenced by send().
nusoap_client::send ($ msg, $ soapaction = '', $ timeout = 0, $ response_timeout = 30)
send the SOAP message
Note: if the operation has multiple return values the return value of this method will be an array of those values.
Parameters:
string $msg a SOAPx4 soapmsg object
string $soapaction SOAPAction value
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
mixed native PHP types. private
Definition at line 7574 of file nusoap.php.
References $err, $response_timeout, $timeout, nusoap_base::appendDebug(), checkCookies(), nusoap_base::debug(), nusoap_base::getError(), getHTTPContentType(), getHTTPContentTypeCharset(), parseResponse(), nusoap_base::setError(), and UpdateCookies().
nusoap_client::send ($ msg, $ soapaction = '', $ timeout = 0, $ response_timeout = 30)
send the SOAP message
Note: if the operation has multiple return values the return value of this method will be an array of those values.
Parameters:
string $msg a SOAPx4 soapmsg object
string $soapaction SOAPAction value
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
mixed native PHP types. private
Definition at line 414 of file class.soapclient.php.
References $err, $response_timeout, $timeout, nusoap_base::appendDebug(), checkCookies(), nusoap_base::debug(), nusoap_base::getError(), getHTTPContentType(), getHTTPContentTypeCharset(), parseResponse(), nusoap_base::setError(), and UpdateCookies().
nusoap_client::send ($ msg, $ soapaction = '', $ timeout = 0, $ response_timeout = 30)
send the SOAP message
Note: if the operation has multiple return values the return value of this method will be an array of those values.
Parameters:
string $msg a SOAPx4 soapmsg object
string $soapaction SOAPAction value
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
mixed native PHP types. private
Definition at line 7572 of file nusoap.php.
References $err, $response_timeout, $timeout, nusoap_base::appendDebug(), checkCookies(), nusoap_base::debug(), nusoap_base::getError(), getHTTPContentType(), getHTTPContentTypeCharset(), parseResponse(), nusoap_base::setError(), and UpdateCookies().
nusoap_client::send ($ msg, $ soapaction = '', $ timeout = 0, $ response_timeout = 30)
send the SOAP message
Note: if the operation has multiple return values the return value of this method will be an array of those values.
Parameters:
string $msg a SOAPx4 soapmsg object
string $soapaction SOAPAction value
integer $timeout set connection timeout in seconds
integer $response_timeout set response timeout in seconds
Returns:
mixed native PHP types. private
Definition at line 414 of file class.soapclient.php.
References $err, $response_timeout, $timeout, nusoap_base::appendDebug(), checkCookies(), nusoap_base::debug(), nusoap_base::getError(), getHTTPContentType(), getHTTPContentTypeCharset(), parseResponse(), nusoap_base::setError(), and UpdateCookies().
Referenced by call().
nusoap_client::setCookie ($ name, $ value)
adds a new Cookie into $this->cookies array
Parameters:
string $name Cookie Name
string $value Cookie Value
Returns:
boolean if cookie-set was successful returns true, else false public
Definition at line 8028 of file nusoap.php.
nusoap_client::setCookie ($ name, $ value)
adds a new Cookie into $this->cookies array
Parameters:
string $name Cookie Name
string $value Cookie Value
Returns:
boolean if cookie-set was successful returns true, else false public
Definition at line 868 of file class.soapclient.php.
nusoap_client::setCookie ($ name, $ value)
adds a new Cookie into $this->cookies array
Parameters:
string $name Cookie Name
string $value Cookie Value
Returns:
boolean if cookie-set was successful returns true, else false public
Definition at line 8026 of file nusoap.php.
nusoap_client::setCookie ($ name, $ value)
adds a new Cookie into $this->cookies array
Parameters:
string $name Cookie Name
string $value Cookie Value
Returns:
boolean if cookie-set was successful returns true, else false public
Definition at line 868 of file class.soapclient.php.
nusoap_client::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 7783 of file nusoap.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 623 of file class.soapclient.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 7781 of file nusoap.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setCredentials ($ username, $ password, $ authtype = 'basic', $ certRequest = array())
if authenticating, set user credentials here
Parameters:
string $username
string $password
string $authtype (basic|digest|certificate|ntlm)
array $certRequest (keys must be cainfofile (optional), sslcertfile, sslkeyfile, passphrase, verifypeer (optional), verifyhost (optional): see corresponding options in cURL docs) public
Definition at line 623 of file class.soapclient.php.
References $authtype, $certRequest, $password, $username, nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setCurlOption ($ option, $ value)
sets user-specified cURL options
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value public
Definition at line 7709 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setCurlOption ($ option, $ value)
sets user-specified cURL options
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value public
Definition at line 549 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setCurlOption ($ option, $ value)
sets user-specified cURL options
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value public
Definition at line 7707 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setCurlOption ($ option, $ value)
sets user-specified cURL options
Parameters:
mixed $option The cURL option (always integer?)
mixed $value The cURL option value public
Definition at line 549 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setDefaultRpcParams ($ rpcParams)
sets the default RPC parameter setting. If true, default is that call params are like RPC even for document style Each call() can override this value.
This is no longer used.
Parameters:
boolean $rpcParams public
Deprecated:
Definition at line 7850 of file nusoap.php.
nusoap_client::setDefaultRpcParams ($ rpcParams)
sets the default RPC parameter setting. If true, default is that call params are like RPC even for document style Each call() can override this value.
This is no longer used.
Parameters:
boolean $rpcParams public
Deprecated:
Definition at line 690 of file class.soapclient.php.
nusoap_client::setDefaultRpcParams ($ rpcParams)
sets the default RPC parameter setting. If true, default is that call params are like RPC even for document style Each call() can override this value.
This is no longer used.
Parameters:
boolean $rpcParams public
Deprecated:
Definition at line 7848 of file nusoap.php.
nusoap_client::setDefaultRpcParams ($ rpcParams)
sets the default RPC parameter setting. If true, default is that call params are like RPC even for document style Each call() can override this value.
This is no longer used.
Parameters:
boolean $rpcParams public
Deprecated:
Definition at line 690 of file class.soapclient.php.
nusoap_client::setEndpoint ($ endpoint)
sets the SOAP endpoint, which can override WSDL
Parameters:
string $endpoint The endpoint URL to use, or empty string or false to prevent override public
Definition at line 7721 of file nusoap.php.
References $endpoint, and nusoap_base::debug().
nusoap_client::setEndpoint ($ endpoint)
sets the SOAP endpoint, which can override WSDL
Parameters:
string $endpoint The endpoint URL to use, or empty string or false to prevent override public
Definition at line 561 of file class.soapclient.php.
References $endpoint, and nusoap_base::debug().
nusoap_client::setEndpoint ($ endpoint)
sets the SOAP endpoint, which can override WSDL
Parameters:
string $endpoint The endpoint URL to use, or empty string or false to prevent override public
Definition at line 7719 of file nusoap.php.
References $endpoint, and nusoap_base::debug().
nusoap_client::setEndpoint ($ endpoint)
sets the SOAP endpoint, which can override WSDL
Parameters:
string $endpoint The endpoint URL to use, or empty string or false to prevent override public
Definition at line 561 of file class.soapclient.php.
References $endpoint, and nusoap_base::debug().
nusoap_client::setHeaders ($ headers)
set the SOAP headers
Parameters:
mixed $headers String of XML with SOAP header content, or array of soapval objects for SOAP headers public
Definition at line 7732 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setHeaders ($ headers)
set the SOAP headers
Parameters:
mixed $headers String of XML with SOAP header content, or array of soapval objects for SOAP headers public
Definition at line 572 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setHeaders ($ headers)
set the SOAP headers
Parameters:
mixed $headers String of XML with SOAP header content, or array of soapval objects for SOAP headers public
Definition at line 7730 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setHeaders ($ headers)
set the SOAP headers
Parameters:
mixed $headers String of XML with SOAP header content, or array of soapval objects for SOAP headers public
Definition at line 572 of file class.soapclient.php.
References nusoap_base::appendDebug(), nusoap_base::debug(), and nusoap_base::varDump().
nusoap_client::setHTTPEncoding ($ enc = 'gzip, deflate')
use HTTP encoding
Parameters:
string $enc HTTP encoding public
Definition at line 7798 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::setHTTPEncoding ($ enc = 'gzip, deflate')
use HTTP encoding
Parameters:
string $enc HTTP encoding public
Definition at line 638 of file class.soapclient.php.
References nusoap_base::debug().
nusoap_client::setHTTPEncoding ($ enc = 'gzip, deflate')
use HTTP encoding
Parameters:
string $enc HTTP encoding public
Definition at line 7796 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::setHTTPEncoding ($ enc = 'gzip, deflate')
use HTTP encoding
Parameters:
string $enc HTTP encoding public
Definition at line 638 of file class.soapclient.php.
References nusoap_base::debug().
nusoap_client::setHTTPProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '')
set proxy info here
Parameters:
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword public
Definition at line 7767 of file nusoap.php.
References $proxyhost, $proxypassword, $proxyport, and $proxyusername.
nusoap_client::setHTTPProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '')
set proxy info here
Parameters:
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword public
Definition at line 607 of file class.soapclient.php.
References $proxyhost, $proxypassword, $proxyport, and $proxyusername.
nusoap_client::setHTTPProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '')
set proxy info here
Parameters:
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword public
Definition at line 7765 of file nusoap.php.
References $proxyhost, $proxypassword, $proxyport, and $proxyusername.
nusoap_client::setHTTPProxy ($ proxyhost, $ proxyport, $ proxyusername = '', $ proxypassword = '')
set proxy info here
Parameters:
string $proxyhost
string $proxyport
string $proxyusername
string $proxypassword public
Definition at line 607 of file class.soapclient.php.
References $proxyhost, $proxypassword, $proxyport, and $proxyusername.
nusoap_client::setUseCURL ($ use)
Set whether to try to use cURL connections if possible
Parameters:
boolean $use Whether to try to use cURL public
Definition at line 7809 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::setUseCURL ($ use)
Set whether to try to use cURL connections if possible
Parameters:
boolean $use Whether to try to use cURL public
Definition at line 649 of file class.soapclient.php.
References nusoap_base::debug().
nusoap_client::setUseCURL ($ use)
Set whether to try to use cURL connections if possible
Parameters:
boolean $use Whether to try to use cURL public
Definition at line 7807 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::setUseCURL ($ use)
Set whether to try to use cURL connections if possible
Parameters:
boolean $use Whether to try to use cURL public
Definition at line 649 of file class.soapclient.php.
References nusoap_base::debug().
nusoap_client::UpdateCookies ($ cookies)
updates the current cookies with a new set
Parameters:
array $cookies new cookies with which to update current ones
Returns:
boolean always return true private
Definition at line 8085 of file nusoap.php.
References $cookies, $i, and nusoap_base::debug().
nusoap_client::UpdateCookies ($ cookies)
updates the current cookies with a new set
Parameters:
array $cookies new cookies with which to update current ones
Returns:
boolean always return true private
Definition at line 925 of file class.soapclient.php.
References $cookies, $i, and nusoap_base::debug().
nusoap_client::UpdateCookies ($ cookies)
updates the current cookies with a new set
Parameters:
array $cookies new cookies with which to update current ones
Returns:
boolean always return true private
Definition at line 8083 of file nusoap.php.
References $cookies, $i, and nusoap_base::debug().
nusoap_client::UpdateCookies ($ cookies)
updates the current cookies with a new set
Parameters:
array $cookies new cookies with which to update current ones
Returns:
boolean always return true private
Definition at line 925 of file class.soapclient.php.
References $cookies, $i, and nusoap_base::debug().
Referenced by send().
nusoap_client::useHTTPPersistentConnection ()
use HTTP persistent connections if possible
public
Definition at line 7819 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::useHTTPPersistentConnection ()
use HTTP persistent connections if possible
public
Definition at line 659 of file class.soapclient.php.
References nusoap_base::debug().
nusoap_client::useHTTPPersistentConnection ()
use HTTP persistent connections if possible
public
Definition at line 7817 of file nusoap.php.
References nusoap_base::debug().
nusoap_client::useHTTPPersistentConnection ()
use HTTP persistent connections if possible
public
Definition at line 659 of file class.soapclient.php.
References nusoap_base::debug().
Member Data Documentation
nusoap_client::$authtype = ''
Definition at line 30 of file class.soapclient.php.
Referenced by setCredentials().
nusoap_client::$bindingType = ''
Definition at line 57 of file class.soapclient.php.
nusoap_client::$certRequest = array()
Definition at line 31 of file class.soapclient.php.
Referenced by setCredentials().
nusoap_client::$cookies = array()
Definition at line 53 of file class.soapclient.php.
Referenced by UpdateCookies().
nusoap_client::$curl_options = array()
Definition at line 56 of file class.soapclient.php.
nusoap_client::$decode_utf8 = true
Definition at line 54 of file class.soapclient.php.
nusoap_client::$defaultRpcParams = false
Definition at line 49 of file class.soapclient.php.
nusoap_client::$document = ''
Definition at line 35 of file class.soapclient.php.
nusoap_client::$endpoint
Definition at line 36 of file class.soapclient.php.
Referenced by nusoap_client(), and setEndpoint().
nusoap_client::$endpointType = ''
Definition at line 47 of file class.soapclient.php.
nusoap_client::$fault
Definition at line 67 of file class.soapclient.php.
nusoap_client::$faultcode
Definition at line 72 of file class.soapclient.php.
nusoap_client::$faultdetail
Definition at line 82 of file class.soapclient.php.
nusoap_client::$faultstring
Definition at line 77 of file class.soapclient.php.
nusoap_client::$forceEndpoint = ''
Definition at line 37 of file class.soapclient.php.
nusoap_client::$http_encoding = false
Definition at line 44 of file class.soapclient.php.
nusoap_client::$operations = array()
Definition at line 55 of file class.soapclient.php.
nusoap_client::$password = ''
Definition at line 29 of file class.soapclient.php.
Referenced by setCredentials().
nusoap_client::$persistentConnection = false
Definition at line 48 of file class.soapclient.php.
nusoap_client::$portName = ''
Definition at line 42 of file class.soapclient.php.
Referenced by nusoap_client().
nusoap_client::$proxyhost = ''
Definition at line 38 of file class.soapclient.php.
Referenced by nusoap_client(), and setHTTPProxy().
nusoap_client::$proxypassword = ''
Definition at line 41 of file class.soapclient.php.
Referenced by nusoap_client(), and setHTTPProxy().
nusoap_client::$proxyport = ''
Definition at line 39 of file class.soapclient.php.
Referenced by nusoap_client(), and setHTTPProxy().
nusoap_client::$proxyusername = ''
Definition at line 40 of file class.soapclient.php.
Referenced by nusoap_client(), and setHTTPProxy().
nusoap_client::$request = ''
Definition at line 50 of file class.soapclient.php.
nusoap_client::$requestHeaders = false
Definition at line 32 of file class.soapclient.php.
nusoap_client::$response = ''
Definition at line 51 of file class.soapclient.php.
nusoap_client::$response_timeout = 30
Definition at line 46 of file class.soapclient.php.
Referenced by nusoap_client(), and send().
nusoap_client::$responseData = ''
Definition at line 52 of file class.soapclient.php.
nusoap_client::$responseHeader = NULL
Definition at line 34 of file class.soapclient.php.
nusoap_client::$responseHeaders = ''
Definition at line 33 of file class.soapclient.php.
nusoap_client::$timeout = 0
Definition at line 45 of file class.soapclient.php.
Referenced by nusoap_client(), and send().
nusoap_client::$use_curl = false
Definition at line 58 of file class.soapclient.php.
nusoap_client::$username = ''
Definition at line 28 of file class.soapclient.php.
Referenced by setCredentials().
nusoap_client::$xml_encoding = ''
Definition at line 43 of file class.soapclient.php.
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.soapclient.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.soapclient.php
modules/soap_server/nusoap/lib/nusoap.php