DAEDrupalInterface: DatasetPageImageBrowser Class Reference
DatasetPageImageBrowser Class Reference
Public Member Functions
__construct (&$info)
build_dataset_page (&$info)
list_builder_datasets (&$array, &$dataset_names, &$i)
getOutput ()
Public Attributes
$output
Detailed Description
Definition at line 375 of file dae_ui.module.
Member Function Documentation
DatasetPageImageBrowser::__construct (&$ info)
Definition at line 379 of file dae_ui.module.
References build_dataset_page().
DatasetPageImageBrowser::build_dataset_page (&$ info)
Definition at line 383 of file dae_ui.module.
References $db, getDAEDatabase(), and list_builder_datasets().
Referenced by __construct().
DatasetPageImageBrowser::getOutput ()
Definition at line 466 of file dae_ui.module.
DatasetPageImageBrowser::list_builder_datasets (&$ array, &$ dataset_names, &$ i)
Definition at line 444 of file dae_ui.module.
Referenced by build_dataset_page().
Member Data Documentation
DatasetPageImageBrowser::$output
Definition at line 377 of file dae_ui.module.
The documentation for this class was generated from the following file:
modules/dae_ui/dae_ui.module