DAEDrupalInterface: nusoap_xmlschema Class Reference
nusoap_xmlschema Class Reference
Public Member Functions
nusoap_xmlschema ($schema='', $xml='', $namespaces=array())
parseFile ($xml, $type)
parseString ($xml, $type)
CreateTypeName ($ename)
schemaStartElement ($parser, $name, $attrs)
schemaEndElement ($parser, $name)
schemaCharacterData ($parser, $data)
serializeSchema ()
xdebug ($string)
getPHPType ($type, $ns)
getTypeDef ($type)
serializeTypeDef ($type)
typeToForm ($name, $type)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
nusoap_xmlschema ($schema='', $xml='', $namespaces=array())
parseFile ($xml, $type)
parseString ($xml, $type)
CreateTypeName ($ename)
schemaStartElement ($parser, $name, $attrs)
schemaEndElement ($parser, $name)
schemaCharacterData ($parser, $data)
serializeSchema ()
xdebug ($string)
getPHPType ($type, $ns)
getTypeDef ($type)
serializeTypeDef ($type)
typeToForm ($name, $type)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
nusoap_xmlschema ($schema='', $xml='', $namespaces=array())
parseFile ($xml, $type)
parseString ($xml, $type)
CreateTypeName ($ename)
schemaStartElement ($parser, $name, $attrs)
schemaEndElement ($parser, $name)
schemaCharacterData ($parser, $data)
serializeSchema ()
xdebug ($string)
getPHPType ($type, $ns)
getTypeDef ($type)
serializeTypeDef ($type)
typeToForm ($name, $type)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
nusoap_xmlschema ($schema='', $xml='', $namespaces=array())
parseFile ($xml, $type)
parseString ($xml, $type)
CreateTypeName ($ename)
schemaStartElement ($parser, $name, $attrs)
schemaEndElement ($parser, $name)
schemaCharacterData ($parser, $data)
serializeSchema ()
xdebug ($string)
getPHPType ($type, $ns)
getTypeDef ($type)
serializeTypeDef ($type)
typeToForm ($name, $type)
addComplexType ($name, $typeClass='complexType', $phpType='array', $compositor='', $restrictionBase='', $elements=array(), $attrs=array(), $arrayType='')
addSimpleType ($name, $restrictionBase='', $typeClass='simpleType', $phpType='scalar', $enumeration=array())
addElement ($attrs)
Public Attributes
$schema = ''
$xml = ''
$enclosingNamespaces
$schemaInfo = array()
$schemaTargetNamespace = ''
$attributes = array()
$complexTypes = array()
$complexTypeStack = array()
$currentComplexType = null
$elements = array()
$elementStack = array()
$currentElement = null
$simpleTypes = array()
$simpleTypeStack = array()
$currentSimpleType = null
$imports = array()
$parser
$position = 0
$depth = 0
$depth_array = array()
$message = array()
$defaultNamespace = array()
Detailed Description
parses an XML Schema, allows access to it's data, other utility methods. imperfect, no validation... yet, but quite functional.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
class.xmlschema.php,v 1.53 2010/04/26 20:15:08 snichol Exp
public
parses an XML Schema, allows access to it's data, other utility methods. imperfect, no validation... yet, but quite functional.
Author:
Dietrich Ayala <dietrich@ganx4.com>
Scott Nichol <snichol@users.sourceforge.net>
Version:
Id
nusoap.php,v 1.123 2010/04/26 20:15:08 snichol Exp
public
Definition at line 15 of file class.xmlschema.php.
Member Function Documentation
nusoap_xmlschema::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds a complex type to the schema
example: array
addType('ArrayOfstring', 'complexType', 'array', '', 'SOAP-ENC:Array', array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'string[]'), 'xsd:string');
example: PHP associative array (SOAP Struct)
addType('SOAPStruct', 'complexType', 'struct', 'all', array('myVar'=> array('name'=>'myVar','type'=>'string'));
Parameters:
name
typeClass (complexType|simpleType|attribute)
phpType,: currently supported are array and struct (php assoc array)
compositor (all|sequence|choice)
restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
elements = array (name = array(name=>'',type=>''))
attrs = array(array('ref' => "http://schemas.xmlsoap.org/soap/encoding/:arrayType", "http://schemas.xmlsoap.org/wsdl/:arrayType" => "string[]"))
arrayType,: namespace:name (http://www.w3.org/2001/XMLSchema:string) public
See also:
getTypeDef
Definition at line 1986 of file nusoap.php.
References $elements, nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds a complex type to the schema
example: array
addType('ArrayOfstring', 'complexType', 'array', '', 'SOAP-ENC:Array', array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'string[]'), 'xsd:string');
example: PHP associative array (SOAP Struct)
addType('SOAPStruct', 'complexType', 'struct', 'all', array('myVar'=> array('name'=>'myVar','type'=>'string'));
Parameters:
name
typeClass (complexType|simpleType|attribute)
phpType,: currently supported are array and struct (php assoc array)
compositor (all|sequence|choice)
restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
elements = array (name = array(name=>'',type=>''))
attrs = array(array('ref' => "http://schemas.xmlsoap.org/soap/encoding/:arrayType", "http://schemas.xmlsoap.org/wsdl/:arrayType" => "string[]"))
arrayType,: namespace:name (http://www.w3.org/2001/XMLSchema:string) public
See also:
getTypeDef
Definition at line 906 of file class.xmlschema.php.
References $elements, nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds a complex type to the schema
example: array
addType('ArrayOfstring', 'complexType', 'array', '', 'SOAP-ENC:Array', array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'string[]'), 'xsd:string');
example: PHP associative array (SOAP Struct)
addType('SOAPStruct', 'complexType', 'struct', 'all', array('myVar'=> array('name'=>'myVar','type'=>'string'));
Parameters:
name
typeClass (complexType|simpleType|attribute)
phpType,: currently supported are array and struct (php assoc array)
compositor (all|sequence|choice)
restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
elements = array (name = array(name=>'',type=>''))
attrs = array(array('ref' => "http://schemas.xmlsoap.org/soap/encoding/:arrayType", "http://schemas.xmlsoap.org/wsdl/:arrayType" => "string[]"))
arrayType,: namespace:name (http://www.w3.org/2001/XMLSchema:string) public
See also:
getTypeDef
Definition at line 1986 of file nusoap.php.
References $elements, nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addComplexType ($ name, $ typeClass = 'complexType', $ phpType = 'array', $ compositor = '', $ restrictionBase = '', $ elements = array(), $ attrs = array(), $ arrayType = '')
adds a complex type to the schema
example: array
addType('ArrayOfstring', 'complexType', 'array', '', 'SOAP-ENC:Array', array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'string[]'), 'xsd:string');
example: PHP associative array (SOAP Struct)
addType('SOAPStruct', 'complexType', 'struct', 'all', array('myVar'=> array('name'=>'myVar','type'=>'string'));
Parameters:
name
typeClass (complexType|simpleType|attribute)
phpType,: currently supported are array and struct (php assoc array)
compositor (all|sequence|choice)
restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
elements = array (name = array(name=>'',type=>''))
attrs = array(array('ref' => "http://schemas.xmlsoap.org/soap/encoding/:arrayType", "http://schemas.xmlsoap.org/wsdl/:arrayType" => "string[]"))
arrayType,: namespace:name (http://www.w3.org/2001/XMLSchema:string) public
See also:
getTypeDef
Definition at line 906 of file class.xmlschema.php.
References $elements, nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addElement ($ attrs)
adds an element to the schema
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 2034 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addElement ($ attrs)
adds an element to the schema
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 954 of file class.xmlschema.php.
References nusoap_base::appendDebug(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addElement ($ attrs)
adds an element to the schema
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 2034 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addElement ($ attrs)
adds an element to the schema
Parameters:
array $attrs attributes that must include name and type
See also:
nusoap_xmlschema public
Definition at line 954 of file class.xmlschema.php.
References nusoap_base::appendDebug(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds a simple type to the schema
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values public
See also:
nusoap_xmlschema
getTypeDef
Definition at line 2014 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds a simple type to the schema
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values public
See also:
nusoap_xmlschema
getTypeDef
Definition at line 934 of file class.xmlschema.php.
References nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds a simple type to the schema
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values public
See also:
nusoap_xmlschema
getTypeDef
Definition at line 2014 of file nusoap.php.
References nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::addSimpleType ($ name, $ restrictionBase = '', $ typeClass = 'simpleType', $ phpType = 'scalar', $ enumeration = array())
adds a simple type to the schema
Parameters:
string $name
string $restrictionBase namespace:name (http://schemas.xmlsoap.org/soap/encoding/:Array)
string $typeClass (should always be simpleType)
string $phpType (should always be scalar)
array $enumeration array of values public
See also:
nusoap_xmlschema
getTypeDef
Definition at line 934 of file class.xmlschema.php.
References nusoap_base::appendDebug(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::CreateTypeName ($ ename)
gets a type name for an unnamed type
Parameters:
string Element name
Returns:
string A type name for an unnamed type private
Definition at line 1240 of file nusoap.php.
References $i.
nusoap_xmlschema::CreateTypeName ($ ename)
gets a type name for an unnamed type
Parameters:
string Element name
Returns:
string A type name for an unnamed type private
Definition at line 160 of file class.xmlschema.php.
References $i.
nusoap_xmlschema::CreateTypeName ($ ename)
gets a type name for an unnamed type
Parameters:
string Element name
Returns:
string A type name for an unnamed type private
Definition at line 1240 of file nusoap.php.
References $i.
nusoap_xmlschema::CreateTypeName ($ ename)
gets a type name for an unnamed type
Parameters:
string Element name
Returns:
string A type name for an unnamed type private
Definition at line 160 of file class.xmlschema.php.
References $i.
Referenced by schemaStartElement().
nusoap_xmlschema::getPHPType ($ type, $ ns)
get the PHP type of a user defined type in the schema PHP type is kind of a misnomer since it actually returns 'struct' for assoc. arrays returns false if no type exists, or not w/ the given namespace else returns a string that is either a native php type, or 'struct'
Parameters:
string $type name of defined type
string $ns namespace of type
Returns:
mixed public
Deprecated:
Definition at line 1766 of file nusoap.php.
nusoap_xmlschema::getPHPType ($ type, $ ns)
get the PHP type of a user defined type in the schema PHP type is kind of a misnomer since it actually returns 'struct' for assoc. arrays returns false if no type exists, or not w/ the given namespace else returns a string that is either a native php type, or 'struct'
Parameters:
string $type name of defined type
string $ns namespace of type
Returns:
mixed public
Deprecated:
Definition at line 686 of file class.xmlschema.php.
nusoap_xmlschema::getPHPType ($ type, $ ns)
get the PHP type of a user defined type in the schema PHP type is kind of a misnomer since it actually returns 'struct' for assoc. arrays returns false if no type exists, or not w/ the given namespace else returns a string that is either a native php type, or 'struct'
Parameters:
string $type name of defined type
string $ns namespace of type
Returns:
mixed public
Deprecated:
Definition at line 1766 of file nusoap.php.
nusoap_xmlschema::getPHPType ($ type, $ ns)
get the PHP type of a user defined type in the schema PHP type is kind of a misnomer since it actually returns 'struct' for assoc. arrays returns false if no type exists, or not w/ the given namespace else returns a string that is either a native php type, or 'struct'
Parameters:
string $type name of defined type
string $ns namespace of type
Returns:
mixed public
Deprecated:
Definition at line 686 of file class.xmlschema.php.
nusoap_xmlschema::getTypeDef ($ type)
returns an associative array of information about a given type returns false if no type exists by the given name
For a complexType typeDef = array('restrictionBase' => '', 'phpType' => '', 'compositor' => '(sequence|all)', 'elements' => array(), // refs to elements array 'attrs' => array() // refs to attributes array ... and so on (see addComplexType))
For simpleType or element, the array has different keys.
Parameters:
string $type
Returns:
mixed public
See also:
addComplexType
addSimpleType
addElement
Definition at line 1799 of file nusoap.php.
References getTypeDef(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::getTypeDef ($ type)
returns an associative array of information about a given type returns false if no type exists by the given name
For a complexType typeDef = array('restrictionBase' => '', 'phpType' => '', 'compositor' => '(sequence|all)', 'elements' => array(), // refs to elements array 'attrs' => array() // refs to attributes array ... and so on (see addComplexType))
For simpleType or element, the array has different keys.
Parameters:
string $type
Returns:
mixed public
See also:
addComplexType
addSimpleType
addElement
Definition at line 719 of file class.xmlschema.php.
References getTypeDef(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::getTypeDef ($ type)
returns an associative array of information about a given type returns false if no type exists by the given name
For a complexType typeDef = array('restrictionBase' => '', 'phpType' => '', 'compositor' => '(sequence|all)', 'elements' => array(), // refs to elements array 'attrs' => array() // refs to attributes array ... and so on (see addComplexType))
For simpleType or element, the array has different keys.
Parameters:
string $type
Returns:
mixed public
See also:
addComplexType
addSimpleType
addElement
Definition at line 1799 of file nusoap.php.
References getTypeDef(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::getTypeDef ($ type)
returns an associative array of information about a given type returns false if no type exists by the given name
For a complexType typeDef = array('restrictionBase' => '', 'phpType' => '', 'compositor' => '(sequence|all)', 'elements' => array(), // refs to elements array 'attrs' => array() // refs to attributes array ... and so on (see addComplexType))
For simpleType or element, the array has different keys.
Parameters:
string $type
Returns:
mixed public
See also:
addComplexType
addSimpleType
addElement
Definition at line 719 of file class.xmlschema.php.
References nusoap_base::varDump(), and xdebug().
Referenced by getTypeDef(), serializeTypeDef(), and typeToForm().
nusoap_xmlschema::nusoap_xmlschema ($ schema = '', $ xml = '', $ namespaces = array())
constructor
Parameters:
string $schema schema document URI
string $xml xml document URI
string $namespaces namespaces defined in enclosing XML public
Definition at line 1134 of file nusoap.php.
References nusoap_base::$namespaces, $schema, $xml, nusoap_base::debug(), nusoap_base::nusoap_base(), and parseFile().
nusoap_xmlschema::nusoap_xmlschema ($ schema = '', $ xml = '', $ namespaces = array())
constructor
Parameters:
string $schema schema document URI
string $xml xml document URI
string $namespaces namespaces defined in enclosing XML public
Definition at line 54 of file class.xmlschema.php.
References nusoap_base::$namespaces, $schema, $xml, nusoap_base::debug(), nusoap_base::nusoap_base(), and parseFile().
nusoap_xmlschema::nusoap_xmlschema ($ schema = '', $ xml = '', $ namespaces = array())
constructor
Parameters:
string $schema schema document URI
string $xml xml document URI
string $namespaces namespaces defined in enclosing XML public
Definition at line 1134 of file nusoap.php.
References nusoap_base::$namespaces, $schema, $xml, nusoap_base::debug(), nusoap_base::nusoap_base(), and parseFile().
nusoap_xmlschema::nusoap_xmlschema ($ schema = '', $ xml = '', $ namespaces = array())
constructor
Parameters:
string $schema schema document URI
string $xml xml document URI
string $namespaces namespaces defined in enclosing XML public
Definition at line 54 of file class.xmlschema.php.
References nusoap_base::$namespaces, $schema, $xml, nusoap_base::debug(), nusoap_base::nusoap_base(), and parseFile().
nusoap_xmlschema::parseFile ($ xml, $ type)
parse an XML file
Parameters:
string $xml path/URL to XML file
string $type (schema | xml)
Returns:
boolean public
Definition at line 1167 of file nusoap.php.
References $xml, nusoap_base::debug(), parseString(), and nusoap_base::setError().
nusoap_xmlschema::parseFile ($ xml, $ type)
parse an XML file
Parameters:
string $xml path/URL to XML file
string $type (schema | xml)
Returns:
boolean public
Definition at line 87 of file class.xmlschema.php.
References $xml, nusoap_base::debug(), parseString(), and nusoap_base::setError().
nusoap_xmlschema::parseFile ($ xml, $ type)
parse an XML file
Parameters:
string $xml path/URL to XML file
string $type (schema | xml)
Returns:
boolean public
Definition at line 1167 of file nusoap.php.
References $xml, nusoap_base::debug(), parseString(), and nusoap_base::setError().
nusoap_xmlschema::parseFile ($ xml, $ type)
parse an XML file
Parameters:
string $xml path/URL to XML file
string $type (schema | xml)
Returns:
boolean public
Definition at line 87 of file class.xmlschema.php.
References $xml, nusoap_base::debug(), parseString(), and nusoap_base::setError().
Referenced by nusoap_xmlschema().
nusoap_xmlschema::parseString ($ xml, $ type)
parse an XML string
Parameters:
string $xml path or URL
string $type (schema|xml) private
Definition at line 1193 of file nusoap.php.
References $xml, nusoap_base::debug(), and nusoap_base::setError().
nusoap_xmlschema::parseString ($ xml, $ type)
parse an XML string
Parameters:
string $xml path or URL
string $type (schema|xml) private
Definition at line 113 of file class.xmlschema.php.
References $xml, nusoap_base::debug(), and nusoap_base::setError().
nusoap_xmlschema::parseString ($ xml, $ type)
parse an XML string
Parameters:
string $xml path or URL
string $type (schema|xml) private
Definition at line 1193 of file nusoap.php.
References $xml, nusoap_base::debug(), and nusoap_base::setError().
nusoap_xmlschema::parseString ($ xml, $ type)
parse an XML string
Parameters:
string $xml path or URL
string $type (schema|xml) private
Definition at line 113 of file class.xmlschema.php.
References $xml, nusoap_base::debug(), and nusoap_base::setError().
Referenced by parseFile().
nusoap_xmlschema::schemaCharacterData ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 1622 of file nusoap.php.
nusoap_xmlschema::schemaCharacterData ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 542 of file class.xmlschema.php.
nusoap_xmlschema::schemaCharacterData ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 1622 of file nusoap.php.
nusoap_xmlschema::schemaCharacterData ($ parser, $ data)
element content handler
Parameters:
string $parser XML parser object
string $data element content private
Definition at line 542 of file class.xmlschema.php.
nusoap_xmlschema::schemaEndElement ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 1583 of file nusoap.php.
References nusoap_base::getLocalPart(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::schemaEndElement ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 503 of file class.xmlschema.php.
References nusoap_base::getLocalPart(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::schemaEndElement ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 1583 of file nusoap.php.
References nusoap_base::getLocalPart(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::schemaEndElement ($ parser, $ name)
end-element handler
Parameters:
string $parser XML parser object
string $name element name private
Definition at line 503 of file class.xmlschema.php.
References nusoap_base::getLocalPart(), nusoap_base::getPrefix(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::schemaStartElement ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 1256 of file nusoap.php.
References $depth, nusoap_base::appendDebug(), CreateTypeName(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::schemaStartElement ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 176 of file class.xmlschema.php.
References $depth, nusoap_base::appendDebug(), CreateTypeName(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::schemaStartElement ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 1256 of file nusoap.php.
References $depth, nusoap_base::appendDebug(), CreateTypeName(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::schemaStartElement ($ parser, $ name, $ attrs)
start-element handler
Parameters:
string $parser XML parser object
string $name element name
string $attrs associative array of attributes private
Definition at line 176 of file class.xmlschema.php.
References $depth, nusoap_base::appendDebug(), CreateTypeName(), nusoap_base::expandQname(), nusoap_base::getLocalPart(), nusoap_base::getNamespaceFromPrefix(), nusoap_base::getPrefix(), nusoap_base::getPrefixFromNamespace(), nusoap_base::varDump(), and xdebug().
nusoap_xmlschema::serializeSchema ()
serialize the schema
public
Definition at line 1632 of file nusoap.php.
References $xml, and nusoap_base::getPrefixFromNamespace().
nusoap_xmlschema::serializeSchema ()
serialize the schema
public
Definition at line 552 of file class.xmlschema.php.
References $xml, and nusoap_base::getPrefixFromNamespace().
nusoap_xmlschema::serializeSchema ()
serialize the schema
public
Definition at line 1632 of file nusoap.php.
References $xml, and nusoap_base::getPrefixFromNamespace().
nusoap_xmlschema::serializeSchema ()
serialize the schema
public
Definition at line 552 of file class.xmlschema.php.
References $xml, and nusoap_base::getPrefixFromNamespace().
nusoap_xmlschema::serializeTypeDef ($ type)
returns a sample serialization of a given type, or false if no type by the given name
Parameters:
string $type name of type
Returns:
mixed public
Deprecated:
Definition at line 1878 of file nusoap.php.
References getTypeDef(), and serializeTypeDef().
nusoap_xmlschema::serializeTypeDef ($ type)
returns a sample serialization of a given type, or false if no type by the given name
Parameters:
string $type name of type
Returns:
mixed public
Deprecated:
Definition at line 798 of file class.xmlschema.php.
References getTypeDef(), and serializeTypeDef().
nusoap_xmlschema::serializeTypeDef ($ type)
returns a sample serialization of a given type, or false if no type by the given name
Parameters:
string $type name of type
Returns:
mixed public
Deprecated:
Definition at line 1878 of file nusoap.php.
References getTypeDef(), and serializeTypeDef().
nusoap_xmlschema::serializeTypeDef ($ type)
returns a sample serialization of a given type, or false if no type by the given name
Parameters:
string $type name of type
Returns:
mixed public
Deprecated:
Definition at line 798 of file class.xmlschema.php.
References getTypeDef().
Referenced by serializeTypeDef().
nusoap_xmlschema::typeToForm ($ name, $ type)
returns HTML form elements that allow a user to enter values for creating an instance of the given type.
Parameters:
string $name name for type instance
string $type name of type
Returns:
string public
Deprecated:
Definition at line 1914 of file nusoap.php.
References $i, and getTypeDef().
nusoap_xmlschema::typeToForm ($ name, $ type)
returns HTML form elements that allow a user to enter values for creating an instance of the given type.
Parameters:
string $name name for type instance
string $type name of type
Returns:
string public
Deprecated:
Definition at line 834 of file class.xmlschema.php.
References $i, and getTypeDef().
nusoap_xmlschema::typeToForm ($ name, $ type)
returns HTML form elements that allow a user to enter values for creating an instance of the given type.
Parameters:
string $name name for type instance
string $type name of type
Returns:
string public
Deprecated:
Definition at line 1914 of file nusoap.php.
References $i, and getTypeDef().
nusoap_xmlschema::typeToForm ($ name, $ type)
returns HTML form elements that allow a user to enter values for creating an instance of the given type.
Parameters:
string $name name for type instance
string $type name of type
Returns:
string public
Deprecated:
Definition at line 834 of file class.xmlschema.php.
References $i, and getTypeDef().
nusoap_xmlschema::xdebug ($ string)
adds debug data to the clas level debug string
Parameters:
string $string debug data private
Definition at line 1750 of file nusoap.php.
References nusoap_base::debug().
nusoap_xmlschema::xdebug ($ string)
adds debug data to the clas level debug string
Parameters:
string $string debug data private
Definition at line 670 of file class.xmlschema.php.
References nusoap_base::debug().
nusoap_xmlschema::xdebug ($ string)
adds debug data to the clas level debug string
Parameters:
string $string debug data private
Definition at line 1750 of file nusoap.php.
References nusoap_base::debug().
nusoap_xmlschema::xdebug ($ string)
adds debug data to the clas level debug string
Parameters:
string $string debug data private
Definition at line 670 of file class.xmlschema.php.
References nusoap_base::debug().
Referenced by addComplexType(), addElement(), addSimpleType(), getTypeDef(), schemaEndElement(), and schemaStartElement().
Member Data Documentation
nusoap_xmlschema::$attributes = array()
Definition at line 26 of file class.xmlschema.php.
nusoap_xmlschema::$complexTypes = array()
Definition at line 27 of file class.xmlschema.php.
nusoap_xmlschema::$complexTypeStack = array()
Definition at line 28 of file class.xmlschema.php.
nusoap_xmlschema::$currentComplexType = null
Definition at line 29 of file class.xmlschema.php.
nusoap_xmlschema::$currentElement = null
Definition at line 32 of file class.xmlschema.php.
nusoap_xmlschema::$currentSimpleType = null
Definition at line 35 of file class.xmlschema.php.
nusoap_xmlschema::$defaultNamespace = array()
Definition at line 44 of file class.xmlschema.php.
nusoap_xmlschema::$depth = 0
Definition at line 41 of file class.xmlschema.php.
Referenced by schemaStartElement().
nusoap_xmlschema::$depth_array = array()
Definition at line 42 of file class.xmlschema.php.
nusoap_xmlschema::$elements = array()
Definition at line 30 of file class.xmlschema.php.
Referenced by addComplexType().
nusoap_xmlschema::$elementStack = array()
Definition at line 31 of file class.xmlschema.php.
nusoap_xmlschema::$enclosingNamespaces
Definition at line 21 of file class.xmlschema.php.
nusoap_xmlschema::$imports = array()
Definition at line 37 of file class.xmlschema.php.
nusoap_xmlschema::$message = array()
Definition at line 43 of file class.xmlschema.php.
nusoap_xmlschema::$parser
Definition at line 39 of file class.xmlschema.php.
nusoap_xmlschema::$position = 0
Definition at line 40 of file class.xmlschema.php.
nusoap_xmlschema::$schema = ''
Definition at line 18 of file class.xmlschema.php.
Referenced by nusoap_xmlschema().
nusoap_xmlschema::$schemaInfo = array()
Definition at line 23 of file class.xmlschema.php.
nusoap_xmlschema::$schemaTargetNamespace = ''
Definition at line 24 of file class.xmlschema.php.
nusoap_xmlschema::$simpleTypes = array()
Definition at line 33 of file class.xmlschema.php.
nusoap_xmlschema::$simpleTypeStack = array()
Definition at line 34 of file class.xmlschema.php.
nusoap_xmlschema::$xml = ''
Definition at line 19 of file class.xmlschema.php.
Referenced by nusoap_xmlschema(), parseFile(), parseString(), and serializeSchema().
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/class.xmlschema.php
modules/dae_wsdl/lib/nusoap.php
modules/soap_server/nusoap/lib/class.xmlschema.php
modules/soap_server/nusoap/lib/nusoap.php