DAEDrupalInterface: nusoap_server_mime Class Reference
nusoap_server_mime Class Reference
Public Member Functions
addAttachment ($data, $filename= '', $contenttype= 'application/octet-stream', $cid=false)
clearAttachments ()
getAttachments ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
parseRequest ($headers, $data)
addAttachment ($data, $filename= '', $contenttype= 'application/octet-stream', $cid=false)
clearAttachments ()
getAttachments ()
getHTTPBody ($soapmsg)
getHTTPContentType ()
getHTTPContentTypeCharset ()
parseRequest ($headers, $data)
Public Attributes
$requestAttachments = array()
$responseAttachments
$mimeContentType
Detailed Description
nusoap_server_mime server supporting MIME attachments defined at http://www.w3.org/TR/SOAP-attachments. It depends on the PEAR Mail_MIME library.
Author:
Scott Nichol <snichol@users.sourceforge.net>
Thanks to Guillaume and Henning Reich for posting great attachment code to the mail list
Version:
Id
nusoapmime.php,v 1.13 2010/04/26 20:15:08 snichol Exp
public
Definition at line 284 of file nusoapmime.php.
Member Function Documentation
nusoap_server_mime::addAttachment ($ data, $ filename = '', $ contenttype = 'application/octet-stream', $ cid = false)
adds a MIME attachment to the current response.
If the $data parameter contains an empty string, this method will read the contents of the file named by the $filename parameter.
If the $cid parameter is false, this method will generate the cid.
Parameters:
string $data The data of the attachment
string $filename The filename of the attachment (default is empty string)
string $contenttype The MIME Content-Type of the attachment (default is application/octet-stream)
string $cid The content-id (cid) of the attachment (default is false)
Returns:
string The content-id (cid) of the attachment public
Definition at line 318 of file nusoapmime.php.
nusoap_server_mime::addAttachment ($ data, $ filename = '', $ contenttype = 'application/octet-stream', $ cid = false)
adds a MIME attachment to the current response.
If the $data parameter contains an empty string, this method will read the contents of the file named by the $filename parameter.
If the $cid parameter is false, this method will generate the cid.
Parameters:
string $data The data of the attachment
string $filename The filename of the attachment (default is empty string)
string $contenttype The MIME Content-Type of the attachment (default is application/octet-stream)
string $cid The content-id (cid) of the attachment (default is false)
Returns:
string The content-id (cid) of the attachment public
Definition at line 318 of file nusoapmime.php.
nusoap_server_mime::clearAttachments ()
clears the MIME attachments for the current response.
public
Definition at line 338 of file nusoapmime.php.
nusoap_server_mime::clearAttachments ()
clears the MIME attachments for the current response.
public
Definition at line 338 of file nusoapmime.php.
nusoap_server_mime::getAttachments ()
gets the MIME attachments from the current request.
Each array element in the return is an associative array with keys data, filename, contenttype, cid. These keys correspond to the parameters for addAttachment.
Returns:
array The attachments. public
Definition at line 352 of file nusoapmime.php.
nusoap_server_mime::getAttachments ()
gets the MIME attachments from the current request.
Each array element in the return is an associative array with keys data, filename, contenttype, cid. These keys correspond to the parameters for addAttachment.
Returns:
array The attachments. public
Definition at line 352 of file nusoapmime.php.
nusoap_server_mime::getHTTPBody ($ soapmsg)
gets the HTTP body for the current response.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented from nusoap_server.
Definition at line 363 of file nusoapmime.php.
References nusoap_base::debug(), and getHTTPBody().
nusoap_server_mime::getHTTPBody ($ soapmsg)
gets the HTTP body for the current response.
Parameters:
string $soapmsg The SOAP payload
Returns:
string The HTTP body, which includes the SOAP payload private
Reimplemented from nusoap_server.
Definition at line 363 of file nusoapmime.php.
References nusoap_base::debug().
Referenced by getHTTPBody().
nusoap_server_mime::getHTTPContentType ()
gets the HTTP content type for the current response.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current response. private
Reimplemented from nusoap_server.
Definition at line 422 of file nusoapmime.php.
References getHTTPContentType().
nusoap_server_mime::getHTTPContentType ()
gets the HTTP content type for the current response.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type for the current response. private
Reimplemented from nusoap_server.
Definition at line 422 of file nusoapmime.php.
Referenced by getHTTPContentType().
nusoap_server_mime::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current response. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current response. private
Reimplemented from nusoap_server.
Definition at line 438 of file nusoapmime.php.
References getHTTPContentTypeCharset().
nusoap_server_mime::getHTTPContentTypeCharset ()
gets the HTTP content type charset for the current response. returns false for non-text content types.
Note: getHTTPBody must be called before this.
Returns:
string the HTTP content type charset for the current response. private
Reimplemented from nusoap_server.
Definition at line 438 of file nusoapmime.php.
Referenced by getHTTPContentTypeCharset().
nusoap_server_mime::parseRequest ($ headers, $ data)
processes SOAP message received from client
Parameters:
array $headers The HTTP headers
string $data unprocessed request data from client
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented from nusoap_server.
Definition at line 453 of file nusoapmime.php.
References nusoap_server::$headers, $input, nusoap_base::debug(), parseRequest(), and nusoap_base::setError().
nusoap_server_mime::parseRequest ($ headers, $ data)
processes SOAP message received from client
Parameters:
array $headers The HTTP headers
string $data unprocessed request data from client
Returns:
mixed value of the message, decoded into a PHP type private
Reimplemented from nusoap_server.
Definition at line 453 of file nusoapmime.php.
References nusoap_server::$headers, $input, nusoap_base::debug(), and nusoap_base::setError().
Referenced by parseRequest().
Member Data Documentation
nusoap_server_mime::$mimeContentType
Definition at line 301 of file nusoapmime.php.
nusoap_server_mime::$requestAttachments = array()
Definition at line 290 of file nusoapmime.php.
nusoap_server_mime::$responseAttachments
Definition at line 296 of file nusoapmime.php.
The documentation for this class was generated from the following files:
modules/dae_wsdl/lib/nusoapmime.php
modules/soap_server/nusoap/lib/nusoapmime.php