DAEDrupalInterface: modules/dae_wsdl/WSDL/client.php File Reference
modules/dae_wsdl/WSDL/client.php File Reference
Variables
$client = new nusoap_client('http://localhost/dae/ocrad.php?wsdl', true)
$err = $client->getError()
if($err) $db = getDAEDatabase()
$importance
$row = $db->fetch_array($importance)
$input = array('page_image' => 'value1', 'testPara' => 'value2')
$result = $client->call('ocrad', array('name' => new soapval('name', 'complexInput', $input, false, 'urn:ocradwsdl')))
Detailed Description
Author:
Yingjie Li <yil308@lehigh.edu>
Version:
1.0
Todo:
This file and all subsequent functions should be moved out of the dae_data module eventually. It is here for pure convenience.
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see <http://www.gnu.org/licenses/>.
Definition in file client.php.
Variable Documentation
$client = new nusoap_client('http://localhost/dae/ocrad.php?wsdl', true)
Todo:
hostname should be determined dynamically or, better even, from the DAE database
Definition at line 39 of file client.php.
Referenced by callback(), dae_data_description(), dae_data_description_debug(), dae_service_dice(), dae_service_icfhr(), dae_service_kanungo(), dae_service_ocrad(), and dae_service_tesseract().
if ($err) $db = getDAEDatabase()
Definition at line 50 of file client.php.
$err = $client->getError()
Definition at line 43 of file client.php.
Referenced by callback(), and dae_data_description_debug().
$importance
Initial value:
 $db ->q("select tag.VALUE as VALUE, count(DATA_ITEM_ID) AS IMP
                                                  from associate_data_item_tag data, TAG tag
                                                  where data.TAG_ID = tag.ID
                                                  group by tag.VALUE
                                                  order by count(DATA_ITEM_ID) desc, LOWER(tag.VALUE) asc ")
Definition at line 52 of file client.php.
Referenced by dae_data_search_page_select().
$input = array('page_image' => 'value1', 'testPara' => 'value2')
Definition at line 61 of file client.php.
Referenced by algorithm_execute(), algorithms_check_files_moved_to_runs(), algorithms_create_spool_directories(), algorithms_get_database_run_info_done(), algorithms_get_run_input_filename(), algorithms_run_form(), algorithms_run_form_submit(), algorithms_run_go(), create_database_flag(), dae_service_dice(), dae_service_icfhr(), dae_service_kanungo(), dae_service_ocrad(), dae_service_tesseract(), run_102(), run_124(), run_125(), run_143(), run_2(), run_82(), run_XX(), validatePreSelected(), and workflow_input_form_submit().
$result = $client->call('ocrad', array('name' => new soapval('name', 'complexInput', $input, false, 'urn:ocradwsdl')))
Definition at line 67 of file client.php.
Referenced by TagCloud::__construct(), callback(), dae_data_browse_dataset_file(), dae_data_browse_dataset_page_image(), dae_data_browse_runoptions(), dae_data_browse_subset(), dae_data_build_page_image_list(), dae_data_description(), dae_data_description_debug(), dae_data_display_datasets(), dae_data_download_before(), dae_data_get_array_of_paths(), dae_data_get_dataset_hierarchy(), dae_data_get_dataset_info_array(), dae_data_get_dataset_leaves(), dae_data_get_drupal_db_list(), dae_data_get_page_element_info_array(), dae_data_get_pageimage_info_array(), dae_data_get_paths_from_result(), dae_service_dice(), dae_service_icfhr(), dae_service_kanungo(), dae_service_ocrad(), dae_service_tesseract(), dataitem_service_descript(), getProfileValue(), DAEDatabase::r(), DAEDatabase::runElapsedTime(), and DAEDatabase::runLength().
$row = $db->fetch_array($importance)
Definition at line 58 of file client.php.
Referenced by TagCloud::__construct(), algorithms_get_database_run_info_done(), algorithms_get_run_input_filename(), algorithms_list(), algorithms_my_runs(), algorithms_run(), algorithms_run_form(), algorithms_run_form_submit(), algorithms_save_output_to_db(), DAEDatabase::checkAlgExists(), DAEDatabase::checkConcurrentRuns(), DAEDatabase::checkDataSetHasChildren(), dae_data_browse_dataset_file(), dae_data_browse_dataset_page_image(), dae_data_browse_runoptions(), dae_data_browse_tree(), dae_data_build_page_image_list(), dae_data_display_datasets(), dae_data_download_before(), dae_data_get_dataset_hierarchy(), dae_data_get_dataset_leaves(), dae_data_get_drupal_db_list(), dae_data_get_paths_from_result(), dae_data_search(), dae_data_search_page_select(), dae_data_search_select(), dae_data_search_tags(), dae_service_algorithms_service(), dae_service_dice(), dae_service_icfhr(), dae_service_kanungo(), dae_service_ocrad(), dae_service_tesseract(), dataitem_service_descript(), file_extension_dropdown(), get_comment_information(), get_dataitem_comments(), DAEDatabase::getAlgName(), RunUI::getRunStatus(), MyUploadsPage::getUsage(), home_directory_change_usage(), invokeWSDL(), DAEDatabase::r(), registerProvenanceStart(), registerProvenanceStop(), retrieveAlgorithmSOAPInputTypes(), retrieveAlgorithmSOAPOutputTypes(), DAEDatabase::runElapsedTime(), DAEDatabase::runLength(), and soap_server().