DAEDrupalInterface: modules/dae_data/dae_data_detail_page.inc File Reference
modules/dae_data/dae_data_detail_page.inc File Reference
Functions
dae_data_browse_dataitem ()
dae_dataset_page ($request, $limit=1)
dae_pageimage_page ($request)
dae_file_page ($request)
dae_page_element_page ($request)
dae_pageimage_pixel_mask ($dataitem, $datatype)
dae_data_browse_runoptions ()
get_dae_data_tag_form ()
get_dataitem_comment_form ($dataitem)
get_dataitem_submitter ($did)
dae_data_get_dataset_hierarchy ($dataset, &$sets, &$dataset_names, $infinite_recurse_stop=array())
dae_data_get_page_image_list ()
dae_data_build_page_image_list ($dataset, &$ui, $limit=1)
dae_data_get_dataset_info_array ($dataset)
dae_data_get_pageimage_info_array ($dataset)
dae_data_get_file_info_array ($dataset)
dae_data_get_page_element_info_array ($dataitem)
dae_data_browse_dataitem_rate ()
dae_data_browse_dataset_comment_rate ()
get_dataitem_comments ($dataitem)
get_comment_information ($comment)
check_comment_id ($comment)
dae_data_comment_rating_exists ($comment)
dae_data_page_element_form ()
dae_data_page_element_form_validate ()
dae_data_page_element_form_submit ($form_id, $form_values)
Variables
$db = getDAEDatabase()
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data_detail_page.inc.
Function Documentation
check_comment_id ($ comment)
This function confirms a comment id exists
Parameters:
$comment - the comment id
Returns:
- 0 if no comment exists, otherwise positive integer
Definition at line 779 of file dae_data_detail_page.inc.
References $db, and getDAEDatabase().
Referenced by dae_data_browse_dataset_comment_rate().
dae_data_browse_dataitem ()
This function is called when browse/dataitem is requested. It takes the data item id from argument(2) and attempts to find the correct function to make a page for the type of data item
Parameters:
arg(2) - the data item id
Returns:
html for a data item page
Definition at line 43 of file dae_data_detail_page.inc.
References $db, $user, check_dataset_id(), dae_data_get_dataset_info_array(), dae_data_get_file_info_array(), dae_data_get_page_element_info_array(), dae_data_get_pageimage_info_array(), dae_data_increment_activity(), dae_dataset_page(), dae_file_page(), dae_page_element_page(), and dae_pageimage_page().
dae_data_browse_dataitem_rate ()
This function saves a users rating of a data item to the database
Parameters:
arg(3) the data item id
arg(4) the rating (1-5)
Definition at line 640 of file dae_data_detail_page.inc.
References $db, $user, check_dataset_id(), dae_data_rating_exists(), getDAEDatabase(), and getPID().
dae_data_browse_dataset_comment_rate ()
This function saves a helpful rating to the database
Returns:
- Success if a comment rating is saved
Definition at line 668 of file dae_data_detail_page.inc.
References $db, $ui, $user, check_comment_id(), dae_data_comment_rating_exists(), get_comment_information(), and getDAEDatabase().
dae_data_browse_runoptions ()
This function outputs the html for the possible algorithms menu on data item pages when /?q=browse/dataitem/runoptions/<data item="" id>="">
arg(3) is therefore the id of the data item
Echoes the html for the option list. The constructed option list URLs end up being handled by the algorithms_run() callback when clicked.
See also:
algorithms_run()
Definition at line 372 of file dae_data_detail_page.inc.
References $db, $result, check_dataset_id(), and getDAEDatabase().
dae_data_build_page_image_list ($ dataset, &$ ui, $ limit = 1)
Definition at line 499 of file dae_data_detail_page.inc.
References $db, $result, $ui, dae_data_get_thumb_uri(), and getDAEDatabase().
Referenced by dae_data_get_page_image_list(), and dae_dataset_page().
dae_data_comment_rating_exists ($ comment)
This function checks to see if a comment has already been rated
Parameters:
$comment - the comment id
Returns:
- 0 if no rating exists, otherwise a positive integer
Definition at line 794 of file dae_data_detail_page.inc.
References $db, $user, getDAEDatabase(), and getPID().
Referenced by dae_data_browse_dataset_comment_rate().
dae_data_get_dataset_hierarchy ($ dataset, &$ sets, &$ dataset_names, $ infinite_recurse_stop = array())
Definition at line 460 of file dae_data_detail_page.inc.
References $db, $result, and getDAEDatabase().
Referenced by dae_dataset_page().
dae_data_get_dataset_info_array ($ dataset)
This function returns information on a dataset
Parameters:
$dataitem - data item id
Returns:
- an array of information on the dataset
Definition at line 555 of file dae_data_detail_page.inc.
References $db, $result, and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_data_get_file_info_array ($ dataset)
This function returns information on a file
Parameters:
$dataitem - data item id
Returns:
- an array of information on the page image
Definition at line 596 of file dae_data_detail_page.inc.
References $db, $result, and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_data_get_page_element_info_array ($ dataitem)
This function returns information on a page element
Parameters:
$dataitem - data item id
Returns:
- an array of information on the page element
Definition at line 617 of file dae_data_detail_page.inc.
References $db, $result, and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_data_get_page_image_list ()
Definition at line 483 of file dae_data_detail_page.inc.
References $ui, check_dataset_id(), and dae_data_build_page_image_list().
dae_data_get_pageimage_info_array ($ dataset)
This function returns information on a page image
Parameters:
$dataitem - data item id
Returns:
- an array of information on the page image
Definition at line 575 of file dae_data_detail_page.inc.
References $db, $result, and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_data_page_element_form ()
This function declares the form for creating page elements
Returns:
- a drupal form array
Definition at line 808 of file dae_data_detail_page.inc.
References $db.
dae_data_page_element_form_submit ($ form_id, $ form_values)
This function saves a user created page element into the database
Parameters:
$form_id - the druapl form id
$form_values - the user submitted form values
Returns:
- none
Create datatype for page element if necessary. Associate page element and datatype
Create page element property value datatype if necessary. Create property value and associate with datatype and page element
Definition at line 965 of file dae_data_detail_page.inc.
References $db, $user, getDAEDatabase(), and getPID().
dae_data_page_element_form_validate ()
Definition at line 949 of file dae_data_detail_page.inc.
dae_dataset_page ($ request, $ limit = 1)
This function is called when a data item is determined to be a dataset
Parameters:
$request - an array containing ['NAME'] = the display name of the data item and ['ID'] = the dataset id
Returns:
html to display a dataset page
Definition at line 84 of file dae_data_detail_page.inc.
References $db, $ui, dae_data_build_page_image_list(), dae_data_get_dataset_hierarchy(), dae_data_get_rating(), get_dae_data_tag_form(), get_dataitem_comment_form(), get_dataitem_comments(), get_dataitem_submitter(), and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_file_page ($ request)
This function is called when a data item is determined to be a file
Parameters:
[in] $request an array containing ['PATH'] = the path to be turned into the display name of the data item and ['ID'] = the page image id
Returns:
html to display a page image page
Definition at line 202 of file dae_data_detail_page.inc.
References $db, $ui, dae_data_get_rating(), get_dae_data_tag_form(), get_dataitem_comment_form(), get_dataitem_comments(), get_dataitem_submitter(), and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_page_element_page ($ request)
This function is called when a data item is determined to be a page element
Parameters:
[in] $request an array containing ['PARENT_PAGE_IMAGE_ID'] = the id of the parent page image ['PARENT_PAGE_IMAGE_PATH'] = the path of the parent page image ['ID'] = the id of the page element ['X'] = top left x position of element ['Y'] = top left y position of the element ['WIDTH'] = width of element ['HEIGHT'] = height of element
Returns:
html to display a page element page
Definition at line 260 of file dae_data_detail_page.inc.
References $db, $ui, dae_data_get_rating(), generate_isolated_pixelmask(), get_dae_data_tag_form(), get_dataitem_comment_form(), get_dataitem_comments(), get_dataitem_submitter(), get_pageelement_properties(), and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_pageimage_page ($ request)
This function is called when a data item is determined to be a page image
Parameters:
[in] $request an array containing ['PATH'] = the path to be turned into the display name of the data item and ['ID'] = the page image id
Returns:
html to display a page image page
Definition at line 142 of file dae_data_detail_page.inc.
References $db, $ui, dae_data_get_rating(), get_dae_data_tag_form(), get_dataitem_comment_form(), get_dataitem_comments(), get_dataitem_submitter(), and getDAEDatabase().
Referenced by dae_data_browse_dataitem().
dae_pageimage_pixel_mask ($ dataitem, $ datatype)
This function generates an alpha mask for a page image if it does not already exist and then returns the mask
Parameters:
[in] $dataitem - the id of the page image
Returns:
png binary
Attempting to keep image cached
Definition at line 333 of file dae_data_detail_page.inc.
get_comment_information ($ comment)
This function gets an array of information on a comment
Parameters:
$comment - the comment id
Returns:
- an array containing the id, author, rating information, text and date
Definition at line 750 of file dae_data_detail_page.inc.
References $db, and getDAEDatabase().
Referenced by dae_data_browse_dataset_comment_rate().
get_dae_data_tag_form ()
This function gets a tag form for data items
Returns:
- the html of for a tag form
Definition at line 425 of file dae_data_detail_page.inc.
Referenced by dae_dataset_page(), dae_file_page(), dae_page_element_page(), and dae_pageimage_page().
get_dataitem_comment_form ($ dataitem)
This function gets a comment form for data items
Parameters:
$dataitem - the data item the comment form will save a comment to
Returns:
- formatted comment form to be inserted into a page
Definition at line 437 of file dae_data_detail_page.inc.
References $user, and dae_data_get_rating().
Referenced by dae_dataset_page(), dae_file_page(), dae_page_element_page(), and dae_pageimage_page().
get_dataitem_comments ($ dataitem)
This builds the html for the comments on a data item
Parameters:
$dataitem - the id of the data item to return comments for
Returns:
- HTML string with the comments
Definition at line 709 of file dae_data_detail_page.inc.
References $db, $ui, and getDAEDatabase().
Referenced by dae_dataset_page(), dae_file_page(), dae_page_element_page(), and dae_pageimage_page().
get_dataitem_submitter ($ did)
Definition at line 452 of file dae_data_detail_page.inc.
References $db, and getDAEDatabase().
Referenced by dae_dataset_page(), dae_file_page(), dae_page_element_page(), and dae_pageimage_page().
Variable Documentation
global $db = getDAEDatabase()
Definition at line 31 of file dae_data_detail_page.inc.