DAEDrupalInterface: modules/dae_ui/dae_ui.module File Reference
modules/dae_ui/dae_ui.module File Reference
Provides the classes which produce the html for dae modules.
Classes
class DataUI
class RunUI
class DAE_Toolbar
class TitleSubmitterRating
class PageImagePage
class PageElementPage
class DatasetPage
class FilePage
class DataItemComment
class DataItemCommentForm
class PageImageList
class DataItemDetails
class StarRating
class UploadUI
class TagCloud
Functions
dae_dataset_preview ($parent)
parse_tree ($root, $db, $e, $count)
Detailed Description
Provides the classes which produce the html for dae modules.
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_ui.module.
Function Documentation
dae_dataset_preview ($ parent)
This function returns the first 5 images from a dataset for the thumbnail previews on the first page.
Parameters:
$parent the id of the dataset
Returns:
Returns HTML markup of the images
Definition at line 1084 of file dae_ui.module.
References $db, dae_data_get_thumb_uri(), getDAEDatabase(), and parse_tree().
parse_tree ($ root, $ db, $ e, $ count)
Runs through a directory structure to grab images for thumbnail previewing
Parameters:
$root The directory to search
$db The database (rather than calling getDAEDatabase() for every iteration)
$e An array to store the ids of page images
$count The number of elements to get
Definition at line 1104 of file dae_ui.module.
References $db, get_directories(), and get_page_elements().
Referenced by dae_dataset_preview(), and DatasetPage::list_builder_datasets().