DAEDrupalInterface: modules/dae_data/dae_data_person.inc File Reference
modules/dae_data/dae_data_person.inc File Reference
Provides the class to query and display user's information.
Classes
class Person
Functions
dae_view_submitter ()
getPID ($uid)
getNextPID ()
getPIDByEmail ($email)
multiple_line ($str, $context)
Detailed Description
Provides the class to query and display user's information.
Author:
Xingjian Zhang xiz30.nosp@m.7@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data_person.inc.
Function Documentation
dae_view_submitter ()
This function is called when ?q=person is requested. It takes the person id from argument(1), fetches information from database and output a page for displaying such information
Parameters:
$input
Returns:
the table (string) that contains the information about the person.
Definition at line 41 of file dae_data_person.inc.
getNextPID ()
This function returns the next Person ID in Oracle.
Returns:
the corresponding person id (pid) in the Person table in the Oracle database.
Definition at line 71 of file dae_data_person.inc.
References $db, and getDAEDatabase().
Referenced by home_directory_user().
getPID ($ uid)
This function takes Drupal user id (uid) as input, and returns the corresponding person id (pid) in the Person table in the Oracle database
Parameters:
$uid
Returns:
the corresponding person id (pid) in the Person table in the Oracle database.
Todo:
default mapping to a potentially random UID is dangerous. This should be fixed
Definition at line 55 of file dae_data_person.inc.
Referenced by algorithms_my_runs(), algorithms_run_form_submit(), algorithms_run_get_status(), algorithms_run_go(), DAEDatabase\checkConcurrentRuns(), dae_data_browse_dataitem_rate(), dae_data_comment_rating_exists(), dae_data_get_rating(), dae_data_page_element_form_submit(), dae_data_rating_exists(), dae_data_upload_submit(), dae_metadata_upload_submit(), dae_page_element_add_interpretation_submit(), generic_hook_ocrad(), home_directory_user(), registerProvenanceStart(), and submit_page().
getPIDByEmail ($ email)
This function returns the Person ID by email
Parameters:
$email
Returns:
PID or -1 if email is not found.
Definition at line 83 of file dae_data_person.inc.
References $db, and getDAEDatabase().
Referenced by home_directory_user().
multiple_line ($ str, $ context)
This function handisplaying the Person information.
Parameters:
$str the multiple-line string to be converted.
$context where this output string will be embeded in. Currently only support 'js' or 'html'
Returns:
the HTML/JavaScript code for displaying multiple-line string. Or the original one if $context is not supported.
Definition at line 101 of file dae_data_person.inc.