DAEDrupalInterface: modules/dae_data/dae_data_query.inc File Reference
modules/dae_data/dae_data_query.inc File Reference
Functions
query_page ()
query_form ()
sel2 ($dn, $arrarr, $farr, $ai, $ci)
sel1 ($dn, $szs, $ci)
getNameById ($dn, $id)
getDescById ($dn, $id)
Function Documentation
getDescById ($ dn, $ id)
Definition at line 292 of file dae_data_query.inc.
References $db, and getDAEDatabase().
Referenced by query_form().
getNameById ($ dn, $ id)
The following lines of code are actually useless and appropriate characters in the retrieved string will still mess up javasctipt!
Definition at line 269 of file dae_data_query.inc.
References $db, and getDAEDatabase().
Referenced by query_form().
query_form ()
Definition at line 82 of file dae_data_query.inc.
References getDescById(), getNameById(), and idstr2arr().
query_page ()
Definition at line 15 of file dae_data_query.inc.
sel1 ($ dn, $ szs, $ ci)
Definition at line 213 of file dae_data_query.inc.
References $db, $result, and getDAEDatabase().
sel2 ($ dn, $ arrarr, $ farr, $ ai, $ ci)
Definition at line 144 of file dae_data_query.inc.
References $db, $result, genSQL(), and getDAEDatabase().