DAEDrupalInterface: modules/dae_data/dae_metadata_upload_file.inc File Reference
modules/dae_data/dae_metadata_upload_file.inc File Reference
Functions
dae_metadata_upload ()
tmpdir ($path, $prefix)
dae_metadata_upload_submit ($form_id, $form_values)
dae_metadata_upload_page ($form_state=NULL)
dae_metadata_upload_validate ($form_id, $form_values)
Detailed Description
Author:
Bart Lamiroy lamir.nosp@m.oy@c.nosp@m.se.le.nosp@m.high.nosp@m..edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_metadata_upload_file.inc.
Function Documentation
dae_metadata_upload ()
Implementation of upload.
Definition at line 34 of file dae_metadata_upload_file.inc.
References $user.
dae_metadata_upload_page ($ form_state = NULL)
Definition at line 165 of file dae_metadata_upload_file.inc.
dae_metadata_upload_submit ($ form_id, $ form_values)
Implementation of upload submit.
Definition at line 99 of file dae_metadata_upload_file.inc.
References $user, getPID(), home_directory_upload_rename(), and tmpdir().
dae_metadata_upload_validate ($ form_id, $ form_values)
Definition at line 194 of file dae_metadata_upload_file.inc.
tmpdir ($ path, $ prefix)
Creates a directory with a unique name at the specified with the specified prefix. (copied from http://php.net/manual/en/function.tempnam.php)
Parameters:
unknown_type $path
unknown_type $prefix
Returns:
directory name on success, false otherwise
Definition at line 77 of file dae_metadata_upload_file.inc.
Referenced by dae_metadata_upload_submit().