DAEDrupalInterface: modules/dae_data/dae_data.module File Reference
modules/dae_data/dae_data.module File Reference
Functions
dae_data_menu ()
A callback is added for retrieving copyright information whose URL is end with browse/dataitem/beforedownload One more callback is added for searching tags and datasets by using dropdown list. Its URL ends with browse/search/select.
dae_data_init ()
dae_data_perm ()
dae_data_browse_tree ()
getParent ($dataitem)
dae_data_search_tags ()
check_dataset_id ($dataitem)
dae_data_browse_dataset_dataitem ()
dae_data_browse_dataset_dataitem_build ($dataitem, $loadImage=false)
Displays detailed information of a DATA_ITEM when accessed.
dae_data_browse_dataset_page_image ($dataitem)
dae_data_browse_dataset_page_element ($dataitem)
dae_data_browse_dataset_file ($dataitem)
dae_data_browse_dataset_thumb ()
dae_data_get_thumb_path ($data_item=0, $size)
dae_data_browse_dataset_thumb_uri ()
dae_data_get_thumb_uri ($data_item=0, $size)
dae_data_filesize_string ($bytes)
dae_data_is_image ($dataitem)
dae_data_mime ($path)
dae_data_get_rating ($dataitem, $showMyRating=true, $uid=null)
dae_data_rating_exists ($dataitem)
dae_data_search_tag ()
dae_data_increment_activity ($dataitem, $amount)
dae_data_search_select ()
Displays detailed information of a selected TAG in the TAG dropdown list.
dae_data_download_access ($accessRights)
dae_data_search ($op= 'search', $keys=NULL)
dae_data_update_index ()
get_page_elements ($id, $db)
get_directories ($id, $db)
Variables
global $db = getDAEDatabase()
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data.module.
Function Documentation
check_dataset_id ($ dataitem)
This confirms requests for data items are integers and logs the request if it is not
Parameters:
$dataitem - the id to check
Returns:
- true if it is only an integer or false if it is not
Definition at line 503 of file dae_data.module.
Referenced by dae_data_add_comment(), dae_data_browse_dataitem(), dae_data_browse_dataitem_rate(), dae_data_browse_runoptions(), dae_data_browse_subset(), dae_data_browse_tree(), dae_data_copy(), dae_data_download(), dae_data_download_before(), dae_data_flag(), dae_data_get_download_size(), and dae_data_get_page_image_list().
dae_data_browse_dataset_dataitem ()
This function outputs the information on a data item as html to be displayed on the dataset browse page
Parameters:
arg(3) - the id of the dataitem to retreive page html for
Returns:
- echoes the html to be retreived via ajax.
Definition at line 520 of file dae_data.module.
References dae_data_browse_dataset_dataitem_build().
dae_data_browse_dataset_dataitem_build ($ dataitem, $ loadImage = false)
Displays detailed information of a DATA_ITEM when accessed.
Parameters:
[in] $dataitem Database DATE_ITEM ID
[in] $loadImage
Definition at line 533 of file dae_data.module.
References dae_data_browse_dataset_file(), dae_data_browse_dataset_page_element(), dae_data_browse_dataset_page_image(), and getDAEDatabase().
Referenced by algorithms_run_form(), and dae_data_browse_dataset_dataitem().
dae_data_browse_dataset_file ($ dataitem)
Todo:
This is related to the MIME problem related a few lines of code further
Gathered data from the database and php's getimagesize() is placed in two arrays, labels and meta. Label index *is expected to match meta index.
Todo:
Solve the mime problem on Solaris. Normally the following code should work, but it doesn't
Definition at line 719 of file dae_data.module.
References $result, $ui, dae_data_filesize_string(), and getDAEDatabase().
Referenced by dae_data_browse_dataset_dataitem_build().
dae_data_browse_dataset_page_element ($ dataitem)
Gathered data from the database and php's getimagesize() is placed in two arrays, labels and meta. Label index *is expected to match meta index.
Definition at line 654 of file dae_data.module.
References $result, $ui, dae_data_filesize_string(), and getDAEDatabase().
Referenced by dae_data_browse_dataset_dataitem_build().
dae_data_browse_dataset_page_image ($ dataitem)
This function builds and returns an html description of a page image. IT ASSUMES THE GIVEN DATA ITEM IS A PAGE IMAGE
Parameters:
$dataitem - the id of the page image. This function assumes the item is a page image.
Returns:
- html for a page image description
Gathered data from the database and php's getimagesize() is placed in two arrays, labels and meta. Label index *is expected to match meta index.
Definition at line 562 of file dae_data.module.
References $result, $ui, dae_data_filesize_string(), dae_data_get_thumb_path(), and getDAEDatabase().
Referenced by dae_data_browse_dataset_dataitem_build().
dae_data_browse_dataset_thumb ()
This function returns thumbnails for page images
Parameters:
arg(3) - the id of the page image to get a thumbnail for
arg(4) - the desired size for the thumbnail (small, medium, large, original)
Returns thumbnail
Attempting to keep image cached
Definition at line 793 of file dae_data.module.
References dae_data_get_thumb_path().
dae_data_browse_dataset_thumb_uri ()
This function spits out the uri encoding of a dataset image. It uses dae_get_thumb_uri
Definition at line 889 of file dae_data.module.
References dae_data_get_thumb_uri().
dae_data_browse_tree ()
This function returns a json encoding of related data items depending on the type
Parameters:
arg(2) - the id of the data item to return a tree for
Returns:
- json encoded data on the parent elements of the requested data item
selects page element information including parent and location to display parent page image in tree dropdown
Definition at line 354 of file dae_data.module.
References check_dataset_id(), dae_data_get_thumb_path(), dae_data_is_image(), getDAEDatabase(), and getParent().
dae_data_download_access ($ accessRights)
Definition at line 1233 of file dae_data.module.
dae_data_filesize_string ($ bytes)
This function formats a number of bytes into a human readable format
Parameters:
$bytes - an integer number of bytes to convert
Returns:
- a string representing the number of giga, mega or kilobytes
Definition at line 976 of file dae_data.module.
Referenced by dae_data_browse_dataset_file(), dae_data_browse_dataset_page_element(), and dae_data_browse_dataset_page_image().
dae_data_get_rating ($ dataitem, $ showMyRating = true, $ uid = null)
This provides information on a data item's rating. By default, the function checks to see if the current user has rated the data item, and if so it returns 1 to signify that the user has rated it, and the integer rating that the current user gave the data item. If the current user has not rated the data item, or $showMyRating is set to false, it will return the average rating from all users for the given data item
Parameters:
$dataitem - the id of the data item to retrieve a rating for
$showMyRating - whether or not to show the current user's rating or the average rating
$uid - if you want a rating from a given user, use this.
Returns:
- an array containing ['rated'] - 1 if the current user has rated the data item, 0 if not ['rating'] - either the average rating for the data item or the current user's rating
Definition at line 1072 of file dae_data.module.
References $db, $user, dae_data_rating_exists(), and getPID().
Referenced by dae_data_display_datasets(), dae_dataset_page(), dae_file_page(), dae_page_element_page(), dae_pageimage_page(), and get_dataitem_comment_form().
dae_data_get_thumb_path ($ data_item = 0, $ size)
This function helps dae_data_browse_dataset_thumb find the correct path
Parameters:
$data_item - the id of the page image to get a thumbnail for
$size - the desired size of the thumbnail (small, medium, large, original)
In general I have found it is best to always return a thumbnail rather than the original because of issues with mime types. Thumbnails are always png
Returns:
- true if it is only an integer or false if it is not
Definition at line 821 of file dae_data.module.
References getDAEDatabase().
Referenced by dae_data_browse_dataset_page_image(), dae_data_browse_dataset_thumb(), and dae_data_browse_tree().
dae_data_get_thumb_uri ($ data_item = 0, $ size)
This function finds the correct dataset image and returns the uri incoding.
Parameters:
$data_item - the id of the page image to get a thumbnail for
$size - the desired size of the thumbnail (small, medium, large, original)
Definition at line 904 of file dae_data.module.
References getDAEDatabase().
Referenced by dae_data_browse_dataset_thumb_uri(), dae_data_build_page_image_list(), dae_data_display_datasets(), and dae_dataset_preview().
dae_data_increment_activity ($ dataitem, $ amount)
This function adds to a data item's popularity rating for the day
Parameters:
$dataitem - the id of the data item to increase popularity
$amount - the integer amount to increment popularity Certain usage increases popularity more than other usage
Definition at line 1171 of file dae_data.module.
References getDAEDatabase().
Referenced by algorithm_pre_selected(), dae_data_browse_dataitem(), dae_data_copy(), and dae_data_download().
dae_data_init ()
This function adds the necessary javascript and css for dae data pages
Definition at line 327 of file dae_data.module.
dae_data_is_image ($ dataitem)
Depricated. This function determines whether or not a file should be considered an image.
Todo:
Remove/Update. All page images must be displayed images, and all thumbnails are png so this function is not necessary
Parameters:
$dataitem - the id of the data item to check
Returns:
- the mimetype of the file
Definition at line 1000 of file dae_data.module.
References getDAEDatabase().
Referenced by dae_data_browse_tree().
dae_data_menu ()
A callback is added for retrieving copyright information whose URL is end with browse/dataitem/beforedownload One more callback is added for searching tags and datasets by using dropdown list. Its URL ends with browse/search/select.
Definition at line 45 of file dae_data.module.
dae_data_mime ($ path)
This function returns mime types for files based on their extension
Parameters:
$path - a string that at minimum contains a file with an extension
Returns:
- a string representing the mimetype of the file
Definition at line 1031 of file dae_data.module.
Referenced by dae_data_copyright(), and dae_data_download().
dae_data_perm ()
This function augments permissions for the dae data module
Returns:
- an array of permissions added by the dae data module
Definition at line 343 of file dae_data.module.
dae_data_rating_exists ($ dataitem)
This checks to see if the authenticated user has a saved rating for the given data item
Parameters:
$dataitem - the id of the data item to check for an existing rating
Returns:
- true/false
Definition at line 1106 of file dae_data.module.
References $db, $user, and getPID().
Referenced by dae_data_add_comment_validate(), dae_data_browse_dataitem_rate(), and dae_data_get_rating().
dae_data_search ($ op = 'search', $ keys = NULL)
Currently not implemented but default function chokes on browse/tags/search
Definition at line 1242 of file dae_data.module.
dae_data_search_select ()
Displays detailed information of a selected TAG in the TAG dropdown list.
Definition at line 1191 of file dae_data.module.
References getDAEDatabase().
dae_data_search_tag ()
This function is used to autocomplete the search bar on the data browsing pages
Parameters:
$_GET['term'] - the search term for tags and datasets
Returns:
- json containing an id (address), label, value and category
max of 25 right now
Definition at line 1119 of file dae_data.module.
References getDAEDatabase().
dae_data_search_tags ()
This function returns a json encoding of tags for the autocomplete search
Parameters:
$_GET['term'] - the query string against tags
Returns:
- json encoded list of matching tags
Definition at line 475 of file dae_data.module.
References getDAEDatabase().
dae_data_update_index ()
Currently not implemented but default function chokes on browse/tags/search
Definition at line 1247 of file dae_data.module.
get_directories ($ id, $ db)
Gets sub directories of a given parent directory
Parameters:
$id the id of the directory to check
$db DAEdatabase
Definition at line 1271 of file dae_data.module.
Referenced by parse_tree().
get_page_elements ($ id, $ db)
Gets page images of a given parent directory
Parameters:
$id the id of the directory to check
$db DAEdatabase
Definition at line 1256 of file dae_data.module.
Referenced by parse_tree().
getParent ($ dataitem)
Definition at line 451 of file dae_data.module.
Referenced by dae_data_browse_tree().
Variable Documentation
$db = getDAEDatabase()
Definition at line 31 of file dae_data.module.