DAEDrupalInterface: modules/dae_annotations/dae_annotations_edit.inc File Reference
modules/dae_annotations/dae_annotations_edit.inc File Reference
Functions
edit_annotation_info ()
annotation_edit_info_form ($form_id, $info)
annotation_edit_info_form_validate ($form_id, &$form_state)
annotation_edit_info_form_submit ($form_id, &$form_state)
edit_annotation_ui ()
edit_annotation_ui_form ($fid, $aid)
edit_annotation_ui_form_submit ($form_id, &$form_state)
Function Documentation
annotation_edit_info_form ($ form_id, $ info)
Definition at line 15 of file dae_annotations_edit.inc.
annotation_edit_info_form_submit ($ form_id, &$ form_state)
Definition at line 46 of file dae_annotations_edit.inc.
References $user.
annotation_edit_info_form_validate ($ form_id, &$ form_state)
Definition at line 40 of file dae_annotations_edit.inc.
edit_annotation_info ()
Definition at line 3 of file dae_annotations_edit.inc.
References canEdit(), and getAnnotationInfo().
edit_annotation_ui ()
Definition at line 64 of file dae_annotations_edit.inc.
References canEdit(), and dae_annotation_ui_params().
edit_annotation_ui_form ($ fid, $ aid)
Definition at line 77 of file dae_annotations_edit.inc.
edit_annotation_ui_form_submit ($ form_id, &$ form_state)
Definition at line 98 of file dae_annotations_edit.inc.
References $user.