DAEDrupalInterface: modules/dae_data/dae_data_tag.inc File Reference
modules/dae_data/dae_data_tag.inc File Reference
Functions
dae_data_tag_form ()
dae_data_tag_form_validate ($form, &$form_state)
dae_data_tag_form_submit ($form_id, $form_values)
dae_data_tag_add_assoc ($tag_on, $tag_id)
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data_tag.inc.
Function Documentation
dae_data_tag_add_assoc ($ tag_on, $ tag_id)
This function is a helper for the tag form submit. It associates tags and data items
Parameters:
$tag_on - the data item to associate a tag with
$tag_id - the id of the tag to associate with a data item
Returns:
- none
Definition at line 132 of file dae_data_tag.inc.
References $db, and getDAEDatabase().
Referenced by dae_data_tag_form_submit().
dae_data_tag_form ()
This function contains and returns a tag form for data items
Returns:
- a drupal form array
Definition at line 34 of file dae_data_tag.inc.
dae_data_tag_form_submit ($ form_id, $ form_values)
This function creates a new tag if necessary and then associates data items with the tag
Parameters:
$form_id - the drupal form id
$form_values - the user submitted form values
Returns:
- none
Definition at line 91 of file dae_data_tag.inc.
References $db, $user, dae_data_tag_add_assoc(), and getDAEDatabase().
dae_data_tag_form_validate ($ form, &$ form_state)
This function validates user submitted tags by checking that they are more than one character and they on a data item
Parameters:
$form - the drupal form object
$form_state - the user input
Returns:
- json encoded list of page elements and their boundaries relative to the fullsize image.
Definition at line 70 of file dae_data_tag.inc.