DAEDrupalInterface: modules/dae_data/dae_data_operations.inc File Reference
modules/dae_data/dae_data_operations.inc File Reference
Functions
dae_data_copyright ()
dae_data_download_before ()
The callback function to retrieve copyright information before download and copy.
dae_data_download ()
Callback function allowing to actually download specific data_items from the database server.
dae_data_get_download_size ($dataID)
dae_data_flag ()
dae_data_copy ()
dae_data_copy_to_home_directory ($paths, $directory)
dae_data_get_page_image_path ($dataitem)
dae_data_get_file_path ($dataitem)
dae_data_get_array_of_paths ($dataset)
dae_data_get_paths_from_result ($result, $paths)
dae_data_get_dataset_leaves ($dataset, &$sets)
find_prefix ($array)
dae_data_zip ($paths)
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data_operations.inc.
Function Documentation
dae_data_copy ()
Definition at line 183 of file dae_data_operations.inc.
References $db, $user, check_dataset_id(), dae_data_copy_to_home_directory(), dae_data_get_array_of_paths(), dae_data_increment_activity(), and getDAEDatabase().
dae_data_copy_to_home_directory ($ paths, $ directory)
Definition at line 221 of file dae_data_operations.inc.
References $uploads, find_prefix(), home_directory_change_usage(), and home_directory_make_directory().
Referenced by dae_data_copy().
dae_data_copyright ()
Definition at line 29 of file dae_data_operations.inc.
References $db, $user, dae_data_mime(), and getDAEDatabase().
dae_data_download ()
Callback function allowing to actually download specific data_items from the database server.
Todo:
This function should check (how ??) whether the user has cleared the copyright disclaimer.
This function checks whether the current argument (based on the Drupal URL arg(3)) is indeed a data_item id. It currently allows downloading of the following data_item types:
PAGE_IMAGE
FILE
DATASET
Definition at line 86 of file dae_data_operations.inc.
References $db, $user, check_dataset_id(), dae_data_get_array_of_paths(), dae_data_get_file_path(), dae_data_get_page_image_path(), dae_data_increment_activity(), dae_data_mime(), dae_data_zip(), and getDAEDatabase().
dae_data_download_before ()
The callback function to retrieve copyright information before download and copy.
Definition at line 49 of file dae_data_operations.inc.
References $db, $result, $user, check_dataset_id(), and getDAEDatabase().
dae_data_flag ()
Definition at line 167 of file dae_data_operations.inc.
References check_dataset_id(), and dae_data_browse().
dae_data_get_array_of_paths ($ dataset)
Definition at line 268 of file dae_data_operations.inc.
References $db, $result, dae_data_get_paths_from_result(), and getDAEDatabase().
Referenced by dae_data_copy(), dae_data_download(), and dae_data_get_download_size().
dae_data_get_dataset_leaves ($ dataset, &$ sets)
Definition at line 344 of file dae_data_operations.inc.
References $db, $result, and getDAEDatabase().
dae_data_get_download_size ($ dataID)
Definition at line 132 of file dae_data_operations.inc.
References $db, $user, check_dataset_id(), dae_data_get_array_of_paths(), dae_data_get_file_path(), dae_data_get_page_image_path(), and getDAEDatabase().
dae_data_get_file_path ($ dataitem)
Definition at line 262 of file dae_data_operations.inc.
References $db, and getDAEDatabase().
Referenced by dae_data_download(), and dae_data_get_download_size().
dae_data_get_page_image_path ($ dataitem)
Definition at line 256 of file dae_data_operations.inc.
References $db, and getDAEDatabase().
Referenced by dae_data_download(), and dae_data_get_download_size().
dae_data_get_paths_from_result ($ result, $ paths)
Definition at line 334 of file dae_data_operations.inc.
References $db, $result, and getDAEDatabase().
Referenced by dae_data_get_array_of_paths().
dae_data_zip ($ paths)
Definition at line 382 of file dae_data_operations.inc.
References $user, and find_prefix().
Referenced by dae_data_download().
find_prefix ($ array)
Check if the current prefix is still prefix of the current element in the array If not, find the longest common prefix by removing characters from the end.
Definition at line 361 of file dae_data_operations.inc.
Referenced by dae_data_copy_to_home_directory(), and dae_data_zip().