DAEDrupalInterface: modules/dae_data/dae_data_page_elements.inc File Reference
modules/dae_data/dae_data_page_elements.inc File Reference
Functions
get_pageelement_properties ($dataitem)
dae_page_element_add_interpretation ($form_state, $dataitem)
dae_page_element_add_interpretation_validate ($form, &$form_state)
dae_page_element_add_interpretation_submit ($form, &$form_state)
generate_isolated_pixelmask ($elementid, $path= '/tmp')
generate_pixelmask ($pageimage, $path="/tmp")
convert_db_mask_to_array ($maskLOB)
getMinMaxCoords ($coords)
makePixelMask ($id, $path, $width, $height, $pixels, $intensity=175, $color= '"rgb(100,250,50)"')
get_page_element_boxes ($dataitem)
dae_data_page_element_type_search ()
dae_pageimage_page_generate_pixelmask ($dataitem)
dae_data_pageimage_load_mask ($pageimage)
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data_page_elements.inc.
Function Documentation
convert_db_mask_to_array ($ maskLOB)
Takes an LOB, loads it and parses it into an array of x and y coordinates
Parameters:
[in] $maskLOB - oracle large object containing a string of pixel pairs
Returns:
- an array with two sub arrays ['x'] and ['y'] which contain the x y pairs at matching keys
Definition at line 427 of file dae_data_page_elements.inc.
Referenced by generate_isolated_pixelmask(), and generate_pixelmask().
dae_data_page_element_type_search ()
This function returns a json listing of datatypes matching a search query given by GET term
Parameters:
$_GET['term']
Returns:
json search results
Definition at line 577 of file dae_data_page_elements.inc.
References $db, and getDAEDatabase().
dae_data_pageimage_load_mask ($ pageimage)
Definition at line 624 of file dae_data_page_elements.inc.
References get_page_element_boxes().
dae_page_element_add_interpretation ($ form_state, $ dataitem)
This function returns a drupal form array for creating interpretations of page elements
Parameters:
[in] $dataitem - the page element for which an interpretation should be added
Returns:
an array containing a drupal form
Definition at line 72 of file dae_data_page_elements.inc.
References $db.
dae_page_element_add_interpretation_submit ($ form, &$ form_state)
This function saves the input from the user for the interpretation form
Parameters:
[in] $form - standard drupal form submit
[in] $form_state - standard for drupal form submit
Definition at line 214 of file dae_data_page_elements.inc.
References $db, $user, and getPID().
dae_page_element_add_interpretation_validate ($ form, &$ form_state)
This function validates the input from the user for the interpretation form
Parameters:
[in] $form - standard drupal form validate
[in] $form_state - standard for drupal form validate
Definition at line 190 of file dae_data_page_elements.inc.
dae_pageimage_page_generate_pixelmask ($ dataitem)
This function generates the png alpha mask for pixel masks
Parameters:
[in] $request an array containing ['ID'] = the page image id
Returns:
array of bounding boxes for masks by data item id (todo)
Definition at line 619 of file dae_data_page_elements.inc.
References generate_pixelmask().
generate_isolated_pixelmask ($ elementid, $ path = '/tmp')
Generates a transparent pixelmask for the page_element of which its id is given.
Parameters:
[in] $elementid the id of the page_element
Todo:
This code is currently only taking into account the very specifi syntax for CVC-cc-area type representations. This should be modified to a more generic framework using the boundary attribute of the page_element.
Definition at line 259 of file dae_data_page_elements.inc.
References $db, convert_db_mask_to_array(), getMinMaxCoords(), and makePixelMask().
Referenced by dae_page_element_page().
generate_pixelmask ($ pageimage, $ path = "/tmp")
Generates a transparent pixelmask for the page_element of which its id is given.
Parameters:
[in] $elementid the id of the page_element
Todo:
This code is currently only taking into account the very specifi syntax for CVC-cc-area type representations. This should be modified to a more generic framework using the boundary attribute of the page_element.
Definition at line 315 of file dae_data_page_elements.inc.
References $db, convert_db_mask_to_array(), getMinMaxCoords(), and makePixelMask().
Referenced by dae_pageimage_page_generate_pixelmask(), and get_page_element_boxes().
get_page_element_boxes ($ dataitem)
This function returns a json encoding of all page elements for a given page image
Parameters:
[in] $dataitem the page image to find elements for
Returns:
json encoded list of page elements and their boundaries relative to the fullsize image.
Definition at line 511 of file dae_data_page_elements.inc.
References $db, and generate_pixelmask().
Referenced by dae_data_pageimage_load_mask().
get_pageelement_properties ($ dataitem)
This function returns an array of page element property values for the given element
Parameters:
[in] $dataitem - the page element to find values for
Returns:
an array containing all property values and types
Definition at line 37 of file dae_data_page_elements.inc.
References $db.
Referenced by dae_page_element_page().
getMinMaxCoords ($ coords)
Gets the min and max for the x and y of a pixel mask
Parameters:
[in] $coords - the pixel array for a pixel mask in the form ['x'] and ['y'] with pairs at matching keys for the x and y arrays
return - an array containing the x and y max and min
Definition at line 456 of file dae_data_page_elements.inc.
Referenced by generate_isolated_pixelmask(), and generate_pixelmask().
makePixelMask ($ id, $ path, $ width, $ height, $ pixels, $ intensity = 175, $ color = '"rgb(100,250,50)"')
Generates a transparent pixelmask for the page_element of which its id is given.
Parameters:
[in] $id the data item id for this mask
[in] $path the location to create mask
[in] $width width of mask image
[in] $height height of mask image
[in] $pixels array of pixels marked as 0 or 255
[in] $intensity intensity setting for ImageMagick
[in] $color color setting for ImageMagick
Definition at line 477 of file dae_data_page_elements.inc.
Referenced by generate_isolated_pixelmask(), and generate_pixelmask().