DAEDrupalInterface: modules/dae_data/dae_data_browse.inc File Reference
modules/dae_data/dae_data_browse.inc File Reference
Functions
dae_data_browse ()
dae_data_get_drupal_db_list ($result)
dae_data_pagination ($default_limit=10)
dae_data_popular_interval ($default=30)
dae_data_browse_get_results ($data_items, $filter)
human_readable ($size)
dae_data_display_datasets (&$results, &$db, $order=array(), &$pagination=array())
dae_data_get_activity ($dataitem, $days)
dae_data_get_tags ($dataitem)
dae_data_browse_subset ()
dae_data_search_results_page ()
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data_browse.inc.
Function Documentation
dae_data_browse ()
This function decides which data items to return based on the request url
Adding a browse by case:
Each browse by case specifies the different parts of all possibile and necessary queries Since data can be filtered by page images, root datasets, etc the queries are built by specifying and combining the select, from, group, where of a given type of data. In other words, if a user filters by all, the a query is built from the 'PAGE_IMAGE' array and the 'DATASET' array, followed by a union of the two to get the result. In the event that $queries['DATASET']['SELECT'] or some other part of the ['DATASET'] array does not exist, the corresponding ['ALL'] is used in its place. Finally, ['ROW_NUMBERED'] specifies a select that includes all information and a row number as RN.
The dataset page builder assumes the the data item id "DATA_ITEM", and the name to be displayed is "NAME"
Adding a new filter is as simple as adding any necessary query parts and adding an array with the corresponding name filter type to the filter switch. Also remember to add the data type/filter to All
Parameters:
arg(1) - a string which describes the group of data to display
Returns:
- the html for a data browsing page
default clauses for queries
clauses when querying for page images
Todo:
Secure following two queries from SQL injection
Definition at line 53 of file dae_data_browse.inc.
References $db, dae_data_display_datasets(), dae_data_pagination(), dae_data_popular_interval(), and getDAEDatabase().
Referenced by dae_data_flag().
dae_data_browse_get_results ($ data_items, $ filter)
This function is used to bridge the gap between the Drupal and Oracle Databases. Using the filter and a list of data items, it selected all the data items needed for a given page. If the filter is not recognized, all types of data items are returned.
Parameters:
$data_items a comma separated string list of data items to select. IDs may refer to any type of data item
$filter the requested filter for the page (type of data item).
Returns:
an array of oracle results that contain the data items requested in the $data_items list
Definition at line 264 of file dae_data_browse.inc.
References $db, and getDAEDatabase().
dae_data_browse_subset ()
Depricated. Marked for deletion.
Todo:
remove function and dependencies
Definition at line 442 of file dae_data_browse.inc.
References $db, $result, $ui, check_dataset_id(), dae_data_display_datasets(), and getDAEDatabase().
dae_data_display_datasets (&$ results, &$ db, $ order = array(), &$ pagination = array())
Takes an array of results and an order of data items to build the data items page
Parameters:
$results - an array of oracle results with the columns ID and NAME or ID and PATH
$db - a DAE database object
$order - an array of data item IDs in the order they are to be displayed
$pagination - an array containing the per page, page and total number of rows information
Returns:
html to be displayed
Definition at line 311 of file dae_data_browse.inc.
References $db, $result, $ui, dae_data_get_activity(), dae_data_get_rating(), dae_data_get_tags(), dae_data_get_thumb_uri(), and dae_data_popular_interval().
Referenced by dae_data_browse(), dae_data_browse_subset(), and dae_data_search_results_page().
dae_data_get_activity ($ dataitem, $ days)
This function gets the activity rating of a data item from the Drupal Database
Parameters:
[in] $dataitem an ID of a data item to retrieve activity rating for
[in] $days
Returns:
an integer representing the data item's activity rating
Definition at line 396 of file dae_data_browse.inc.
References $db, and getDAEDatabase().
Referenced by dae_data_display_datasets().
dae_data_get_drupal_db_list ($ result)
This function takes a Drupal MySQL result with column 'data_item' and returns an array containing a comma separated string of the data item IDs and an array of the IDs in the correct display order
Parameters:
$result - a MySQL result which has data_item as a column name
Returns:
- an array containing a comma separated string of the data item IDs and an array of the IDs in the correct display order
Definition at line 185 of file dae_data_browse.inc.
References $result.
dae_data_get_tags ($ dataitem)
This function is used get a comma separated list of tag links
Parameters:
$dataitem the ID of a dataitem to get tag list for
Returns:
a comma separated list of tag links
Definition at line 421 of file dae_data_browse.inc.
References $db, and getDAEDatabase().
Referenced by dae_data_display_datasets().
dae_data_pagination ($ default_limit = 10)
This function interprets pagination variables in the request URL It assumes the variables per_page and page contain the pagination information. It does not allow more than 100 data items per page.
Parameters:
$default_limit - if no per_page is specified, how many items to show per page
Returns:
- an array containing 'per' with the number of items per page and 'page' containing the number of the page to be viewed.
Definition at line 206 of file dae_data_browse.inc.
Referenced by dae_data_browse(), and dae_data_search_results_page().
dae_data_popular_interval ($ default = 30)
This function interprets popular intervals and returns the correct number of days
Parameters:
$default - if no default is specified, how far back to check for popular
Returns:
- the number of days to scan over
Definition at line 227 of file dae_data_browse.inc.
Referenced by dae_data_browse(), and dae_data_display_datasets().
dae_data_search_results_page ()
This function looks for a search string GET 's' and returns matching tags and data items
Returns:
html to build a search results page
Definition at line 463 of file dae_data_browse.inc.
References $db, dae_data_display_datasets(), dae_data_pagination(), and getDAEDatabase().
human_readable ($ size)
Definition at line 289 of file dae_data_browse.inc.