DAEDrupalInterface: modules/services/dae_algorithms/dae_service_algorithms.inc File Reference
modules/services/dae_algorithms/dae_service_algorithms.inc File Reference
Functions
files_identical ($fn1, $fn2)
createDataItem ($data, $dataType, $flag)
localCopy ($value, $localname)
registerDataItem ($dataType, $dataTypeId, $dataId, $value, $remoteData=false)
findDataItemToRegister ($dataType, $dataTypeId, $dataId, $value, $runId)
registerProvenanceStart ($algoId, &$callParameters, $quarantainedExecutionProxy=null)
registerProvenanceFailure ($inserted_id, $algoId)
registerProvenanceStop ($inserted_id, $algoId, &$callParameters)
hook_algorithm ($aid, $aname, $args1, $args2=null)
checkForCloneExecution ($runId)
callback ($callbackArguments=array(), $username, $password)
Variables
global $db
Function Documentation
callback ($ callbackArguments = array(), $ username, $ password)
This is a generic callback through which all web-service calls are routed.
This function relies on a session variable $_SESSION['algoId'] to determine which is the actual algorithm web service it will eventually call.
The session variable is set in dae_service_algorithms_auth() at the invocation of the service.
This callback function prepares all input and output data to conform to the DAE data model standards, registers provenance and reformats data to fit with remote or quarantained services.
Parameters:
[in] $callbackArguments
[in] $username
[in] $password
Returns:
algorithm outputs
If the algorithm is a standard, DAE hosted application: generate the access path URL by using the algorithm_service_host Drupal variable and $algoHTMLString
! This may be the source of difficult to identify bugs. When the following error message is logged 'wsdl error: Bad path to WSDL file XYZ' this may mean that the $algoInfo['PATH'] value stored in the database, is wrong (e.g. due to case sensitivity or typos)
If the algorithm is NOT a standard, DAE hosted application, it is either a remotely hosted application or a quarantained DAE hosted application.
The algorithm is a quarantained DAE hosted application if its URL lies within the defined quarantaine network.
Todo:
Get the nusoap error handling right and raise appropriate exceptions ... everywhere (not only here) !
Todo:
the database retrieved Input/Output parameters should be checked to the published WSDL information
While the current callback's WSDL input/output description (and subsequent hierarchical structure of the $callbackArguments associative array) has a complex naming scheme combining DATA.name, DATA.id as well as DATA_TYPE.name and DATA_TYPE.id values, the actual webservice executing the algorithm has a 'flat' WSDL input/output structure in which the argument names identical to DATA.name.
Todo:
We're assuming all array keys are unique ... check if this is actually the case 100% of the time
Todo:
We're assuming composite types only have one component ... check if this is actually the case 100% of the time
Once all input arguments have been retrieved and have been associated wth their corresponding DATA.id we resister a new ALGORITHM_RUN.id ($runId) and store and associate input provenance in the DAE Oracle database.
If the run is quarantained, we also need to copy the input to the quarantaine proxy and translate input value URLs to this new location so that the quarantained web services can access the data.
Todo:
check for possible execution failures of the above webservice call.
Todo:
We're assuming all array keys are unique ... check if this is actually the case 100% of the time
Todo:
Check following 2 lines of code... it looks like there's some redundancy here
Todo:
We're assuming composite types only have one component ... check if this is actually the case 100% of the time
Definition at line 937 of file dae_service_algorithms.inc.
References $client, $result, $user, checkForCloneExecution(), getDAEDatabase(), hook_algorithm(), registerProvenanceFailure(), registerProvenanceStart(), registerProvenanceStop(), retrieveAlgorithmSOAPOutputTypes(), and retrieveAlgortithmInfo().
checkForCloneExecution ($ runId)
This function will check if the ALGORTITHM_RUN with id $runId has a 'clone' (i.e. the execution of the same algorithm with the exact same input parameters)
Parameters:
[in] $runId
Returns:
the ALGORTITHM_RUN.id of a clone if one exists
Behavior is undefined if multiple clones exist, but a valid id will allways be returned in that case.
Todo:
Finding the clone executions is currently only partially working. Since the framework doesn't register foreign input parameters, and since we can have optional parameters as well, there is an ambiguity as to know whether an algorithm was run with default arguments or whether some of these arguments were exeternal parameters.
Definition at line 864 of file dae_service_algorithms.inc.
References getDAEDatabase().
Referenced by callback().
createDataItem ($ data, $ dataType, $ flag)
Enter description here ...
Parameters:
unknown_type $data
unknown_type $dataType
unknown_type $flag
Todo:
This function should also register a standard Copyright value.
Todo:
Associate contributor information to newly generated data using the 'contribute' relation
Definition at line 62 of file dae_service_algorithms.inc.
References getDAEDatabase().
Referenced by registerDataItem().
files_identical ($ fn1, $ fn2)
The following code was taken from http://php.net/manual/en/function.md5-file.php
Enter description here ...
Parameters:
unknown_type $fn1
unknown_type $fn2
Definition at line 22 of file dae_service_algorithms.inc.
Referenced by findDataItemToRegister().
findDataItemToRegister ($ dataType, $ dataTypeId, $ dataId, $ value, $ runId)
This function is called when a registered web service is executed. It is called once for each individual input argument to the web service.
The input parameters of this fuction define the given input argument to the web service. It checks whether the argument is already existant (registered) in the DAE database and returns its data_item.id value if it is. The function returns -1 if the argument is currently unregistered in the database.
Parameters:
string $dataType contains the class of data (page_image, files, argument ...) as per datatype.data_item_type
integer $dataTypeId contains the ID of the datatype under consideration
integer $dataId contains the ID of the data under consideration
mixed $value contains the value of the data_item under consideration
integer $runId the Oracle database identifier of the currenr algorithm run
Returns:
the data_item.id value if the specified parameters correspond to an existing object in the DAE database; returns -1 if they don't correspond to an existing object; returns NULL if an error occurs.
Todo:
find out what to do when algorithms are run on remote data and how to store the information
One of the possible things would be to check if the referenced image path (URL) is already stored in the database. Register it if it isn't, and then use it as a local reference.
The major question here is 'Copyright'. Although we do not store the image locally (only the URL pointing to it) derived content may eventually get stored.
Also, there is no guarantee that the referenced URL remains accessible for the remaining duration of the whole platform's life.
Todo:
Make '/dae/database' appear somewhere in the configuration variables
Second -
Todo:
check its type validity
The data_item is present in the database but has no registered links with the required data or datatype values
Todo:
decide on a coherent policy to handle strangely referenced inputs.
Currently we'll just log a message and return the id
This configuration should be impossible ... how can a registered algorithm argument not belong to a valid 'dataType' ?
Currently we're assuming in this case that this means that the argument is of type 'argument'
Todo:
implement the 'argument' insertion when running an algorithm.
Todo:
raise an exception
Definition at line 277 of file dae_service_algorithms.inc.
References files_identical(), getDAEDatabase(), and localCopy().
Referenced by registerProvenanceStart().
hook_algorithm ($ aid, $ aname, $ args1, $ args2 = null)
Looks for and calls hooks for the specified algorithm based on both the name of the algorithm and the algorithm's ID.
Example: For $aid = 124 and $aname = "Kanungo Degradation_1.0", this function will call hook_124 AND hook_kanungo_degradation_1_0. Keep this in mind when writing functions.
Parameters:
[in] $aid - the integer ID of the algorithm
[in] $aname - the name of the algorithm with _<version>
[in] $args1 - argument(s) for the hook function hook_<name> and hook_<id> if $args2 is not specified
[in] $args2 - argument(s) for the hook function if different for hook_<id>
Returns:
true if a hook is called, false if no hook is found
Definition at line 812 of file dae_service_algorithms.inc.
Referenced by callback().
localCopy ($ value, $ localname)
This is a workaround to some restriction on the Solaris CSW PhP version, not being able to have remote copy() execution. This fuction copies $value (presumably remote, but not necessary) to $localname. It first tries to invoke the standard copy() function. If that fails it makes a call to wget using a system() call.
Parameters:
[in] $value
[in] $localname
Returns:
Name of localy created file
Todo:
Make this function a bit more secure by checking the parameters correctly, as well as checking the correct execution and the result of each step.
Note that the "allow_url_fopen = On" should be set in php.ini for copy to work accross the network (and even then you still can get surprises)
Todo:
Get rid of this hard coded /opt/csw/bin path
Definition at line 103 of file dae_service_algorithms.inc.
Referenced by findDataItemToRegister(), registerDataItem(), and registerProvenanceStart().
registerDataItem ($ dataType, $ dataTypeId, $ dataId, $ value, $ remoteData = false)
Parameters:
string $dataType
integer $dataTypeId
integer $dataId
mixed $value
boolean $remoteData
Todo:
All folowing code should be put in coherence with existing Oracle triggers and procedures used for uploading datasets
Todo:
Make '/dae/database' appear somewhere in the configuration variables
Note that the "allow_url_fopen = On" should be set in php.ini for copy to work accross the network (and even then you still can get surprises)
Todo:
Check parameters for malevolant actions like passing /etc/passwd
Todo:
check whether this insert does not return any error !
Todo:
check whether this insert does not return any error !
Todo:
generate the thumbnails in the database
Todo:
Also store the 'mime' field obtained from getimagesize as a datatype associated to the page_image
Todo:
Manage page_element insertion after execution
Todo:
All folowing code should be put in coherence with existing Oracle triggers and procedures used for uploading datasets
Todo:
Make '/dae/database' appear somewhere in the configuration variables
Todo:
Check parameters for malevolant actions like passing /etc/passwd
Todo:
Manage dataset insertion after execution
Todo:
Manage page_element_property_value insertion after execution
Definition at line 136 of file dae_service_algorithms.inc.
References createDataItem(), getDAEDatabase(), and localCopy().
Referenced by registerProvenanceStop().
registerProvenanceFailure ($ inserted_id, $ algoId)
Parameters:
[in] $insertedId
[in] $algoId
Definition at line 718 of file dae_service_algorithms.inc.
References getDAEDatabase().
Referenced by callback().
registerProvenanceStart ($ algoId, &$ callParameters, $ quarantainedExecutionProxy = null)
Registers all provenance information with respect of the staring of a run of the algorithm defined by $algoId and with input parameters $callParameters.
This function will check if the $callParameters are already present in the DAE Oracle database, and will update the following tables:
ALGORITHM_RUN
ALGORITHM_RUN_OF
EXECUTES_RUN
ALGORITHM_RUN_INPUT
INPUT_CONFIGURATION
Todo:
Currently, the INSTANCE_OF table is not updated.
Currently, input data of type dataset, page_element, page_element_property_value are not handled appropriately (actually ... they are ignored)
If execution is to be quarantained, the input data referenced in $callParameters is copied to the quarantaine exchange area, and paths/URLs in $callParameters are updated accordingly.
Parameters:
[in] $algoId string indentifier of algorithm being run
[in,out] $callParameters mixed associative array of input values, indexed by DATA.id
[in] $quarantainedExecutionProxy boolean (default = NULL) flag indicating if execution is quarantained
Todo:
We're assuming here there will be at most one row returned by this query (i.e. any data has at most one datatype) We should check if this is always true !
Todo:
Adapt to new data model with input_configuration and remove references to ALGORITHM_RUN_INPUT (obsoleted)
Todo:
Check existence in INSTANCE_OF table and update with following instruction if necessary (i.e. not already present)
Definition at line 581 of file dae_service_algorithms.inc.
References $user, findDataItemToRegister(), getDAEDatabase(), getPID(), and localCopy().
Referenced by callback().
registerProvenanceStop ($ inserted_id, $ algoId, &$ callParameters)
Parameters:
[in] $insertedId
[in] $algoId
[in/out] &$callParameters
Todo:
Getting this function right is far more complex than it might seem. One has to take into account two kinds of situations. The first case concerns all-local input data; in which case output data should be stored into the data base with full provenance. The second case is partially local data or completely external data (non-locally hosted), in which case it is tricky to store the results and full provenance (mainly for Copyright reasons).
Todo:
We're assuming here there will be at most one row returned by this query (i.e. any data has at most one datatype) We should check if this is always true !
Todo:
Adapt to new data model with input_configuration and remove references to ALGORITHM_RUN_OUTPUT (obsoleted)
Todo:
Check existence in INSTANCE_OF table and update with following instruction if necessary (i.e. not already present)
Definition at line 740 of file dae_service_algorithms.inc.
References getDAEDatabase(), and registerDataItem().
Referenced by callback().
Variable Documentation
global $db
Access a DAE algorithm by wsdl.
Definition at line 8 of file dae_service_algorithms.inc.