DAEDrupalInterface: modules/services/dae_convert/dae_service_convert.inc File Reference
modules/services/dae_convert/dae_service_convert.inc File Reference
Functions
createDataItem ($data, $dataType, $flag)
registerDataItem ($dataType, $dataTypeId, $dataId, $value)
findDataItemToRegister ($dataType, $dataTypeId, $dataId, $value)
registerProvenanceStart ($algoId, $callParameters)
registerProvenanceStop ($insertedId, $algoId, &$callParameters)
callback ($fields=array())
Variables
global $db
Function Documentation
callback ($ fields = array())
Call a remote web service.
Parameters:
array $fields parameters
Returns:
algorithm outputs
Todo:
the database retrieved Input/Output parameters should be checked to the published WSDL information
Todo:
We're assuming all array keys are unique ... check if this is actually the case 100% of the time
Todo:
We're assuming composite types only have one component ... check if this is actually the case 100% of the time
Todo:
check for possible execution failures of the above webservice call.
Todo:
We're assuming all array keys are unique ... check if this is actually the case 100% of the time
Todo:
Check following 2 lines of code... it looks like there's some redundancy here
Todo:
We're assuming composite types only have one component ... check if this is actually the case 100% of the time
Definition at line 515 of file dae_service_convert.inc.
References $client, $err, $outputT, $result, getDAEDatabase(), registerProvenanceStart(), registerProvenanceStop(), retrieveAlgorithmSOAPOutputTypes(), and retrieveAlgortithmInfo().
createDataItem ($ data, $ dataType, $ flag)
Enter description here ...
Parameters:
unknown_type $data
unknown_type $dataType
unknown_type $flag
Todo:
This function should also register a standard Copyright value.
Todo:
Associate contributor information to newly generated data using the 'contribute' relation
Definition at line 23 of file dae_service_convert.inc.
References getDAEDatabase().
findDataItemToRegister ($ dataType, $ dataTypeId, $ dataId, $ value)
Parameters:
string $dataType
integer $dataTypeId
integer $dataId
mixed $value
Todo:
find out what to do when algorithms are run on remote data and how to store the information
One of the possible things would be to check if the referenced image path (URL) is already stored in the database. Register it if it isn't, and then use it as a local reference.
The major question here is 'Copyright'. Although we do not store the image locally (only the URL pointing to it) derived content may eventually get stored.
Also, there is no guarantee that the referenced URL remains accessible for the remaining duration of the whole platform's life.
Second -
Todo:
check its type validity
The data_item is present in the database but has no registered links with the required data or datatype values
Todo:
decide on a coherent policy to handle strangely referenced inputs.
Currently we'll just log a message and return the id
Todo:
create a new 'argument' data_item with all corresponding datatype links.
This configuration should be impossible ... how can a registered algorithm argument not belong to a valid 'dataType' ?
Currently we're assuming in this case that this means that the argument is of type 'argument'
Todo:
implement the 'argument' insertion when running an algorithm.
Todo:
raise an exception
Definition at line 181 of file dae_service_convert.inc.
References getDAEDatabase().
registerDataItem ($ dataType, $ dataTypeId, $ dataId, $ value)
Parameters:
string $dataType
integer $dataTypeId
integer $dataId
mixed $value
Todo:
All folowing code should be put in coherence with existing Oracle triggers and procedures used for uploading datasets
Todo:
Make '/dae/database' appear somewhere in the configuration variables
Note that the "allow_url_fopen = On" should be set in php.ini for copy to work accross the network (and even then you still can get surprises)
Todo:
Get rid of this hard coded /opt/csw/bin path
Todo:
check whether this insert does not return any error !
Todo:
check whether this insert does not return any error !
Todo:
generate the thumbnails in the database
Todo:
Also store the 'mime' field obtained from getimagesize as a datatype associated to the page_image
Todo:
Manage page_element insertion after execution
Todo:
All folowing code should be put in coherence with existing Oracle triggers and procedures used for uploading datasets
Todo:
Make '/dae/database' appear somewhere in the configuration variables
Todo:
Manage dataset insertion after execution
Todo:
Manage page_element_property_value insertion after execution
Definition at line 45 of file dae_service_convert.inc.
References createDataItem(), and getDAEDatabase().
registerProvenanceStart ($ algoId, $ callParameters)
Parameters:
[in] $algoId string
[in] $callParameters mixed
Todo:
We're assuming here there will be at most one row returned by this query (i.e. any data has at most one datatype) We should check if this is always true !
Todo:
Adapt to new data model with input_configuration and remove references to ALGORITHM_RUN_INPUT (obsoleted)
Todo:
Check existence in INSTANCE_OF table and update with following instruction if necessary (i.e. not already present)
Definition at line 391 of file dae_service_convert.inc.
References $i, $row, $user, findDataItemToRegister(), and getDAEDatabase().
registerProvenanceStop ($ insertedId, $ algoId, &$ callParameters)
Parameters:
[in] $insertedId
[in] $algoId
[in/out] &$callParameters
Todo:
Getting this function right is far more complex than it might seem. One has to take into account two kinds of situations. The first case concerns all-local input data; in which case output data should be stored into the data base with full provenance. The second case is partially local data or completely external data (non-locally hosted), in which case it is tricky to store the results and full provenance (mainly for Copyright reasons).
Todo:
We're assuming here there will be at most one row returned by this query (i.e. any data has at most one datatype) We should check if this is always true !
Todo:
Adapt to new data model with input_configuration and remove references to ALGORITHM_RUN_OUTPUT (obsoleted)
Todo:
Check existence in INSTANCE_OF table and update with following instruction if necessary (i.e. not already present)
Definition at line 459 of file dae_service_convert.inc.
References $i, $row, getDAEDatabase(), and registerDataItem().
Variable Documentation
global $db
Access a DAE algorithm by wsdl.
Definition at line 8 of file dae_service_convert.inc.