DAEDrupalInterface: modules/dae_data/dae_data_query_client.inc File Reference
modules/dae_data/dae_data_query_client.inc File Reference
Functions
query_client ()
query_preview ()
my_set_int_type ($arr)
genSQL ($lim, $opitList, $odsList, $opetList, $opepList, $opevList, $fpit, $fds, $fpet, $fpep)
idstr2arr ($idstr)
valstr2arr ($valstr)
my_codec ($str)
Function Documentation
genSQL ($ lim, $ opitList, $ odsList, $ opetList, $ opepList, $ opevList, $ fpit, $ fds, $ fpet, $ fpep)
Definition at line 100 of file dae_data_query_client.inc.
References my_set_int_type().
Referenced by dae_query_pageimage(), query_preview(), and sel2().
idstr2arr ($ idstr)
Definition at line 255 of file dae_data_query_client.inc.
Referenced by query_client(), query_form(), and query_preview().
my_codec ($ str)
Definition at line 282 of file dae_data_query_client.inc.
Referenced by valstr2arr().
my_set_int_type ($ arr)
Definition at line 90 of file dae_data_query_client.inc.
Referenced by genSQL().
query_client ()
Definition at line 2 of file dae_data_query_client.inc.
References $client, $result, $user, $wsdl, idstr2arr(), and valstr2arr().
query_preview ()
Definition at line 66 of file dae_data_query_client.inc.
References genSQL(), idstr2arr(), and valstr2arr().
valstr2arr ($ valstr)
Definition at line 267 of file dae_data_query_client.inc.
References my_codec().
Referenced by query_client(), and query_preview().