DAEDrupalInterface: modules/dae_data/dae_data_upload_file.inc File Reference
modules/dae_data/dae_data_upload_file.inc File Reference
Functions
dae_data_upload ()
dae_data_upload_submit ($form_id, $form_values)
dae_data_upload_page ($form_state=NULL)
dae_data_upload_validate ($form_id, $form_values)
Detailed Description
Author:
Bart Lamiroy lamir.nosp@m.oy@c.nosp@m.se.le.nosp@m.high.nosp@m..edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_data_upload_file.inc.
Function Documentation
dae_data_upload ()
Implementation of upload.
Definition at line 34 of file dae_data_upload_file.inc.
References $user.
dae_data_upload_page ($ form_state = NULL)
Definition at line 553 of file dae_data_upload_file.inc.
dae_data_upload_submit ($ form_id, $ form_values)
Implementation of upload submit.
Definition at line 300 of file dae_data_upload_file.inc.
References $db, $user, getDAEDatabase(), getPID(), and home_directory_upload_rename().
dae_data_upload_validate ($ form_id, $ form_values)
Definition at line 582 of file dae_data_upload_file.inc.
References $db, and getDAEDatabase().