DAEDrupalInterface: modules/services/dae_algorithms/dae_service_algorithms_helper_functions.inc File Reference
modules/services/dae_algorithms/dae_service_algorithms_helper_functions.inc File Reference
Functions
create_thumbnails ($file)
hook_ocrad_0_21_2 ($args=array())
hook_ocrad_0_19 ($args=array())
generic_hook_ocrad ($args=array())
hook_convert_6_6_0_4 ($args=array())
hook_convert_6_4_6 ($args=array())
generic_hook_convert ($args=array())
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file dae_service_algorithms_helper_functions.inc.
Function Documentation
create_thumbnails ($ file)
ADDING ALGORITHM HOOKS:
There are two flavors of hooks, those based on ID, and those based on name. By their nature, hooks by ID will only be called for the exact algorithm, while hooks by name can refer multiple versions of an algorithm assuming all of them have the same name in the database.
Hooks by name may be more flexible accross databases where IDs are arbitrary.
Currently, BOTH hooks are called, so if you hook convert and 102 (convert's ID) both will be run.
ARGUMENTS:
  Hooks get one argument which is an array of information.
Todo:
add what is in the array as necessary
FORMAT:
By name: hook_<name>_<version> "hook_kanungo_degradation_1_0($arguments)" where name is entirely lowercase and all non-alphanumeric have been replaced with underscores.
By id: hook_<id> "hook_124($arguments)"
Definition at line 61 of file dae_service_algorithms_helper_functions.inc.
Referenced by generic_hook_convert().
generic_hook_convert ($ args = array())
Definition at line 154 of file dae_service_algorithms_helper_functions.inc.
References $db, create_thumbnails(), and getDAEDatabase().
Referenced by hook_convert_6_4_6(), and hook_convert_6_6_0_4().
generic_hook_ocrad ($ args = array())
Definition at line 86 of file dae_service_algorithms_helper_functions.inc.
References $db, $user, getDAEDatabase(), and getPID().
Referenced by hook_ocrad_0_19(), and hook_ocrad_0_21_2().
hook_convert_6_4_6 ($ args = array())
Definition at line 150 of file dae_service_algorithms_helper_functions.inc.
References generic_hook_convert().
hook_convert_6_6_0_4 ($ args = array())
This function hooks the convert algorithm (v 6.4.6)
Definition at line 146 of file dae_service_algorithms_helper_functions.inc.
References generic_hook_convert().
hook_ocrad_0_19 ($ args = array())
Definition at line 82 of file dae_service_algorithms_helper_functions.inc.
References generic_hook_ocrad().
hook_ocrad_0_21_2 ($ args = array())
This function hooks the ocrad algorithm (v 0.19)
Definition at line 78 of file dae_service_algorithms_helper_functions.inc.
References generic_hook_ocrad().