DAEDrupalInterface: modules/dae_annotations/dae_annotations.module File Reference
modules/dae_annotations/dae_annotations.module File Reference
Functions
dae_annotations_menu ()
dae_annotations_perm ()
dae_annotation_ui_params ($aid)
getAnnotationInfo ($aid)
annotationNameExists ($n)
annotation_specification ()
annotation_sql_query ($sql, $itemNo=null)
annotation_sql_query_count ($sql)
annotation_sql ()
canEdit ($aid)
Function Documentation
annotation_specification ()
AJAX callback to retrieve annotation task XML spec
Definition at line 134 of file dae_annotations.module.
annotation_sql ()
JSON callback to retrieve query results
Definition at line 172 of file dae_annotations.module.
annotation_sql_query ($ sql, $ itemNo = null)
Runs the user created sql query
Definition at line 147 of file dae_annotations.module.
Referenced by dae_annotation_ui_params(), and display_annotation().
annotation_sql_query_count ($ sql)
Definition at line 163 of file dae_annotations.module.
Referenced by display_annotation(), and get_user_annotations().
annotationNameExists ($ n)
Definition at line 116 of file dae_annotations.module.
References $user.
canEdit ($ aid)
Checks to see if the current user is allowed to edit
Todo:
only checks for creator
Definition at line 183 of file dae_annotations.module.
Referenced by edit_annotation_info(), and edit_annotation_ui().
dae_annotation_ui_params ($ aid)
Sets params for creating the annotation tsk building tool.
Parameters:
string {$name} the annotation name
int {$dataitem} the dataitem id $param bool {$exists} false if this is a new ui, true if editing an existing ui
Definition at line 81 of file dae_annotations.module.
References annotation_sql_query(), and getAnnotationInfo().
Referenced by edit_annotation_ui().
dae_annotations_menu ()
Definition at line 3 of file dae_annotations.module.
dae_annotations_perm ()
Definition at line 69 of file dae_annotations.module.
getAnnotationInfo ($ aid)
Definition at line 107 of file dae_annotations.module.
Referenced by dae_annotation_ui_params(), and edit_annotation_info().