DAEDrupalInterface: modules/daedatabase/daedatabase_db.inc File Reference
modules/daedatabase/daedatabase_db.inc File Reference
Provides access to Oracle and MySQL database functions and data structures in a transparent way.
Classes
class DAEDatabase
Generic class, providing all database interaction functions.
class DAEMySQLDatabase
class DAEOracleDatabase
Functions
getDAEDatabase ()
Get access to the current DAEDatabase instance.
retrieveAlgortithmInfo ($algoId)
Generates an array representing the signature of the algorithm the ID of which was specified in $algoId.
retrieveAlgorithmSOAPOutputTypes ($algoId, $prefix="#")
retrieveAlgorithmSOAPInputTypes ($algoId, $prefix="", $nameSpace="", $numbering=false)
Generates an array containing the SOAP-compatible representation of all input parameters of the algorithm the ID of which was specified in $algoId.
databaseDebugMessage ($msg, $stacktrace=false)
Runtime debug message handler.
Detailed Description
Provides access to Oracle and MySQL database functions and data structures in a transparent way.
Author:
Bart Lamiroy lamir.nosp@m.oy@c.nosp@m.se.le.nosp@m.high.nosp@m..edu
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
The most important part of this module is the DAEDatabase class. This is the main API that allows a programmer to take advantage of any DBMS without having to change his or her code. This class is further derived into sub-classes that actually implement the core access functions to specific DBMSs like Oracle and MySQL.
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file daedatabase_db.inc.
Function Documentation
databaseDebugMessage ($ msg, $ stacktrace = false)
Runtime debug message handler.
This function can be used un a running server without polluting the regular users. It is controlled by the 'debug DAE Database' Drupal user access policy.
Parameters:
$msg Message to be displayed
$stacktrace flag determining whether to dump the call stack as well
Definition at line 978 of file daedatabase_db.inc.
Referenced by DAEMySQLDatabase\__construct(), DAEOracleDatabase\__construct(), algorithm_execute(), data_repository_display(), DAEMySQLDatabase\fetch_array(), DAEDatabase\fetch_row(), DAEDatabase\field_name(), DAEDatabase\getDAEDatabase(), DAEDatabase\i(), DAEDatabase\num_fields(), DAEMySQLDatabase\q(), DAEOracleDatabase\q(), DAEDatabase\r(), run_102(), run_124(), run_125(), run_143(), run_82(), run_XX(), sql_service(), and DAEOracleDatabase\u().
getDAEDatabase ()
Get access to the current DAEDatabase instance.
Returns:
the DAEDatabase singleton.
Definition at line 53 of file daedatabase_db.inc.
References DAEDatabase\getDAEDatabase().
Referenced by Person\__construct(), algorithm_execute(), algorithms_copy_make_dest_dir(), algorithms_delete_access(), algorithms_delete_run_files(), algorithms_get_database_run_info_done(), algorithms_get_home_folder_run_info_done(), algorithms_get_run_info_working(), algorithms_get_run_input_filename(), algorithms_list(), algorithms_my_runs(), algorithms_run(), algorithms_run_choose(), algorithms_run_done(), algorithms_run_form(), algorithms_run_form_submit(), algorithms_run_get_status(), algorithms_run_go(), algorithms_run_title(), basicInfo(), callback(), check_comment_id(), check_version_page(), checkForCloneExecution(), createDataItem(), ct_select_content(), ct_select_sub1_content(), ct_select_sub2_content(), dae_data_browse(), dae_data_browse_dataitem_rate(), dae_data_browse_dataset_comment_rate(), dae_data_browse_dataset_dataitem_build(), dae_data_browse_dataset_file(), dae_data_browse_dataset_page_element(), dae_data_browse_dataset_page_image(), dae_data_browse_get_results(), dae_data_browse_runoptions(), dae_data_browse_subset(), dae_data_browse_tree(), dae_data_build_page_image_list(), dae_data_comment_rating_exists(), dae_data_copy(), dae_data_copyright(), dae_data_download(), dae_data_download_before(), dae_data_get_activity(), dae_data_get_array_of_paths(), dae_data_get_dataset_hierarchy(), dae_data_get_dataset_info_array(), dae_data_get_dataset_leaves(), dae_data_get_download_size(), dae_data_get_file_info_array(), dae_data_get_file_path(), dae_data_get_page_element_info_array(), dae_data_get_page_image_path(), dae_data_get_pageimage_info_array(), dae_data_get_paths_from_result(), dae_data_get_tags(), dae_data_get_thumb_path(), dae_data_get_thumb_uri(), dae_data_increment_activity(), dae_data_is_image(), dae_data_page_element_form_submit(), dae_data_page_element_type_search(), dae_data_search_page_select(), dae_data_search_page_submit(), dae_data_search_results_page(), dae_data_search_select(), dae_data_search_tag(), dae_data_search_tags(), dae_data_tag_add_assoc(), dae_data_tag_form_submit(), dae_data_upload_submit(), dae_data_upload_validate(), dae_dataset_page(), dae_dataset_preview(), dae_file_page(), dae_page_element_page(), dae_pageimage_page(), dae_query_pageimage(), dae_service_algorithms_service(), dae_service_ocrad(), data_repository_display(), data_repository_queryurl(), dataitem_service_descript(), findDataItemToRegister(), generic_hook_convert(), generic_hook_ocrad(), get_comment_information(), get_dataitem_comments(), get_dataitem_submitter(), getAlgName(), getAllAlgIdName(), getDescById(), getExists(), getNameById(), getNextPID(), getPIDByEmail(), home_directory_user(), insertPersonInfo(), IOpart(), DatasetPage\list_builder_datasets(), registerDataItem(), registerProvenanceFailure(), registerProvenanceStart(), registerProvenanceStop(), retrieveAlgorithmSOAPInputTypes(), retrieveAlgorithmSOAPOutputTypes(), retrieveAlgortithmInfo(), run_on_database(), save_type(), sel1(), sel2(), show_stat_block(), soap_server(), sql_service(), updatePersonInfo(), and validatePreSelected().
retrieveAlgorithmSOAPInputTypes ($ algoId, $ prefix = "", $ nameSpace = "", $ numbering = false)
Generates an array containing the SOAP-compatible representation of all input parameters of the algorithm the ID of which was specified in $algoId.
Parameters:
[in] $algoId
[in] $prefix
Returns:
a NuSoap compatible array of input parameters for algorithm $algoId.
Definition at line 914 of file daedatabase_db.inc.
References $db, and getDAEDatabase().
Referenced by soap_server().
retrieveAlgorithmSOAPOutputTypes ($ algoId, $ prefix = "#")
Definition at line 874 of file daedatabase_db.inc.
References $db, and getDAEDatabase().
Referenced by callback(), and soap_server().
retrieveAlgortithmInfo ($ algoId)
Generates an array representing the signature of the algorithm the ID of which was specified in $algoId.
Parameters:
[in] $algoId
Returns:
an associative array containing the fields NAME, VERSION and DESCRIPTION of algorithm $algoId.
Definition at line 866 of file daedatabase_db.inc.
References $db, and getDAEDatabase().
Referenced by callback(), and dae_service_algorithms_service().