DAEDrupalInterface: modules/data_repository/data_repository.inc File Reference
modules/data_repository/data_repository.inc File Reference
Functions handling raw SQL interaction with the backend data base through Drupal.
Functions
data_repository_query ()
Drupal menu callback for Repository as declared in data_repository_menu()
data_repository_sql_submit ($form, &$form_state)
Standard Drupal form submit callback function.
data_repository_display ()
Drupal menu callback for Repository/SQL as declared in data_repository_menu()
data_repository_sql ($form_state)
Form definition function for SQL query input.
data_repository_queryurl ()
Detailed Description
Functions handling raw SQL interaction with the backend data base through Drupal.
Author:
Bart Lamiroy lamir.nosp@m.oy@c.nosp@m.se.le.nosp@m.high.nosp@m..edu
Date:
May 2010
Version:
1.0
This file contains all necessary code to implement the Data Repository Module which allows authorized Drupal users to interact directly with the backend data base management system using raw, unfiltered SQL.
Users need to have the Drupal 'raw DAE database access' access rights set.
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file data_repository.inc.
Function Documentation
data_repository_display ()
Drupal menu callback for Repository/SQL as declared in data_repository_menu()
Requires Drupal user to have 'raw DAE database access' access rights.
Todo:
Make the HTML disply more appealing and efficient. Current version can be fery slow and memory consuming on queries with very large output. Might be a good idea to have a generic way of handling bulky query outputs all over the project
Todo:
Using OCI_LOB->load() is a OCI specific hack, and does not use the generic dae_database API. This should be corrected in future releases
Definition at line 88 of file data_repository.inc.
References $db, data_repository_query(), databaseDebugMessage(), and getDAEDatabase().
data_repository_query ()
Drupal menu callback for Repository as declared in data_repository_menu()
Creates a $_SESSION variable for memorizing cross-page query inputs.
Displays the form defined in data_repository_sql().
Drupal automagically attaches data_repository_sql_submit() as the form submit callback.
Definition at line 46 of file data_repository.inc.
Referenced by data_repository_display().
data_repository_queryurl ()
This function transforms URLs in the form of query/table/column/value into select ID from TABLE where COLUMN like 'VALUE';
Todo:
This function currently doesn't check whether ID exists in requested table
Definition at line 215 of file data_repository.inc.
References $db, and getDAEDatabase().
data_repository_sql ($ form_state)
Form definition function for SQL query input.
The form contains only two fields:
a textarea field named 'query'
a submit button named 'submit'
Parameters:
[in] $form_state
Returns:
a Drupal form array.
Checks whether there is a previously known form entry for the query. If true, then pre-fill the form with this query. If not pre-fill the form with a default query.
Definition at line 185 of file data_repository.inc.
data_repository_sql_submit ($ form, &$ form_state)
Standard Drupal form submit callback function.
Redirects the handling of the form submission to 'Repository/SQL', handled by the data_repository_display() callback.
Parameters:
[in] $form Drupal form structure
[in] $form_state form contents
use of _SESSION variables is necessary since globals are only valid within the scope of a page. In our case we have Repository and Repository/SQL being two different pages. Globals are therefore not propagated
Definition at line 70 of file data_repository.inc.