DAEDrupalInterface: modules/home_directory/home_directory_run_folder.inc File Reference
modules/home_directory/home_directory_run_folder.inc File Reference
Functions
home_directory_copy_to_runs ($run, $folder="")
Copies files from a spool directory to the user's run directory.
home_directory_delete_runs_folders ($run, $folder="")
Recursively deletes all the directories in the spool run folder.
home_directory_create_run_zip ($run)
Create a zip file containing all result files of a given run.
Detailed Description
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file home_directory_run_folder.inc.
Function Documentation
home_directory_copy_to_runs ($ run, $ folder = "")
Copies files from a spool directory to the user's run directory.
This function requires the global variables $runs and $spool to be set to the appropriate directories
Increases user's used storage space as it copies files and directory structure
Parameters:
$run the run id.
$folder used for recursive deletes. Not necessary on initial call
Definition at line 40 of file home_directory_run_folder.inc.
References $user, hd_scandir(), and home_directory_change_usage().
home_directory_create_run_zip ($ run)
Create a zip file containing all result files of a given run.
This function requires the global variable $runs to be set to the appropriate directory and takes the assumption that $runs/$run/output is a valid and writeable path.
If the zip file is created, the function updates the user's file storage space usage.
Parameters:
$run the run id.
Definition at line 118 of file home_directory_run_folder.inc.
References home_directory_change_usage().
home_directory_delete_runs_folders ($ run, $ folder = "")
Recursively deletes all the directories in the spool run folder.
This function requires the global variable $spool to be set to the appropriate directory
Parameters:
$run the run id.
$folder used for recursive deletes. Not necessary on initial call
Definition at line 82 of file home_directory_run_folder.inc.
References hd_scandir().