DAEDrupalInterface: modules/home_directory/home_directory.module File Reference
modules/home_directory/home_directory.module File Reference
The home_directory module creates user directories and allows creation of subdirectories.
Functions
home_directory_menu ()
home_directory_perm ()
home_directory_user ($op, &$edit, &$account, $category=NULL)
getProfileValue ($uid, $profileField)
insertPersonInfo ($tblStr, $pid, $val, $uid, $profile_field)
updatePersonInfo ($tblStr, $pid, $val)
home_directory_content_type ($ext, $default="text/plain")
Returns a mimetype for a given file extension.
home_directory_get_filename_from_path ($file)
Get file extension from a filename.
home_directory_get_path_to_file_dir ($file)
Get the path to a file from the full filepath.
home_directory_get_file_extension ($file)
Get file extension from a filename.
home_directory_file_uploads_exists ($file)
Checks that a file exists in $uploads.
home_directory_fullsize ()
Gets a fullsize version of the image to display.
home_directory_thumb ()
callback for getThumb
home_directory_check_image ($ext)
Decides if a file extension is an image (for purpose of displaying thumb vs filetype icon)
home_directory_download ()
Callback for getFile.
home_directory_remove_file ($file)
Deletes a file in the user's uploads folder and updates user's usage.
home_directory_remove_directory ($dir, $subdir="")
Deletes a directory and the files inside while updating user storage.
hd_scandir ($dir)
Get a list of files in the given directory without . and ..
home_directory_commit ()
home_directory_make_directory ($dir, $fullPathtoDir, $recurse=false)
Takes a user's input for a directory name and sanitizes/avoids name conflicts.
home_directory_upload_rename ($path, $filename)
Renames files if the file already exists.
home_directory_dir_rename ($path, $dirName)
Used when creating directories to get a new name if the directory exists.
home_directory_change_usage ($amount)
Updates the current user's file storage amount.
Detailed Description
The home_directory module creates user directories and allows creation of subdirectories.
Author:
Mike Kot mdk31.nosp@m.2@le.nosp@m.high..nosp@m.edu
Version:
1.0
LICENSE
This file is part of the DAE Platform Project (DAE).
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file home_directory.module.
Function Documentation
getProfileValue ($ uid, $ profileField)
This function returns the profile value of the user in Drupal database
Parameters:
$uid Drupal user id
$profileField Drupal profile field name
Returns:
the corresponding person id (pid) in the Person table in the Oracle database.
Definition at line 198 of file home_directory.module.
References $result.
Referenced by home_directory_user().
hd_scandir ($ dir)
Get a list of files in the given directory without . and ..
Sets a watchdog message if the directory does not exist
Parameters:
$dir full path from root
Definition at line 564 of file home_directory.module.
Referenced by algorithms_get_home_folder_run_info_done(), algorithms_get_run_input_filename(), home_directory_copy_to_runs(), home_directory_delete_runs_folders(), and home_directory_remove_directory().
home_directory_change_usage ($ amount)
Updates the current user's file storage amount.
A user must be logged in
Parameters:
$amount integer amount in bytes
Definition at line 659 of file home_directory.module.
References $user.
Referenced by algorithms_copy(), algorithms_delete_run_files(), dae_data_copy_to_home_directory(), home_directory_copy_to_runs(), home_directory_create_run_zip(), home_directory_remove_file(), and home_directory_upload_submit().
home_directory_check_image ($ ext)
Decides if a file extension is an image (for purpose of displaying thumb vs filetype icon)
Uses setting in home directory settings
Parameters:
$ext the file extension without a period
Definition at line 443 of file home_directory.module.
Referenced by MyUploadsPage::getFiles(), and home_directory_thumb().
home_directory_commit ()
Definition at line 583 of file home_directory.module.
home_directory_content_type ($ ext, $ default = "text/plain")
Returns a mimetype for a given file extension.
Parameters:
$ext the file extension without a period
$default allows you to set a mimetype if the $ext is not found
Todo:
this should probably better be retrieved from the running environment rather than be application defined.
Definition at line 303 of file home_directory.module.
Referenced by home_directory_download(), and home_directory_thumb().
home_directory_dir_rename ($ path, $ dirName)
Used when creating directories to get a new name if the directory exists.
Adds _<number> until the directory does not exist
IMPORTANT: Assumes the directory name has already been sanitized.
Parameters:
$path full path from root
$dirName the sanitized directory name you would like to try
Definition at line 640 of file home_directory.module.
Referenced by home_directory_make_directory().
home_directory_download ()
Callback for getFile.
Assumes $uploads and $runs are set
Parameters:
arg(1) the place to download from (uploads, runs or tmp)
arg(2...) the rest of the args are the path to the download relative to arg(1)
Definition at line 455 of file home_directory.module.
References $uploads, $user, home_directory_content_type(), and home_directory_get_file_extension().
home_directory_file_uploads_exists ($ file)
Checks that a file exists in $uploads.
Assumes $uploads is set and globally available. Paths relative to $uploads are fine
Parameters:
$file the file with path relative to user's $uploads
Definition at line 375 of file home_directory.module.
References $uploads.
Referenced by home_directory_run_batch().
home_directory_fullsize ()
Gets a fullsize version of the image to display.
Assumes $uploads is set and globally available
Parameters:
$file the file with path relative to user's $uploads
Todo:
replace with code for thumb before changing thumb
Definition at line 389 of file home_directory.module.
References home_directory_thumb().
home_directory_get_file_extension ($ file)
Get file extension from a filename.
Parameters:
$file the filename. Paths are ok as long as there is a file name with a .
Definition at line 362 of file home_directory.module.
Referenced by MyUploadsPage::getFiles(), home_directory_download(), and home_directory_thumb().
home_directory_get_filename_from_path ($ file)
Get file extension from a filename.
Parameters:
$file the filename. Paths are ok as long as there is a file name with a .
Definition at line 336 of file home_directory.module.
Referenced by home_directory_run_batch().
home_directory_get_path_to_file_dir ($ file)
Get the path to a file from the full filepath.
Parameters:
$file the full file path
Definition at line 348 of file home_directory.module.
Referenced by home_directory_run_batch().
home_directory_make_directory ($ dir, $ fullPathtoDir, $ recurse = false)
Takes a user's input for a directory name and sanitizes/avoids name conflicts.
Replaces anything but letters and numbers with underscores
Uses home_directory_dir_rename to fix conflicting names
Parameters:
$dir the user input for the name of the directory
$fullPathtoDir the path from root to the directory (not including the directory)
$recurse doesn't do anything right now
Todo:
allow directories to be recursively created
Definition at line 599 of file home_directory.module.
References home_directory_dir_rename().
Referenced by algorithms_copy_make_dest_dir(), dae_data_copy_to_home_directory(), and home_directory_mkdir_submit().
home_directory_menu ()
Implementation of hook_menu().
Temporarily deactivating personal upload directory
Definition at line 37 of file home_directory.module.
home_directory_perm ()
Implementation of hook_perm().
Definition at line 112 of file home_directory.module.
home_directory_remove_directory ($ dir, $ subdir = "")
Deletes a directory and the files inside while updating user storage.
Assumes $uploads is set and globally available
Parameters:
$dir the directory to delete
$subdir used for recursing by the function
Definition at line 534 of file home_directory.module.
References $uploads, hd_scandir(), and home_directory_remove_file().
Referenced by home_directory_run_batch().
home_directory_remove_file ($ file)
Deletes a file in the user's uploads folder and updates user's usage.
Assumes $uploads is set and globally available
Parameters:
$file the file with path relative to user's $uploads
Definition at line 515 of file home_directory.module.
References $uploads, and home_directory_change_usage().
Referenced by home_directory_remove_directory(), and home_directory_run_batch().
home_directory_thumb ()
callback for getThumb
Assumes $uploads is set and globally available
Parameters:
arg(1...) the path to the file (and thumbnail) relative to $uploads
Todo:
make it actually get thumbs instead of fullsize
Definition at line 402 of file home_directory.module.
References $uploads, home_directory_check_image(), home_directory_content_type(), and home_directory_get_file_extension().
Referenced by home_directory_fullsize().
home_directory_upload_rename ($ path, $ filename)
Renames files if the file already exists.
Uses the format <original-name>_1.<original-extension> and increments until file does not exist
IMPORTANT: Assumes the filename has already been sanitized
Parameters:
$path full path from root
$filename the sanitized filename you would like to try to make
Definition at line 619 of file home_directory.module.
Referenced by dae_data_upload_submit(), dae_metadata_upload_submit(), and home_directory_upload_submit().
home_directory_user ($ op, &$ edit, &$ account, $ category = NULL)
Implementation of hook_user().
Makes a user's uploads and runs directories. Also adds user to oracle database and creates a user storage row in the drupal MySQL db
Definition at line 124 of file home_directory.module.
References $db, getDAEDatabase(), getNextPID(), getPID(), getPIDByEmail(), getProfileValue(), insertPersonInfo(), and updatePersonInfo().
insertPersonInfo ($ tblStr, $ pid, $ val, $ uid, $ profile_field)
This function is called when a new user registers at Drupal to save one of the user's profile values into the corresponding Oracle database.
Parameters:
$tblStr the string of the Oracle database table corresponding to the profile field
$pid the Person ID in Oracle database
$val the value of the profile field
$uid the user ID in Drupal
$profile_field Drupal profile field name
Definition at line 215 of file home_directory.module.
References $db, and getDAEDatabase().
Referenced by home_directory_user().
updatePersonInfo ($ tblStr, $ pid, $ val)
This function is called when an existing user updates his profile to save one of the user's profile values into the corresponding Oracle database.
Parameters:
$tblStr the string of the Oracle database table corresponding to the profile field
$pid the Person ID in Oracle database
$val the value of the profile field
Definition at line 262 of file home_directory.module.
References $db, and getDAEDatabase().
Referenced by home_directory_user().