DAEDrupalInterface: modules/services/examples/authenticated_service/soap_server_test.php File Reference
modules/services/examples/authenticated_service/soap_server_test.php File Reference
Variables
$wsdl = 'http://localhost/dae/?q=services/soap'
$client = new nusoap_client($wsdl, false)
$user = NULL
$client debug_flag = true
$input = array('name' => array('page_image' => 'testPara'))
$input ['username'] = 'admin'
$input ['password'] = 'daepassword'
$result = $client->call('dae.ocrad', $input)
$text = htmlspecialchars($client->request, ENT_QUOTES)
$remove = array ("<"," x")
$insert = array ("<br><","<br> x")
Variable Documentation
$client = new nusoap_client($wsdl, false)
Definition at line 17 of file soap_server_test.php.
Referenced by callback(), dae_data_description(), dae_service_ocrad(), data_repository_service_client(), and query_client().
$input = array('name' => array('page_image' => 'testPara'))
Definition at line 39 of file soap_server_test.php.
Referenced by algorithm_execute(), algorithms_create_spool_directories(), algorithms_get_database_run_info_done(), algorithms_get_run_input_filename(), algorithms_run_form(), algorithms_run_form_submit(), algorithms_run_go(), create_database_flag(), dae_service_ocrad(), run_102(), run_124(), run_125(), run_143(), run_2(), run_82(), run_XX(), validatePreSelected(), and workflow_input_form_submit().
$input['username'] = 'admin'
Definition at line 40 of file soap_server_test.php.
$input['password'] = 'daepassword'
Definition at line 41 of file soap_server_test.php.
$insert = array ("<br><","<br> x")
Definition at line 55 of file soap_server_test.php.
$remove = array ("<"," x")
Definition at line 54 of file soap_server_test.php.
$result = $client->call('dae.ocrad', $input)
Definition at line 45 of file soap_server_test.php.
Referenced by TagCloud\__construct(), basicInfo(), callback(), check_version_page(), ct_select_content(), dae_data_browse_dataset_file(), dae_data_browse_dataset_page_element(), dae_data_browse_dataset_page_image(), dae_data_browse_runoptions(), dae_data_browse_subset(), dae_data_build_page_image_list(), dae_data_description(), dae_data_display_datasets(), dae_data_download_before(), dae_data_get_array_of_paths(), dae_data_get_dataset_hierarchy(), dae_data_get_dataset_info_array(), dae_data_get_dataset_leaves(), dae_data_get_drupal_db_list(), dae_data_get_file_info_array(), dae_data_get_page_element_info_array(), dae_data_get_pageimage_info_array(), dae_data_get_paths_from_result(), dae_query_pageimage(), dae_service_ocrad(), data_repository_service_client(), dataitem_service_descript(), declareDAEType(), getAllAlgIdName(), getProfileValue(), IOpart(), query_client(), DAEDatabase\r(), DAEDatabase\runElapsedTime(), DAEDatabase\runLength(), sel1(), and sel2().
$text = htmlspecialchars($client->request, ENT_QUOTES)
Definition at line 53 of file soap_server_test.php.
Referenced by convertXmlObjToArr(), parse_output(), and remove_header().
$user = NULL
Definition at line 20 of file soap_server_test.php.
$wsdl = 'http://localhost/dae/?q=services/soap'
Definition at line 10 of file soap_server_test.php.
Referenced by dae_data_description(), data_repository_service_client(), and query_client().
$client debug_flag = true
Definition at line 22 of file soap_server_test.php.