DAEDrupalInterface: modules/services/dae_service/soap_server_test.php File Reference
modules/services/dae_service/soap_server_test.php File Reference
Variables
$wsdl = 'http://localhost/dae/?q=services/soap'
$client = new nusoap_client($wsdl, false)
$user = NULL
$client debug_flag = true
$input = array('name' => array('page_image' => 'testPara'))
$input ['username'] = 'admin'
$input ['password'] = 'daepassword'
$result = $client->call('dae.ocrad', $input)
$text = htmlspecialchars($client->request, ENT_QUOTES)
$remove = array ("<"," x")
$insert = array ("<br><","<br> x")
Variable Documentation
$client = new nusoap_client($wsdl, false)
Definition at line 17 of file soap_server_test.php.
$input['password'] = 'daepassword'
Definition at line 41 of file soap_server_test.php.
$input['username'] = 'admin'
Definition at line 40 of file soap_server_test.php.
$input = array('name' => array('page_image' => 'testPara'))
Definition at line 39 of file soap_server_test.php.
$insert = array ("<br><","<br> x")
Definition at line 55 of file soap_server_test.php.
Referenced by dae_data_description(), and dae_data_description_debug().
$remove = array ("<"," x")
Definition at line 54 of file soap_server_test.php.
Referenced by dae_data_description(), and dae_data_description_debug().
$result = $client->call('dae.ocrad', $input)
Definition at line 45 of file soap_server_test.php.
$text = htmlspecialchars($client->request, ENT_QUOTES)
Definition at line 53 of file soap_server_test.php.
Referenced by dae_data_description(), dae_data_description_debug(), parse_output(), and remove_header().
$user = NULL
Definition at line 20 of file soap_server_test.php.
$wsdl = 'http://localhost/dae/?q=services/soap'
Definition at line 10 of file soap_server_test.php.
Referenced by dae_data_description(), and dae_data_description_debug().
$client debug_flag = true
Definition at line 22 of file soap_server_test.php.