DAEDrupalInterface: modules/soap_server/soap_server.module File Reference
modules/soap_server/soap_server.module File Reference
Functions
declareDAEType ($soap_server, $name, $id, $typeInfo)
soap_server_help ($path, $arg)
soap_server_menu ()
soap_server_admin_settings ()
soap_server_nusoap_path ()
soap_server_server_info ()
soap_server_server ()
soap_server ()
soap_call_wrapper ($method)
Variables
global $db
Detailed Description
The implementation of a SOAP Server for the Services module.
Listens on: services/soap
WSDL Interface: services/soap?wsdl
Cite original source from Drupal module.
This module has been significantly rewritten in order to accomodate the changes (especially new type definitions) required by the DAE project.
Definition in file soap_server.module.
Function Documentation
declareDAEType ($ soap_server, $ name, $ id, $ typeInfo)
there is no reason 'xsd:string' be hard-coded, here. This should be changed as soon as the data model accepts this. This can be done by using the currently (as of June 2011) unused DATATYPE.TYPE field.
we're supposing here that DATATYPE.names are unique ... the datamodel does not actually enforce this (although the user interface tries somehow to avoid having duplicate names)
Todo:
solve this typing issue in a more satisfactory way
Definition at line 26 of file soap_server.module.
References $db, and $result.
Referenced by soap_server().
soap_call_wrapper ($ method)
SOAP Server callback wrapper.
Definition at line 718 of file soap_server.module.
soap_server ()
Creates the SOAP server and manages its call
Added DAE specific code. This code connects to the DAE Database and retrieves all specific type names that serve as algorithm input and output. The code then proceeds to declaring these types to the SOAP server.
This specific DAE code doesn't feel right. It would be much nicer if each service, when published through the Drupal framework (i.e. when it's module gets activated) registers its input and output types to the server.
Definition at line 221 of file soap_server.module.
References declareDAEType(), getDAEDatabase(), retrieveAlgorithmSOAPInputTypes(), and retrieveAlgorithmSOAPOutputTypes().
Referenced by soap_server_server().
soap_server_admin_settings ()
Administration settings for the SOAP server.
Definition at line 162 of file soap_server.module.
References soap_server_nusoap_path().
soap_server_help ($ path, $ arg)
Implementation of hook_menu()
Definition at line 136 of file soap_server.module.
soap_server_menu ()
Implementation of hook_menu()
Definition at line 146 of file soap_server.module.
soap_server_nusoap_path ()
Retrieve the path where NuSOAP is installed
Definition at line 188 of file soap_server.module.
Referenced by soap_server_admin_settings(), and soap_server_server().
soap_server_server ()
Implementation of hook_server()
Definition at line 205 of file soap_server.module.
References soap_server(), and soap_server_nusoap_path().
soap_server_server_info ()
Implementation of hook_server_info()
Definition at line 195 of file soap_server.module.
Variable Documentation
global $db
Definition at line 21 of file soap_server.module.