DAEDrupalInterface: modules/soap_server/soap_server_original.module File Reference
modules/soap_server/soap_server_original.module File Reference
Functions
soap_server_help ($path, $arg)
soap_server_menu ()
soap_server_admin_settings ()
soap_server_nusoap_path ()
soap_server_server_info ()
soap_server_server ()
soap_server ()
soap_call_wrapper ($method)
Detailed Description
The implementation of a SOAP Server for the Services module.
Listens on: services/soap
WSDL Interface: services/soap?wsdl
Definition in file soap_server_original.module.
Function Documentation
soap_call_wrapper ($ method)
SOAP Server callback wrapper.
Definition at line 252 of file soap_server_original.module.
soap_server ()
Creates the SOAP server and manages its call
Definition at line 103 of file soap_server_original.module.
References soap_server().
soap_server_admin_settings ()
Administration settings for the SOAP server.
Definition at line 44 of file soap_server_original.module.
References soap_server_nusoap_path().
soap_server_help ($ path, $ arg)
Implementation of hook_menu()
Definition at line 18 of file soap_server_original.module.
soap_server_menu ()
Implementation of hook_menu()
Definition at line 28 of file soap_server_original.module.
soap_server_nusoap_path ()
Retrieve the path where NuSOAP is installed
Definition at line 70 of file soap_server_original.module.
soap_server_server ()
Implementation of hook_server()
Definition at line 87 of file soap_server_original.module.
References soap_server(), and soap_server_nusoap_path().
soap_server_server_info ()
Implementation of hook_server_info()
Definition at line 77 of file soap_server_original.module.