DAEDrupalInterface: modules/workflow/workflow.inc File Reference
modules/workflow/workflow.inc File Reference
The workflow module is.
Functions
workflow_generation ()
workflow_form ($form_state)
workflow_form_submit ()
workflow_output_form ($form_state)
workflow_output_form_submit ($form_state)
workflow_input_form ($form_state)
workflow_input_form_submit ($form_state)
createRequest ($method, $url, $type, $head, $data, $foot)
sendRequest ($url, $request)
do_post_request ($url, $data, $optional_headers=null)
createGetRequest ($url)
remove_header ($text)
parse_output ($text)
Detailed Description
The workflow module is.
Author:
Qihan Long <qil212lehigh.edu>
Version:
0.1
It consists of 3 files:
workflow.info (containing the module declaration for Drupal)
workflow.module (containing a simple menu callback declaration)
workflow.inc (the actual menu callback function)
workflow_input.inc (asks the user for the input for the workflow)
LICENSE
This file is part of the DAE Platform Project (DAE). It can be downloaded from http://sourceforge.net/projects/daeplatform/
DAE is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DAE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DAE. If not, see http://www.gnu.org/licenses/.
Definition in file workflow.inc.
Function Documentation
createGetRequest ($ url)
Definition at line 402 of file workflow.inc.
Referenced by workflow_output_form().
createRequest ($ method, $ url, $ type, $ head, $ data, $ foot)
Definition at line 331 of file workflow.inc.
Referenced by workflow_form_submit(), and workflow_input_form_submit().
do_post_request ($ url, $ data, $ optional_headers = null)
Definition at line 380 of file workflow.inc.
parse_output ($ text)
Definition at line 424 of file workflow.inc.
References $text.
Referenced by workflow_output_form().
remove_header ($ text)
Definition at line 411 of file workflow.inc.
References $text.
Referenced by workflow_output_form().
sendRequest ($ url, $ request)
Definition at line 347 of file workflow.inc.
Referenced by workflow_form_submit(), workflow_input_form_submit(), and workflow_output_form().
workflow_form ($ form_state)
Definition at line 64 of file workflow.inc.
workflow_form_submit ()
Definition at line 86 of file workflow.inc.
References createRequest(), and sendRequest().
workflow_generation ()
Implementation of callback function.
Definition at line 43 of file workflow.inc.
workflow_input_form ($ form_state)
Definition at line 252 of file workflow.inc.
workflow_input_form_submit ($ form_state)
Definition at line 284 of file workflow.inc.
References $input, createRequest(), and sendRequest().
workflow_output_form ($ form_state)
Definition at line 182 of file workflow.inc.
References createGetRequest(), parse_output(), remove_header(), and sendRequest().
workflow_output_form_submit ($ form_state)
Definition at line 242 of file workflow.inc.